"""Entity-agnostic aggregation engine for the public GraphQL API.

A caller builds an :class:`~public_api.aggregations.plan.AggregateQueryPlan`
from a GraphQL selection, hands it plus an already-scoped base queryset to
:func:`~public_api.aggregations.executor.build_aggregate_queryset`, and gets
back one row dict per non-empty group -- grouped and aggregated by Postgres,
in one query, with nothing reshaped in Python.

Which fields an entity may be grouped by or aggregated over, and which
operations each field's type accepts, is decided in
:mod:`public_api.aggregations.registry` and nowhere else.

The base queryset itself comes from a per-entity filter input in
:mod:`public_api.aggregations.filters`, which starts from the model's scoped
manager and narrows it to the caller's bounded date range.

What a caller may group by, at what bucket width, and what the group key
comes back as is in :mod:`public_api.aggregations.dimensions`; the IANA name
those buckets are measured in is resolved by
:mod:`public_api.aggregations.timezone`.

The six root fields are on the schema (:mod:`public_api.aggregations.fields`),
scoped by :mod:`public_api.aggregations.filters`'s mandatory bounded date
range. Post-aggregation filtering and metric ordering are typed per entity in
:mod:`public_api.aggregations.having` and
:mod:`public_api.aggregations.ordering`; running totals, moving averages, rank
and share-of-partition over those grouped rows are in
:mod:`public_api.aggregations.windows`, computed by Postgres in the same
statement. Later phases of
``ai-plans/2026-09-11-GRAPHQL_AGGREGATIONS_IMPLEMENTATION_PLAN.md`` add audit
logging and nested batching on top.
"""

from public_api.aggregations.dimensions import (
    GROUP_BY_INPUT_BY_ENTITY,
    GROUP_KEY_TYPE_BY_ENTITY,
    SCALAR_GROUP_BY_FIELD_BY_ENTITY,
    TEMPORAL_GROUP_BY_FIELD_BY_ENTITY,
    AppointmentTypeGroupByInput,
    AppointmentTypeGroupKey,
    AppointmentTypeScalarGroupByField,
    AppointmentTypeTemporalGroupByField,
    AppointmentTypeTemporalGroupByInput,
    AvailableTimeGroupByInput,
    AvailableTimeGroupKey,
    AvailableTimeScalarGroupByField,
    AvailableTimeTemporalGroupByField,
    AvailableTimeTemporalGroupByInput,
    BlockedTimeGroupByInput,
    BlockedTimeGroupKey,
    BlockedTimeScalarGroupByField,
    BlockedTimeTemporalGroupByField,
    BlockedTimeTemporalGroupByInput,
    CalendarEventGroupByInput,
    CalendarEventGroupKey,
    CalendarEventScalarGroupByField,
    CalendarEventTemporalGroupByField,
    CalendarEventTemporalGroupByInput,
    CalendarGroupByInput,
    CalendarGroupKey,
    CalendarPoolGroupByInput,
    CalendarPoolGroupKey,
    CalendarPoolScalarGroupByField,
    CalendarPoolTemporalGroupByField,
    CalendarPoolTemporalGroupByInput,
    CalendarScalarGroupByField,
    CalendarTemporalGroupByField,
    CalendarTemporalGroupByInput,
    build_group_key,
    resolve_dimensions,
    scalar_alias,
    temporal_alias,
)
from public_api.aggregations.errors import (
    AggregateTimeoutError,
    AggregationError,
    AggregationRequestError,
    AliasCollisionError,
    DateRangeExceededError,
    EmptyHavingComparisonError,
    EmptyHavingInputError,
    GroupByVariantError,
    InvalidPlanError,
    LimitOutOfRangeError,
    NonTemporalGranularityError,
    OffsetOutOfRangeError,
    OrderKeyNotGroupedError,
    OrderVariantError,
    QuerysetModelMismatchError,
    UnknownDimensionError,
    UnknownEntityError,
    UnknownMetricFieldError,
    UnknownTimezoneError,
    UnsupportedOperationError,
    UnsupportedPlanFeatureError,
    WindowFrameError,
    WindowOrderByRequiredError,
    WindowOrderKeyNotGroupedError,
    WindowOrderVariantError,
    WindowPartitionNotGroupedError,
)
from public_api.aggregations.executor import build_aggregate_queryset
from public_api.aggregations.fields import (
    appointment_type_aggregate,
    available_time_aggregate,
    blocked_time_aggregate,
    blocked_time_aggregate_for_calendar,
    calendar_aggregate,
    calendar_event_aggregate,
    calendar_event_aggregate_for_appointment_type,
    calendar_event_aggregate_for_calendar,
    calendar_event_aggregate_for_calendar_pool,
    calendar_pool_aggregate,
)
from public_api.aggregations.filters import (
    AppointmentTypeAggregateFilterInput,
    AvailableTimeAggregateFilterInput,
    BlockedTimeAggregateFilterInput,
    CalendarAggregateFilterInput,
    CalendarEventAggregateFilterInput,
    CalendarPoolAggregateFilterInput,
)
from public_api.aggregations.having import (
    HAVING_INPUT_BY_ENTITY,
    AppointmentTypeHavingInput,
    AvailableTimeHavingInput,
    BlockedTimeHavingInput,
    CalendarEventHavingInput,
    CalendarHavingInput,
    CalendarPoolHavingInput,
    FloatComparison,
    IntComparison,
    NumericAggregateComparison,
    resolve_having,
)
from public_api.aggregations.nested import (
    APPOINTMENT_TYPE_EVENTS,
    CALENDAR_BLOCKED_TIMES,
    CALENDAR_EVENTS,
    CALENDAR_POOL_EVENTS,
    NestedAggregateCollector,
    NestedAggregateLink,
    batch_key,
    collector_for,
    group_rows_by_parent,
    level_key,
)
from public_api.aggregations.ordering import (
    ORDER_INPUT_BY_ENTITY,
    AggregateOrderDirection,
    AppointmentTypeAggregateOrderInput,
    AppointmentTypeOrderableMetric,
    AvailableTimeAggregateOrderInput,
    AvailableTimeOrderableMetric,
    BlockedTimeAggregateOrderInput,
    BlockedTimeOrderableMetric,
    CalendarAggregateOrderInput,
    CalendarEventAggregateOrderInput,
    CalendarEventOrderableMetric,
    CalendarOrderableMetric,
    CalendarPoolAggregateOrderInput,
    CalendarPoolOrderableMetric,
    resolve_metric_reference,
    resolve_order_by,
)
from public_api.aggregations.output_types import (
    ROW_TYPE_BY_ENTITY,
    AppointmentTypeAggregateRow,
    AvailableTimeAggregateRow,
    BlockedTimeAggregateRow,
    CalendarAggregateRow,
    CalendarEventAggregateRow,
    CalendarPoolAggregateRow,
)
from public_api.aggregations.plan import (
    MAX_AGGREGATE_LIMIT,
    MIN_AGGREGATE_LIMIT,
    PARENT_KEY_ALIAS,
    ROW_COUNT_ALIAS,
    ROW_COUNT_FIELD_PATH,
    AggregatableEntity,
    AggregateOp,
    AggregateQueryPlan,
    ComparisonOp,
    DimensionSpec,
    FilterBounds,
    HavingComparison,
    HavingSpec,
    MetricSpec,
    OrderDirection,
    OrderSpec,
    ParentKeySpec,
    WindowBound,
    WindowFrameSpec,
    WindowFrameType,
    WindowFunctionKind,
    WindowSpec,
    default_metric_alias,
    window_alias,
)
from public_api.aggregations.registry import (
    AGGREGATE_TYPE_BY_KIND,
    OPS_BY_KIND,
    AggregatableField,
    EntityRegistration,
    FieldKind,
    GroupableDimension,
    RelationCount,
    aggregate_type_for,
    get_registration,
    registered_entities,
    supported_ops,
)
from public_api.aggregations.timezone import resolve_bucketing_timezone
from public_api.aggregations.types import (
    BooleanAggregate,
    DateTimeAggregate,
    NumericAggregate,
    StringAggregate,
    TemporalGranularity,
)
from public_api.aggregations.windows import (
    WINDOW_INPUT_BY_ENTITY,
    WINDOW_METRICS_TYPE_BY_ENTITY,
    AppointmentTypeWindowInput,
    AppointmentTypeWindowMetrics,
    AppointmentTypeWindowOrderInput,
    AvailableTimeWindowInput,
    AvailableTimeWindowMetrics,
    AvailableTimeWindowOrderInput,
    BlockedTimeWindowInput,
    BlockedTimeWindowMetrics,
    BlockedTimeWindowOrderInput,
    CalendarEventWindowInput,
    CalendarEventWindowMetrics,
    CalendarEventWindowOrderInput,
    CalendarPoolWindowInput,
    CalendarPoolWindowMetrics,
    CalendarPoolWindowOrderInput,
    CalendarWindowInput,
    CalendarWindowMetrics,
    CalendarWindowOrderInput,
    WindowFrameInput,
    build_window_metrics,
    resolve_frame,
    resolve_window,
    selected_window_kinds,
)


__all__ = [
    "AGGREGATE_TYPE_BY_KIND",
    "APPOINTMENT_TYPE_EVENTS",
    "CALENDAR_BLOCKED_TIMES",
    "CALENDAR_EVENTS",
    "CALENDAR_POOL_EVENTS",
    "GROUP_BY_INPUT_BY_ENTITY",
    "GROUP_KEY_TYPE_BY_ENTITY",
    "HAVING_INPUT_BY_ENTITY",
    "MAX_AGGREGATE_LIMIT",
    "MIN_AGGREGATE_LIMIT",
    "OPS_BY_KIND",
    "ORDER_INPUT_BY_ENTITY",
    "PARENT_KEY_ALIAS",
    "ROW_COUNT_ALIAS",
    "ROW_COUNT_FIELD_PATH",
    "ROW_TYPE_BY_ENTITY",
    "SCALAR_GROUP_BY_FIELD_BY_ENTITY",
    "TEMPORAL_GROUP_BY_FIELD_BY_ENTITY",
    "WINDOW_INPUT_BY_ENTITY",
    "WINDOW_METRICS_TYPE_BY_ENTITY",
    "AggregatableEntity",
    "AggregatableField",
    "AggregateOp",
    "AggregateOrderDirection",
    "AggregateQueryPlan",
    "AggregateTimeoutError",
    "AggregationError",
    "AggregationRequestError",
    "AliasCollisionError",
    "AppointmentTypeAggregateFilterInput",
    "AppointmentTypeAggregateOrderInput",
    "AppointmentTypeAggregateRow",
    "AppointmentTypeGroupByInput",
    "AppointmentTypeGroupKey",
    "AppointmentTypeHavingInput",
    "AppointmentTypeOrderableMetric",
    "AppointmentTypeScalarGroupByField",
    "AppointmentTypeTemporalGroupByField",
    "AppointmentTypeTemporalGroupByInput",
    "AppointmentTypeWindowInput",
    "AppointmentTypeWindowMetrics",
    "AppointmentTypeWindowOrderInput",
    "AvailableTimeAggregateFilterInput",
    "AvailableTimeAggregateOrderInput",
    "AvailableTimeAggregateRow",
    "AvailableTimeGroupByInput",
    "AvailableTimeGroupKey",
    "AvailableTimeHavingInput",
    "AvailableTimeOrderableMetric",
    "AvailableTimeScalarGroupByField",
    "AvailableTimeTemporalGroupByField",
    "AvailableTimeTemporalGroupByInput",
    "AvailableTimeWindowInput",
    "AvailableTimeWindowMetrics",
    "AvailableTimeWindowOrderInput",
    "BlockedTimeAggregateFilterInput",
    "BlockedTimeAggregateOrderInput",
    "BlockedTimeAggregateRow",
    "BlockedTimeGroupByInput",
    "BlockedTimeGroupKey",
    "BlockedTimeHavingInput",
    "BlockedTimeOrderableMetric",
    "BlockedTimeScalarGroupByField",
    "BlockedTimeTemporalGroupByField",
    "BlockedTimeTemporalGroupByInput",
    "BlockedTimeWindowInput",
    "BlockedTimeWindowMetrics",
    "BlockedTimeWindowOrderInput",
    "BooleanAggregate",
    "CalendarAggregateFilterInput",
    "CalendarAggregateOrderInput",
    "CalendarAggregateRow",
    "CalendarEventAggregateFilterInput",
    "CalendarEventAggregateOrderInput",
    "CalendarEventAggregateRow",
    "CalendarEventGroupByInput",
    "CalendarEventGroupKey",
    "CalendarEventHavingInput",
    "CalendarEventOrderableMetric",
    "CalendarEventScalarGroupByField",
    "CalendarEventTemporalGroupByField",
    "CalendarEventTemporalGroupByInput",
    "CalendarEventWindowInput",
    "CalendarEventWindowMetrics",
    "CalendarEventWindowOrderInput",
    "CalendarGroupByInput",
    "CalendarGroupKey",
    "CalendarHavingInput",
    "CalendarOrderableMetric",
    "CalendarPoolAggregateFilterInput",
    "CalendarPoolAggregateOrderInput",
    "CalendarPoolAggregateRow",
    "CalendarPoolGroupByInput",
    "CalendarPoolGroupKey",
    "CalendarPoolHavingInput",
    "CalendarPoolOrderableMetric",
    "CalendarPoolScalarGroupByField",
    "CalendarPoolTemporalGroupByField",
    "CalendarPoolTemporalGroupByInput",
    "CalendarPoolWindowInput",
    "CalendarPoolWindowMetrics",
    "CalendarPoolWindowOrderInput",
    "CalendarScalarGroupByField",
    "CalendarTemporalGroupByField",
    "CalendarTemporalGroupByInput",
    "CalendarWindowInput",
    "CalendarWindowMetrics",
    "CalendarWindowOrderInput",
    "ComparisonOp",
    "DateRangeExceededError",
    "DateTimeAggregate",
    "DimensionSpec",
    "EmptyHavingComparisonError",
    "EmptyHavingInputError",
    "EntityRegistration",
    "FieldKind",
    "FilterBounds",
    "FloatComparison",
    "GroupByVariantError",
    "GroupableDimension",
    "HavingComparison",
    "HavingSpec",
    "IntComparison",
    "InvalidPlanError",
    "LimitOutOfRangeError",
    "MetricSpec",
    "NestedAggregateCollector",
    "NestedAggregateLink",
    "NonTemporalGranularityError",
    "NumericAggregate",
    "NumericAggregateComparison",
    "OffsetOutOfRangeError",
    "OrderDirection",
    "OrderKeyNotGroupedError",
    "OrderSpec",
    "OrderVariantError",
    "ParentKeySpec",
    "QuerysetModelMismatchError",
    "RelationCount",
    "StringAggregate",
    "TemporalGranularity",
    "UnknownDimensionError",
    "UnknownEntityError",
    "UnknownMetricFieldError",
    "UnknownTimezoneError",
    "UnsupportedOperationError",
    "UnsupportedPlanFeatureError",
    "WindowBound",
    "WindowFrameError",
    "WindowFrameInput",
    "WindowFrameSpec",
    "WindowFrameType",
    "WindowFunctionKind",
    "WindowOrderByRequiredError",
    "WindowOrderKeyNotGroupedError",
    "WindowOrderVariantError",
    "WindowPartitionNotGroupedError",
    "WindowSpec",
    "aggregate_type_for",
    "appointment_type_aggregate",
    "available_time_aggregate",
    "batch_key",
    "blocked_time_aggregate",
    "blocked_time_aggregate_for_calendar",
    "build_aggregate_queryset",
    "build_group_key",
    "build_window_metrics",
    "calendar_aggregate",
    "calendar_event_aggregate",
    "calendar_event_aggregate_for_appointment_type",
    "calendar_event_aggregate_for_calendar",
    "calendar_event_aggregate_for_calendar_pool",
    "calendar_pool_aggregate",
    "collector_for",
    "default_metric_alias",
    "get_registration",
    "group_rows_by_parent",
    "level_key",
    "registered_entities",
    "resolve_bucketing_timezone",
    "resolve_dimensions",
    "resolve_frame",
    "resolve_having",
    "resolve_metric_reference",
    "resolve_order_by",
    "resolve_window",
    "scalar_alias",
    "selected_window_kinds",
    "supported_ops",
    "temporal_alias",
    "window_alias",
]
