"""Entity-agnostic aggregation engine for the public GraphQL API.

A caller builds an :class:`~public_api.aggregations.plan.AggregateQueryPlan`
from a GraphQL selection, hands it plus an already-scoped base queryset to
:func:`~public_api.aggregations.executor.build_aggregate_queryset`, and gets
back one row dict per non-empty group -- grouped and aggregated by Postgres,
in one query, with nothing reshaped in Python.

Which fields an entity may be grouped by or aggregated over, and which
operations each field's type accepts, is decided in
:mod:`public_api.aggregations.registry` and nowhere else.

The base queryset itself comes from a per-entity filter input in
:mod:`public_api.aggregations.filters`, which starts from the model's scoped
manager and narrows it to the caller's bounded date range.

What a caller may group by, at what bucket width, and what the group key
comes back as is in :mod:`public_api.aggregations.dimensions`; the IANA name
those buckets are measured in is resolved by
:mod:`public_api.aggregations.timezone`.

Nothing here is on the schema yet. Later phases of
``ai-plans/2026-09-11-GRAPHQL_AGGREGATIONS_IMPLEMENTATION_PLAN.md`` add the
six root fields, HAVING, audit logging, window functions and nested batching
on top.
"""

from public_api.aggregations.dimensions import (
    GROUP_BY_INPUT_BY_ENTITY,
    GROUP_KEY_TYPE_BY_ENTITY,
    SCALAR_GROUP_BY_FIELD_BY_ENTITY,
    TEMPORAL_GROUP_BY_FIELD_BY_ENTITY,
    AppointmentTypeGroupByInput,
    AppointmentTypeGroupKey,
    AppointmentTypeScalarGroupByField,
    AppointmentTypeTemporalGroupByField,
    AppointmentTypeTemporalGroupByInput,
    AvailableTimeGroupByInput,
    AvailableTimeGroupKey,
    AvailableTimeScalarGroupByField,
    AvailableTimeTemporalGroupByField,
    AvailableTimeTemporalGroupByInput,
    BlockedTimeGroupByInput,
    BlockedTimeGroupKey,
    BlockedTimeScalarGroupByField,
    BlockedTimeTemporalGroupByField,
    BlockedTimeTemporalGroupByInput,
    CalendarEventGroupByInput,
    CalendarEventGroupKey,
    CalendarEventScalarGroupByField,
    CalendarEventTemporalGroupByField,
    CalendarEventTemporalGroupByInput,
    CalendarGroupByInput,
    CalendarGroupKey,
    CalendarPoolGroupByInput,
    CalendarPoolGroupKey,
    CalendarPoolScalarGroupByField,
    CalendarPoolTemporalGroupByField,
    CalendarPoolTemporalGroupByInput,
    CalendarScalarGroupByField,
    CalendarTemporalGroupByField,
    CalendarTemporalGroupByInput,
    build_group_key,
    resolve_dimensions,
    scalar_alias,
    temporal_alias,
)
from public_api.aggregations.errors import (
    AggregateTimeoutError,
    AggregationError,
    AggregationRequestError,
    AliasCollisionError,
    DateRangeExceededError,
    GroupByVariantError,
    InvalidPlanError,
    LimitOutOfRangeError,
    NonTemporalGranularityError,
    QuerysetModelMismatchError,
    UnknownDimensionError,
    UnknownEntityError,
    UnknownMetricFieldError,
    UnknownTimezoneError,
    UnsupportedOperationError,
    UnsupportedPlanFeatureError,
)
from public_api.aggregations.executor import build_aggregate_queryset
from public_api.aggregations.filters import (
    AppointmentTypeAggregateFilterInput,
    AvailableTimeAggregateFilterInput,
    BlockedTimeAggregateFilterInput,
    CalendarAggregateFilterInput,
    CalendarEventAggregateFilterInput,
    CalendarPoolAggregateFilterInput,
)
from public_api.aggregations.plan import (
    MAX_AGGREGATE_LIMIT,
    MIN_AGGREGATE_LIMIT,
    ROW_COUNT_FIELD_PATH,
    AggregatableEntity,
    AggregateOp,
    AggregateQueryPlan,
    DimensionSpec,
    FilterBounds,
    HavingSpec,
    MetricSpec,
    OrderDirection,
    OrderSpec,
    WindowSpec,
)
from public_api.aggregations.registry import (
    AGGREGATE_TYPE_BY_KIND,
    OPS_BY_KIND,
    AggregatableField,
    EntityRegistration,
    FieldKind,
    GroupableDimension,
    RelationCount,
    aggregate_type_for,
    get_registration,
    registered_entities,
    supported_ops,
)
from public_api.aggregations.timezone import resolve_bucketing_timezone
from public_api.aggregations.types import (
    BooleanAggregate,
    DateTimeAggregate,
    NumericAggregate,
    StringAggregate,
    TemporalGranularity,
)


__all__ = [
    "AGGREGATE_TYPE_BY_KIND",
    "GROUP_BY_INPUT_BY_ENTITY",
    "GROUP_KEY_TYPE_BY_ENTITY",
    "MAX_AGGREGATE_LIMIT",
    "MIN_AGGREGATE_LIMIT",
    "OPS_BY_KIND",
    "ROW_COUNT_FIELD_PATH",
    "SCALAR_GROUP_BY_FIELD_BY_ENTITY",
    "TEMPORAL_GROUP_BY_FIELD_BY_ENTITY",
    "AggregatableEntity",
    "AggregatableField",
    "AggregateOp",
    "AggregateQueryPlan",
    "AggregateTimeoutError",
    "AggregationError",
    "AggregationRequestError",
    "AliasCollisionError",
    "AppointmentTypeAggregateFilterInput",
    "AppointmentTypeGroupByInput",
    "AppointmentTypeGroupKey",
    "AppointmentTypeScalarGroupByField",
    "AppointmentTypeTemporalGroupByField",
    "AppointmentTypeTemporalGroupByInput",
    "AvailableTimeAggregateFilterInput",
    "AvailableTimeGroupByInput",
    "AvailableTimeGroupKey",
    "AvailableTimeScalarGroupByField",
    "AvailableTimeTemporalGroupByField",
    "AvailableTimeTemporalGroupByInput",
    "BlockedTimeAggregateFilterInput",
    "BlockedTimeGroupByInput",
    "BlockedTimeGroupKey",
    "BlockedTimeScalarGroupByField",
    "BlockedTimeTemporalGroupByField",
    "BlockedTimeTemporalGroupByInput",
    "BooleanAggregate",
    "CalendarAggregateFilterInput",
    "CalendarEventAggregateFilterInput",
    "CalendarEventGroupByInput",
    "CalendarEventGroupKey",
    "CalendarEventScalarGroupByField",
    "CalendarEventTemporalGroupByField",
    "CalendarEventTemporalGroupByInput",
    "CalendarGroupByInput",
    "CalendarGroupKey",
    "CalendarPoolAggregateFilterInput",
    "CalendarPoolGroupByInput",
    "CalendarPoolGroupKey",
    "CalendarPoolScalarGroupByField",
    "CalendarPoolTemporalGroupByField",
    "CalendarPoolTemporalGroupByInput",
    "CalendarScalarGroupByField",
    "CalendarTemporalGroupByField",
    "CalendarTemporalGroupByInput",
    "DateRangeExceededError",
    "DateTimeAggregate",
    "DimensionSpec",
    "EntityRegistration",
    "FieldKind",
    "FilterBounds",
    "GroupByVariantError",
    "GroupableDimension",
    "HavingSpec",
    "InvalidPlanError",
    "LimitOutOfRangeError",
    "MetricSpec",
    "NonTemporalGranularityError",
    "NumericAggregate",
    "OrderDirection",
    "OrderSpec",
    "QuerysetModelMismatchError",
    "RelationCount",
    "StringAggregate",
    "TemporalGranularity",
    "UnknownDimensionError",
    "UnknownEntityError",
    "UnknownMetricFieldError",
    "UnknownTimezoneError",
    "UnsupportedOperationError",
    "UnsupportedPlanFeatureError",
    "WindowSpec",
    "aggregate_type_for",
    "build_aggregate_queryset",
    "build_group_key",
    "get_registration",
    "registered_entities",
    "resolve_bucketing_timezone",
    "resolve_dimensions",
    "scalar_alias",
    "supported_ops",
    "temporal_alias",
]
