"""Temporal bucketing against real rows — the load-bearing test of this phase.

Every assertion here is about the same question: whose day is it? The rows store
a local wall clock plus their own IANA name, and the aggregate cuts buckets on a
clock the caller names, so the same four events land in different buckets
depending on the timezone the query asked for. If that is wrong nothing raises —
the numbers are just quietly attributed to the wrong days.
"""

import datetime
from zoneinfo import ZoneInfo

from django.db import connection
from django.test.utils import CaptureQueriesContext

import pytest
from model_bakery import baker

from calendar_integration.constants import CalendarProvider
from calendar_integration.models import Calendar, CalendarEvent
from common.organization_context import organization_context
from organizations.models import Organization
from public_api.aggregations.dimensions import (
    CalendarEventGroupByInput,
    CalendarEventTemporalGroupBy,
    CalendarEventTemporalGroupByField,
    resolve_group_by_inputs,
)
from public_api.aggregations.executor import execute_aggregate_plan
from public_api.aggregations.plan import AggregatableEntity, AggregateOp, AggregateQueryPlan
from public_api.aggregations.registry import build_metric
from public_api.aggregations.types import TemporalGranularity


SAO_PAULO = ZoneInfo("America/Sao_Paulo")
NEW_YORK = ZoneInfo("America/New_York")
UTC = ZoneInfo("UTC")

EVENT = AggregatableEntity.CALENDAR_EVENT


def _make_event(
    organization: Organization,
    calendar: Calendar,
    *,
    external_id: str,
    utc_start: datetime.datetime,
    minutes: int = 30,
) -> CalendarEvent:
    """Create an event whose ``start_time`` is exactly ``utc_start``.

    ``start_time`` is generated by ``convert_naive_utc_to_timezone`` over the
    naive column and the row's own IANA name, so storing the naive value with
    ``timezone="UTC"`` pins the instant. The row's own timezone is deliberately
    not the one the aggregate buckets in — that separation is the whole point.
    """
    return baker.make(
        CalendarEvent,
        organization=organization,
        calendar=calendar,
        external_id=external_id,
        title=external_id,
        timezone="UTC",
        start_time_tz_unaware=utc_start,
        end_time_tz_unaware=utc_start + datetime.timedelta(minutes=minutes),
    )


def _bucket_plan(
    field: CalendarEventTemporalGroupByField,
    granularity: TemporalGranularity,
    tzinfo: ZoneInfo,
) -> AggregateQueryPlan:
    resolved = resolve_group_by_inputs(
        EVENT,
        [
            CalendarEventGroupByInput(
                temporal=CalendarEventTemporalGroupBy(field=field, granularity=granularity)
            )
        ],
        tzinfo,
    )
    return AggregateQueryPlan(
        entity=EVENT,
        dimensions=tuple(one.dimension for one in resolved),
        metrics=(build_metric(EVENT, "count", AggregateOp.COUNT, alias="count"),),
    )


def _day_counts(organization: Organization, tzinfo: ZoneInfo) -> dict[datetime.datetime, int]:
    plan = _bucket_plan(
        CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.DAY, tzinfo
    )
    with organization_context(organization):
        rows = execute_aggregate_plan(plan, CalendarEvent.objects.all())
    return {row["start_time_day"]: row["count"] for row in rows}


@pytest.fixture
def organization() -> Organization:
    return baker.make(Organization, name="Bucketing Org")


@pytest.fixture
def calendar(organization) -> Calendar:
    return baker.make(
        Calendar,
        organization=organization,
        name="Bucketing Calendar",
        external_id="bucket-cal",
        provider=CalendarProvider.INTERNAL,
    )


@pytest.mark.django_db
class TestLocalMidnight:
    """São Paulo is UTC-3, so its midnight is 03:00 UTC.

    Two events 30 minutes either side of that instant are on different local
    days in São Paulo and on the same UTC day.
    """

    @pytest.fixture(autouse=True)
    def events(self, organization, calendar):
        _make_event(
            organization,
            calendar,
            external_id="before-midnight",
            utc_start=datetime.datetime(2026, 3, 3, 2, 30),
        )
        _make_event(
            organization,
            calendar,
            external_id="after-midnight",
            utc_start=datetime.datetime(2026, 3, 3, 3, 30),
        )

    def test_the_two_events_land_in_different_sao_paulo_days(self, organization):
        assert _day_counts(organization, SAO_PAULO) == {
            datetime.datetime(2026, 3, 2, tzinfo=SAO_PAULO): 1,
            datetime.datetime(2026, 3, 3, tzinfo=SAO_PAULO): 1,
        }

    def test_the_same_two_events_land_in_one_utc_day(self, organization):
        assert _day_counts(organization, UTC) == {
            datetime.datetime(2026, 3, 3, tzinfo=UTC): 2,
        }

    def test_a_bucket_is_local_midnight_on_the_named_clock(self, organization):
        buckets = list(_day_counts(organization, SAO_PAULO))

        for bucket in buckets:
            assert bucket.utcoffset() == datetime.timedelta(hours=-3)
            assert (bucket.hour, bucket.minute) == (0, 0)


@pytest.mark.django_db
class TestDaylightSavingBoundary:
    """New York springs forward on 2026-03-08: 02:00 EST becomes 03:00 EDT.

    The local day 2026-03-08 is 23 hours long, so it ends at 04:00 UTC on the
    9th rather than 05:00. An implementation that adds a fixed 24 hours to the
    day's start would put ``just-after-midnight-on-the-9th`` on the 8th.
    """

    @pytest.fixture(autouse=True)
    def events(self, organization, calendar):
        # 01:00 EST on the 8th, before the transition.
        _make_event(
            organization,
            calendar,
            external_id="before-transition",
            utc_start=datetime.datetime(2026, 3, 8, 6, 0),
        )
        # 04:00 EDT on the 8th, after the transition.
        _make_event(
            organization,
            calendar,
            external_id="after-transition",
            utc_start=datetime.datetime(2026, 3, 8, 8, 0),
        )
        # 23:30 EDT on the 8th — the last half hour of a 23-hour day.
        _make_event(
            organization,
            calendar,
            external_id="end-of-short-day",
            utc_start=datetime.datetime(2026, 3, 9, 3, 30),
        )
        # 00:30 EDT on the 9th. A fixed-24-hour day would swallow this one.
        _make_event(
            organization,
            calendar,
            external_id="start-of-next-day",
            utc_start=datetime.datetime(2026, 3, 9, 4, 30),
        )

    def test_events_are_bucketed_by_local_day_across_the_transition(self, organization):
        assert _day_counts(organization, NEW_YORK) == {
            datetime.datetime(2026, 3, 8, tzinfo=NEW_YORK): 3,
            datetime.datetime(2026, 3, 9, tzinfo=NEW_YORK): 1,
        }

    def test_the_bucket_offsets_change_across_the_transition(self, organization):
        counts = _day_counts(organization, NEW_YORK)
        eighth = datetime.datetime(2026, 3, 8, tzinfo=NEW_YORK)
        ninth = datetime.datetime(2026, 3, 9, tzinfo=NEW_YORK)

        assert counts[eighth] == 3
        assert counts[ninth] == 1
        assert eighth.utcoffset() == datetime.timedelta(hours=-5)
        assert ninth.utcoffset() == datetime.timedelta(hours=-4)

    def test_utc_disagrees_with_new_york_about_which_day_it_is(self, organization):
        """The same four events, cut on a clock with no transition."""
        assert _day_counts(organization, UTC) == {
            datetime.datetime(2026, 3, 8, tzinfo=UTC): 2,
            datetime.datetime(2026, 3, 9, tzinfo=UTC): 2,
        }


@pytest.mark.django_db
class TestWeekAndMonthBuckets:
    @pytest.fixture(autouse=True)
    def events(self, organization, calendar):
        # 2026-03-02 is a Monday; 2026-03-08 the Sunday that closes its week.
        for day, external_id in (
            (2, "monday"),
            (5, "thursday"),
            (8, "sunday"),
            (9, "next-monday"),
        ):
            _make_event(
                organization,
                calendar,
                external_id=external_id,
                utc_start=datetime.datetime(2026, 3, day, 12, 0),
            )
        _make_event(
            organization,
            calendar,
            external_id="april",
            utc_start=datetime.datetime(2026, 4, 1, 12, 0),
        )

    def test_a_week_bucket_starts_on_monday_and_ends_on_sunday(self, organization):
        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.WEEK, UTC
        )
        with organization_context(organization):
            rows = execute_aggregate_plan(plan, CalendarEvent.objects.all())

        counts = {row["start_time_week"]: row["count"] for row in rows}
        first_week = datetime.datetime(2026, 3, 2, tzinfo=UTC)
        second_week = datetime.datetime(2026, 3, 9, tzinfo=UTC)
        april_week = datetime.datetime(2026, 3, 30, tzinfo=UTC)

        assert first_week.weekday() == 0
        assert counts == {first_week: 3, second_week: 1, april_week: 1}

    def test_a_month_bucket_is_the_first_of_the_month(self, organization):
        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.MONTH, UTC
        )
        with organization_context(organization):
            rows = execute_aggregate_plan(plan, CalendarEvent.objects.all())

        assert {row["start_time_month"]: row["count"] for row in rows} == {
            datetime.datetime(2026, 3, 1, tzinfo=UTC): 4,
            datetime.datetime(2026, 4, 1, tzinfo=UTC): 1,
        }

    def test_created_can_be_bucketed_too(self, organization):
        """Every entity can bucket on ``created``, not only on a start time."""
        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.CREATED, TemporalGranularity.MONTH, UTC
        )
        with organization_context(organization):
            rows = execute_aggregate_plan(plan, CalendarEvent.objects.all())

        assert sum(row["count"] for row in rows) == 5


@pytest.mark.django_db
class TestSparseBuckets:
    def test_a_day_with_no_events_produces_no_row(self, organization, calendar):
        """Zero-filling is the client's job; the aggregate never invents a row."""
        _make_event(
            organization,
            calendar,
            external_id="first",
            utc_start=datetime.datetime(2026, 3, 2, 12, 0),
        )
        _make_event(
            organization,
            calendar,
            external_id="fourth",
            utc_start=datetime.datetime(2026, 3, 5, 12, 0),
        )

        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.DAY, UTC
        )
        with organization_context(organization):
            rows = execute_aggregate_plan(
                plan,
                CalendarEvent.objects.filter(
                    start_time__gte=datetime.datetime(2026, 3, 1, tzinfo=UTC),
                    start_time__lt=datetime.datetime(2026, 3, 8, tzinfo=UTC),
                ),
            )

        assert rows == [
            {"start_time_day": datetime.datetime(2026, 3, 2, tzinfo=UTC), "count": 1},
            {"start_time_day": datetime.datetime(2026, 3, 5, tzinfo=UTC), "count": 1},
        ]

    def test_an_empty_range_produces_no_rows_at_all(self, organization, calendar):
        _make_event(
            organization,
            calendar,
            external_id="outside",
            utc_start=datetime.datetime(2026, 3, 2, 12, 0),
        )

        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.DAY, UTC
        )
        with organization_context(organization):
            rows = execute_aggregate_plan(
                plan,
                CalendarEvent.objects.filter(
                    start_time__gte=datetime.datetime(2026, 4, 1, tzinfo=UTC),
                    start_time__lt=datetime.datetime(2026, 4, 8, tzinfo=UTC),
                ),
            )

        assert rows == []


@pytest.mark.django_db
class TestGeneratedSql:
    def test_bucketing_is_one_query_that_truncates_in_the_database(self, organization, calendar):
        _make_event(
            organization,
            calendar,
            external_id="sql",
            utc_start=datetime.datetime(2026, 3, 2, 12, 0),
        )
        plan = _bucket_plan(
            CalendarEventTemporalGroupByField.START_TIME, TemporalGranularity.DAY, SAO_PAULO
        )

        with organization_context(organization):
            with CaptureQueriesContext(connection) as captured:
                rows = execute_aggregate_plan(plan, CalendarEvent.objects.all())

        assert len(rows) == 1
        assert len(captured.captured_queries) == 1
        sql = captured.captured_queries[0]["sql"]
        assert "DATE_TRUNC" in sql.upper()
        assert "GROUP BY" in sql.upper()
        assert "America/Sao_Paulo" in sql
