"""The group-by surface: what may be named, and what happens when it is not.

Two claims carry this module. The enums are the schema's half of the contract
and must match the registry exactly -- a dimension in one and not the other is
either a field a caller can see and no resolver can honour, or one the engine
supports and nobody can ask for. And a timezone the runtime cannot resolve is
refused with a fixed message, because the name is caller-supplied text that
would otherwise reach the response body and every log line recording it.

No database here: an enum, an input object and a timezone name are all resolved
without one.
"""

import dataclasses
import zoneinfo

import pytest

from public_api.aggregations.dimensions import (
    GROUP_BY_INPUT_TYPE_BY_ENTITY,
    GROUP_KEY_TYPE_BY_ENTITY,
    AppointmentTypeGroupByInput,
    AppointmentTypeScalarGroupByField,
    CalendarEventGroupByInput,
    CalendarEventGroupKey,
    CalendarEventScalarGroupByField,
    CalendarEventTemporalGroupBy,
    CalendarEventTemporalGroupByField,
    CalendarGroupByInput,
    CalendarPoolGroupByInput,
    CalendarPoolTemporalGroupBy,
    CalendarPoolTemporalGroupByField,
    CalendarScalarGroupByField,
    build_group_key,
    dimensions_from_group_by,
    validate_dimension_enums,
)
from public_api.aggregations.errors import (
    AmbiguousGroupByError,
    DuplicateGroupKeyFieldError,
    UnknownTimezoneError,
)
from public_api.aggregations.plan import AggregatableEntity
from public_api.aggregations.registry import get_registration
from public_api.aggregations.timezone import resolve_timezone
from public_api.aggregations.types import TemporalGranularity


ALL_ENTITIES = tuple(AggregatableEntity)
SAO_PAULO = zoneinfo.ZoneInfo("America/Sao_Paulo")


class TestTheEnumsMatchTheRegistry:
    """The enums are generated by hand, so drift is checked rather than assumed."""

    def test_the_import_time_conformance_check_passes(self):
        # Already run at import; calling it again makes the guarantee visible
        # in the suite rather than only in a traceback nobody sees.
        validate_dimension_enums()

    @pytest.mark.parametrize("entity", ALL_ENTITIES)
    def test_every_entity_has_a_group_by_input_and_a_group_key(self, entity):
        assert entity in GROUP_BY_INPUT_TYPE_BY_ENTITY
        assert entity in GROUP_KEY_TYPE_BY_ENTITY

    @pytest.mark.parametrize("entity", ALL_ENTITIES)
    def test_the_group_key_has_a_nullable_field_per_registered_dimension(self, entity):
        registration = get_registration(entity)
        key_fields = {
            field.name: field for field in dataclasses.fields(GROUP_KEY_TYPE_BY_ENTITY[entity])
        }

        for dimension in registration.groupable:
            assert dimension.name in key_fields, f"{entity} key has no {dimension.name}"
            # Populated only for the dimensions a query named, so every one of
            # them has to default to null.
            assert key_fields[dimension.name].default is None

    def test_the_calendar_event_enums_partition_its_dimensions(self):
        scalar = {member.value for member in CalendarEventScalarGroupByField}
        temporal = {member.value for member in CalendarEventTemporalGroupByField}

        assert scalar == {
            "calendar_id",
            "appointment_type_id",
            "bundle_calendar_id",
            "is_bundle_primary",
            "is_recurring_exception",
            "timezone",
        }
        assert temporal == {"start_time", "end_time", "created", "modified"}
        assert scalar & temporal == set()

    def test_a_field_that_is_not_groupable_is_not_in_any_enum(self):
        # ``title`` is aggregatable but never a dimension: grouping by it would
        # produce one group per row.
        members = {member.value for member in CalendarEventScalarGroupByField} | {
            member.value for member in CalendarEventTemporalGroupByField
        }

        assert "title" not in members
        assert "description" not in members
        assert "duration_minutes" not in members

    def test_a_temporal_field_is_absent_from_the_scalar_enum(self):
        # This absence is the type-level guarantee: there is no shape in which a
        # granularity can be attached to a non-temporal dimension, because the
        # granularity lives inside the temporal variant and that variant's enum
        # holds only temporal fields.
        scalar_values = {member.value for member in CalendarEventScalarGroupByField}

        assert "start_time" not in scalar_values
        assert "created" not in scalar_values

    def test_a_calendar_pool_has_no_scalar_variant(self):
        # Its only columns are a name and a description, whose cardinality is
        # the row count. Temporal is the only honest dimension.
        assert not hasattr(CalendarPoolGroupByInput, "scalar")
        assert {member.value for member in CalendarPoolTemporalGroupByField} == {
            "created",
            "modified",
        }


class TestTimezoneResolution:
    def test_a_known_iana_name_resolves(self):
        assert resolve_timezone("America/Sao_Paulo") == SAO_PAULO
        assert resolve_timezone("UTC") == zoneinfo.ZoneInfo("UTC")

    @pytest.mark.parametrize(
        "name",
        [
            "Mars/Olympus_Mons",
            "america/sao_paulo",
            "UTC+3",
            "",
            "   ",
            "../../etc/passwd",
            "/etc/passwd",
            "America/Sao_Paulo\x00",
        ],
    )
    def test_an_unusable_name_is_refused(self, name):
        with pytest.raises(UnknownTimezoneError):
            resolve_timezone(name)

    @pytest.mark.parametrize("name", ["Mars/Olympus_Mons", "../../etc/passwd", "SECRET-TOKEN"])
    def test_the_refusal_never_echoes_the_name(self, name):
        with pytest.raises(UnknownTimezoneError) as excinfo:
            resolve_timezone(name)

        assert str(excinfo.value.message) == "Unknown timezone"
        assert name not in str(excinfo.value)
        # Nor through an exception chain: ZoneInfo's own errors quote the key.
        assert excinfo.value.__cause__ is None


class TestGroupByInputsBecomeDimensions:
    def test_a_scalar_entry_becomes_an_untruncated_dimension(self):
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID)],
            "America/Sao_Paulo",
        )

        assert len(dimensions) == 1
        assert dimensions[0].alias == "calendar_id"
        assert dimensions[0].field_path == "calendar_id"
        assert dimensions[0].granularity is None
        assert dimensions[0].tzinfo is None

    @pytest.mark.parametrize(
        ("granularity", "expected_alias"),
        [
            (TemporalGranularity.DAY, "start_time_day"),
            (TemporalGranularity.WEEK, "start_time_week"),
            (TemporalGranularity.MONTH, "start_time_month"),
        ],
    )
    def test_a_temporal_entry_carries_its_bucket_size_and_the_callers_zone(
        self, granularity, expected_alias
    ):
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.START_TIME,
                        granularity=granularity,
                    )
                )
            ],
            "America/Sao_Paulo",
        )

        assert dimensions[0].alias == expected_alias
        assert dimensions[0].field_path == "start_time"
        assert dimensions[0].granularity is granularity
        assert dimensions[0].tzinfo == SAO_PAULO

    def test_several_entries_keep_the_order_the_caller_gave(self):
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.START_TIME,
                        granularity=TemporalGranularity.DAY,
                    )
                ),
                CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID),
            ],
            "UTC",
        )

        assert [dimension.alias for dimension in dimensions] == [
            "start_time_day",
            "calendar_id",
        ]

    def test_every_entity_can_build_a_dimension(self):
        cases = [
            (
                AggregatableEntity.APPOINTMENT_TYPE,
                AppointmentTypeGroupByInput(
                    scalar=AppointmentTypeScalarGroupByField.ACCEPTS_PUBLIC_SCHEDULING
                ),
                "accepts_public_scheduling",
            ),
            (
                AggregatableEntity.CALENDAR,
                CalendarGroupByInput(scalar=CalendarScalarGroupByField.CALENDAR_TYPE),
                "calendar_type",
            ),
            (
                AggregatableEntity.CALENDAR_POOL,
                CalendarPoolGroupByInput(
                    temporal=CalendarPoolTemporalGroupBy(
                        field=CalendarPoolTemporalGroupByField.CREATED,
                        granularity=TemporalGranularity.MONTH,
                    )
                ),
                "created_month",
            ),
        ]

        for entity, entry, expected_alias in cases:
            dimensions = dimensions_from_group_by(entity, [entry], "UTC")
            assert dimensions[0].alias == expected_alias


class TestGroupByEntriesMustNameExactlyOneVariant:
    def test_an_entry_naming_neither_variant_is_refused(self):
        with pytest.raises(AmbiguousGroupByError):
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT, [CalendarEventGroupByInput()], "UTC"
            )

    def test_an_entry_naming_both_variants_is_refused(self):
        with pytest.raises(AmbiguousGroupByError):
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT,
                [
                    CalendarEventGroupByInput(
                        scalar=CalendarEventScalarGroupByField.CALENDAR_ID,
                        temporal=CalendarEventTemporalGroupBy(
                            field=CalendarEventTemporalGroupByField.START_TIME,
                            granularity=TemporalGranularity.DAY,
                        ),
                    )
                ],
                "UTC",
            )

    def test_the_refusal_does_not_echo_caller_input(self):
        with pytest.raises(AmbiguousGroupByError) as excinfo:
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT, [CalendarEventGroupByInput()], "UTC"
            )

        assert "scalar" in str(excinfo.value)
        assert "temporal" in str(excinfo.value)


class TestOneEntryPerGroupKeyField:
    def test_the_same_field_at_two_granularities_is_refused(self):
        # The key type carries one ``startTime`` field, so the second bucket
        # would overwrite the first on the way out. A month is derivable from a
        # day anyway, so nothing is lost by refusing.
        with pytest.raises(DuplicateGroupKeyFieldError) as excinfo:
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT,
                [
                    CalendarEventGroupByInput(
                        temporal=CalendarEventTemporalGroupBy(
                            field=CalendarEventTemporalGroupByField.START_TIME,
                            granularity=TemporalGranularity.DAY,
                        )
                    ),
                    CalendarEventGroupByInput(
                        temporal=CalendarEventTemporalGroupBy(
                            field=CalendarEventTemporalGroupByField.START_TIME,
                            granularity=TemporalGranularity.MONTH,
                        )
                    ),
                ],
                "UTC",
            )

        assert "start_time" in str(excinfo.value)

    def test_the_same_scalar_field_twice_is_refused(self):
        with pytest.raises(DuplicateGroupKeyFieldError):
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT,
                [
                    CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID),
                    CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID),
                ],
                "UTC",
            )

    def test_two_different_temporal_fields_are_fine(self):
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.START_TIME,
                        granularity=TemporalGranularity.DAY,
                    )
                ),
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.END_TIME,
                        granularity=TemporalGranularity.DAY,
                    )
                ),
            ],
            "UTC",
        )

        assert [dimension.alias for dimension in dimensions] == [
            "start_time_day",
            "end_time_day",
        ]


class TestTheTimezoneIsValidatedEvenWhenNothingIsBucketed:
    def test_a_scalar_only_grouping_still_refuses_an_unknown_zone(self):
        # ``timezone`` is a non-null field argument. Accepting a name in one
        # query that another query would refuse is an inconsistency partners
        # write bug reports about.
        with pytest.raises(UnknownTimezoneError):
            dimensions_from_group_by(
                AggregatableEntity.CALENDAR_EVENT,
                [CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID)],
                "Mars/Olympus_Mons",
            )


class TestGroupKeysCarryOnlyWhatWasAsked:
    def test_only_the_named_dimensions_are_populated(self):
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [
                CalendarEventGroupByInput(scalar=CalendarEventScalarGroupByField.CALENDAR_ID),
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.START_TIME,
                        granularity=TemporalGranularity.DAY,
                    )
                ),
            ],
            "America/Sao_Paulo",
        )
        row = {"calendar_id": 7, "start_time_day": "2026-03-05T00:00:00-03:00", "count": 3}

        key = build_group_key(AggregatableEntity.CALENDAR_EVENT, dimensions, row)

        assert isinstance(key, CalendarEventGroupKey)
        assert key.calendar_id == 7
        assert key.start_time == "2026-03-05T00:00:00-03:00"
        # Every dimension the query did not name stays null.
        assert key.appointment_type_id is None
        assert key.bundle_calendar_id is None
        assert key.is_bundle_primary is None
        assert key.timezone is None
        assert key.end_time is None
        assert key.created is None

    def test_a_bucketed_dimension_lands_on_its_unbucketed_key_field(self):
        # The row key is ``start_time_month``; the key field is ``startTime``.
        dimensions = dimensions_from_group_by(
            AggregatableEntity.CALENDAR_EVENT,
            [
                CalendarEventGroupByInput(
                    temporal=CalendarEventTemporalGroupBy(
                        field=CalendarEventTemporalGroupByField.START_TIME,
                        granularity=TemporalGranularity.MONTH,
                    )
                )
            ],
            "UTC",
        )

        key = build_group_key(
            AggregatableEntity.CALENDAR_EVENT, dimensions, {"start_time_month": "2026-03"}
        )

        assert key.start_time == "2026-03"

    def test_a_group_key_with_no_dimensions_is_entirely_null(self):
        key = build_group_key(AggregatableEntity.CALENDAR_EVENT, (), {"count": 1})

        assert all(
            getattr(key, field.name) is None for field in dataclasses.fields(CalendarEventGroupKey)
        )
