# Generated by Django 6.0.5 on 2026-07-19 04:51

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_organization_owned_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                (
                    "provider",
                    models.CharField(choices=[("mercadopago", "MercadoPago")], max_length=50),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("payment_update", "Payment update"),
                            ("subscription_payment_update", "Subscription payment update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("external_event_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "route", "external_event_id"),
                        name="uniq_provider_webhook_event",
                    )
                ],
            },
        ),
    ]
