# Generated by Django 6.0.5 on 2026-07-19 18:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_providerwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('entitlement_key', models.CharField(choices=[('external_calendar_google', 'Google Calendar sync'), ('external_calendar_microsoft', 'Microsoft Calendar sync'), ('partner_api', 'Partner / public API access'), ('white_label_branding', 'White-label branding'), ('advanced_scheduling', 'Advanced scheduling')], max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='payments.billingplan')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('plan', 'entitlement_key'), name='uniq_plan_entitlement_key')],
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('resource_key', models.CharField(choices=[('organization_members', 'Organization members'), ('resource_calendars', 'Resource calendars'), ('calendar_groups', 'Calendar groups'), ('bundle_calendars', 'Bundle calendars'), ('availability_windows', 'Availability windows'), ('webhook_subscriptions', 'Webhook subscriptions'), ('public_api_system_users', 'Public API system users'), ('event_occurrences', 'Event occurrences')], max_length=100)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=20)),
                ('overage_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='payments.billingplan')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('plan', 'resource_key'), name='uniq_plan_limit_resource')],
            },
        ),
    ]
