# Generated by Django 6.0.5 on 2026-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_providerwebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_provider",
            field=models.CharField(
                choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="providerwebhookevent",
            name="provider",
            field=models.CharField(
                choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment_provider",
            field=models.CharField(
                choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")], max_length=50
            ),
        ),
    ]
