# Generated by Django 6.0.5 on 2026-07-20 00:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_backfill_unlimited_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('resource_key', models.CharField(choices=[('organization_members', 'Organization members'), ('resource_calendars', 'Resource calendars'), ('calendar_groups', 'Calendar groups'), ('bundle_calendars', 'Bundle calendars'), ('availability_windows', 'Availability windows'), ('webhook_subscriptions', 'Webhook subscriptions'), ('public_api_system_users', 'Public API system users'), ('event_occurrences', 'Event occurrences')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('is_recurring', models.BooleanField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('purchase_idempotency_key', models.CharField(max_length=255, unique=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='payments.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
