# Generated by Django 6.0.5 on 2026-07-20 12:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationmembership_is_billing_owner'),
        ('payments', '0010_subscriptionaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteredOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('event_id', models.BigIntegerField()),
                ('occurrence_start', models.DateTimeField()),
                ('billing_period_start', models.DateTimeField(db_index=True)),
                ('is_within_allowance', models.BooleanField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metered_occurrences', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metered_occurrences', to='payments.subscription')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['subscription', 'billing_period_start'], name='metered_occ_sub_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'event_id', 'occurrence_start'), name='uniq_metered_occurrence')],
            },
        ),
    ]
