# Generated by Django 6.0.5 on 2026-07-20 21:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationmembership_is_billing_owner'),
        ('payments', '0011_meteredoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_billing_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.billingplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionaddon',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_on', to='payments.payment'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('provider', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('stripe', 'Stripe')], max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'external_id'), name='uniq_payment_method')],
            },
        ),
    ]
