# Generated by Django 6.0.5 on 2026-07-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_subscription_pending_billing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_change_pending_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
