# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_subscription_plan_change_pending_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_dunning_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
