# Generated by Django 6.0.5 on 2026-07-21 05:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_subscription_last_dunning_attempt_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitWarningNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('resource_key', models.CharField(choices=[('organization_members', 'Organization members'), ('resource_calendars', 'Resource calendars'), ('calendar_groups', 'Calendar groups'), ('bundle_calendars', 'Bundle calendars'), ('availability_windows', 'Availability windows'), ('webhook_subscriptions', 'Webhook subscriptions'), ('public_api_system_users', 'Public API system users'), ('event_occurrences', 'Event occurrences')], max_length=100)),
                ('billing_period_start', models.DateTimeField(db_index=True)),
                ('level', models.CharField(choices=[('approaching', 'Approaching the limit'), ('reached', 'At or over the limit')], max_length=20)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_warnings', to='payments.subscription')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('subscription', 'resource_key', 'billing_period_start', 'level'), name='uniq_limit_warning_notification')],
            },
        ),
    ]
