# Generated by Django 6.0.5 on 2026-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_limitwarningnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('mercadopago', 'MercadoPago'), ('stripe', 'Stripe')], default='', max_length=50),
        ),
    ]
