# Generated by Django 6.0.5 on 2026-08-08 19:49

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organization_week_start'),
        ('payments', '0019_backfill_subscription_payment_provider_on_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('billing_period_start', models.DateTimeField(db_index=True)),
                ('billing_period_end', models.DateTimeField()),
                ('plan_slug', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=255)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('overage_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('charged', models.BooleanField()),
                ('reconciliation_unmetered', models.PositiveIntegerField()),
                ('reconciliation_orphaned', models.PositiveIntegerField()),
                ('closed_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_period_summaries', to='organizations.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_summaries', to='payments.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_summaries', to='payments.subscription')),
            ],
            options={
                'ordering': ('-billing_period_start',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingPeriodResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('resource_key', models.CharField(choices=[('organization_members', 'Organization members'), ('resource_calendars', 'Resource calendars'), ('calendar_groups', 'Calendar groups'), ('bundle_calendars', 'Bundle calendars'), ('availability_windows', 'Availability windows'), ('webhook_subscriptions', 'Webhook subscriptions'), ('public_api_system_users', 'Public API system users'), ('event_occurrences', 'Event occurrences')], max_length=100)),
                ('kind', models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=20, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('overage_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('by_organization', models.JSONField(default=dict)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='payments.billingperiodsummary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='billingperiodsummary',
            index=models.Index(fields=['organization', '-billing_period_start'], name='billing_period_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingperiodsummary',
            constraint=models.UniqueConstraint(fields=('subscription', 'billing_period_start'), name='uniq_billing_period_summary'),
        ),
        migrations.AddConstraint(
            model_name='billingperiodresourceusage',
            constraint=models.UniqueConstraint(fields=('summary', 'resource_key'), name='uniq_billing_period_resource_usage'),
        ),
    ]
