# Generated by Django 6.0.5 on 2026-08-10 15:31

from django.db import migrations, models

from payments.billing_constants import DocumentTypes


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_billing_period_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='document_type',
            # `DocumentTypes.choices` is referenced, not frozen into literals, so
            # adding or renaming a member does not generate a follow-up migration.
            # Safe precisely because `choices` is validation metadata Django never
            # emits DDL for -- the historical state tracking the live enum changes
            # nothing about the column. Do not "restore" the generated literals.
            field=models.CharField(choices=DocumentTypes.choices, max_length=50),
        ),
    ]
