# Generated by Django 6.0.5 on 2026-08-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_billingprofile_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('manage_billing', "Can manage the organization's billing")]},
        ),
    ]
