"""Move every billing row from ``payments_*`` to ``vinta_billing_*``, move the
``manage_billing`` grant with it, and drop this app's twenty models.

**Copy forward, then drop -- not ``AlterModelTable``.** A rename would have to be
ordered either before ``vinta_billing.0001_initial`` (which then needs
``migrate --fake-initial`` at deploy time, and ``pytest-django`` builds the test
database with a plain ``migrate``) or after it (which means dropping the tables
that migration just created and inheriting ``payments_``-prefixed index and
constraint names that later package migrations would fail to find). The copy
runs unattended in every environment and leaves the package's own names in
place. Its cost is a table copy, acceptable at this project's volume and worth
revisiting at a much larger one. See the implementation plan's *Risk & Rollout
Notes*.

**Explicit column lists, never ``SELECT *``.** The two tables carry identical
column *sets* but not identical column *orders* -- ``billingprofile`` alone has
``billing_address_id`` and ``payment_provider`` transposed between them, and
``subscription`` differs in five positions -- so ``INSERT ... SELECT *`` would
write plausible-looking values into the wrong columns. ``_assert_columns_match``
additionally re-derives both tables' real column sets from
``information_schema`` and refuses to copy if either disagrees with the list
below, so a future package release that adds a column fails loudly here instead
of silently dropping it.

**Sequences.** Every table except ``billingprofile`` (whose primary key is its
``organization_id``) has a ``bigint GENERATED BY DEFAULT AS IDENTITY`` ``id``.
Copying rows with their primary keys does not move the identity sequence, so the
very next insert would collide on a key that already exists -- a failure that
surfaces long after this migration reports success. Each copy is therefore
followed by a ``setval`` on the *destination* table's own sequence, looked up
with ``pg_get_serial_sequence`` rather than spelled as a literal.

**Reverse.** ``migrate payments 0022`` is this plan's rollback lever, and it is a
real one. Django unapplies, in order: this migration (the deletions reverse into
``CREATE TABLE``s Django derives from the migration state, then the rows are
copied back and ``vinta_billing_*`` is emptied), then ``vinta_billing.0002`` and
``0001`` -- forced by ``0023``'s ``run_before`` edge, and necessary, because
``0023``'s own reverse re-adds the thirteen constraint and index names the
package's tables would otherwise still be holding -- then ``0023`` itself. What
comes back is the schema and the data as ``payments.0022`` left them.

One asymmetry worth stating: ``vinta_billing.manage_billing`` is deleted on the
way back, but Django's ``post_migrate`` ``create_permissions`` recreates it,
unassigned, at the end of the same command. That is the correct end state -- the
permission belongs to a model that still exists, and what the rollback actually
has to undo is the *grant*, which is revoked here and stays revoked.
"""

from django.db import migrations


#: ``table_suffix -> columns``, in the order every foreign-key target precedes
#: its referents. ``MeteredOccurrence.event_id`` is a soft reference to
#: ``calendar_integration`` rather than a foreign key, so nothing outside these
#: twenty tables takes part in the ordering.
TABLES: list[tuple[str, tuple[str, ...]]] = [
    # 1. no billing foreign keys at all
    (
        "billingaddress",
        (
            "id",
            "created",
            "modified",
            "meta",
            "street_name",
            "street_number",
            "neighborhood",
            "address_line_2",
            "city",
            "state",
            "country",
            "zip_code",
        ),
    ),
    (
        "billingplan",
        (
            "id",
            "created",
            "modified",
            "meta",
            "slug",
            "name",
            "is_active",
            "is_default_for_new_organizations",
            "monthly_price",
            "annual_price",
            "currency",
            "grace_period_days",
        ),
    ),
    # 2. -> billingplan
    (
        "planlimit",
        (
            "id",
            "created",
            "modified",
            "meta",
            "resource_key",
            "limit_value",
            "kind",
            "overage_unit_price",
            "plan_id",
        ),
    ),
    (
        "planentitlement",
        (
            "id",
            "created",
            "modified",
            "meta",
            "entitlement_key",
            "is_enabled",
            "plan_id",
        ),
    ),
    # 3. -> billingaddress. Primary key is ``organization_id``: no identity column.
    (
        "billingprofile",
        (
            "created",
            "modified",
            "meta",
            "organization_id",
            "contact_first_name",
            "contact_last_name",
            "contact_email",
            "contact_phone",
            "document_type",
            "document_number",
            "payment_provider",
            "billing_address_id",
        ),
    ),
    # 4. -> billingplan (twice: ``plan`` and ``pending_plan``), organization
    (
        "subscription",
        (
            "id",
            "created",
            "modified",
            "meta",
            "status",
            "billing_state",
            "billing_interval",
            "current_period_start",
            "current_period_end",
            "grace_period_ends_at",
            "last_dunning_attempt_at",
            "external_id",
            "plan_external_id",
            "payment_provider",
            "pending_billing_interval",
            "pending_plan_effective_at",
            "plan_change_pending_confirmation",
            "organization_id",
            "pending_plan_id",
            "plan_id",
        ),
    ),
    # 5. -> subscription / organization
    (
        "paymentmethod",
        (
            "id",
            "created",
            "modified",
            "meta",
            "provider",
            "external_id",
            "is_active",
            "organization_id",
        ),
    ),
    (
        "subscriptionplanlimit",
        (
            "id",
            "created",
            "modified",
            "meta",
            "resource_key",
            "limit_value",
            "kind",
            "overage_unit_price",
            "is_overridden",
            "subscription_id",
        ),
    ),
    (
        "subscriptionentitlement",
        (
            "id",
            "created",
            "modified",
            "meta",
            "entitlement_key",
            "is_enabled",
            "is_overridden",
            "subscription_id",
        ),
    ),
    # 6. -> billingprofile, subscription
    (
        "payment",
        (
            "id",
            "created",
            "modified",
            "meta",
            "value",
            "currency",
            "payment_provider",
            "external_id",
            "status",
            "original_status",
            "payment_method",
            "description",
            "billing_profile_id",
            "subscription_id",
        ),
    ),
    # 7. -> subscription + payment / payment
    (
        "subscriptionaddon",
        (
            "id",
            "created",
            "modified",
            "meta",
            "resource_key",
            "quantity",
            "is_recurring",
            "is_active",
            "external_id",
            "purchase_idempotency_key",
            "payment_id",
            "subscription_id",
        ),
    ),
    (
        "refund",
        (
            "id",
            "created",
            "modified",
            "meta",
            "value",
            "currency",
            "external_id",
            "status",
            "payment_id",
        ),
    ),
    # 8. status ledgers -> payment / subscription / refund
    (
        "paymentstatusupdate",
        (
            "id",
            "created",
            "modified",
            "meta",
            "status",
            "description",
            "external_id",
            "payment_id",
        ),
    ),
    (
        "subscriptionstatusupdate",
        (
            "id",
            "created",
            "modified",
            "meta",
            "status",
            "description",
            "external_id",
            "subscription_id",
        ),
    ),
    (
        "refundstatusupdate",
        (
            "id",
            "created",
            "modified",
            "meta",
            "status",
            "description",
            "external_id",
            "refund_id",
        ),
    ),
    # 9. -> subscription / organization / nothing
    (
        "providerwebhookevent",
        (
            "id",
            "created",
            "modified",
            "meta",
            "provider",
            "route",
            "external_event_id",
            "payload",
            "processed_at",
        ),
    ),
    (
        "meteredoccurrence",
        (
            "id",
            "created",
            "modified",
            "meta",
            "event_id",
            "occurrence_start",
            "billing_period_start",
            "is_within_allowance",
            "unit_price",
            "organization_id",
            "subscription_id",
        ),
    ),
    (
        "limitwarningnotification",
        (
            "id",
            "created",
            "modified",
            "meta",
            "resource_key",
            "billing_period_start",
            "level",
            "subscription_id",
        ),
    ),
    # 10. -> subscription, payment, organization; then its own children
    (
        "billingperiodsummary",
        (
            "id",
            "created",
            "modified",
            "meta",
            "billing_period_start",
            "billing_period_end",
            "plan_slug",
            "plan_name",
            "billing_interval",
            "currency",
            "overage_total",
            "charged",
            "reconciliation_unmetered",
            "reconciliation_orphaned",
            "closed_at",
            "organization_id",
            "payment_id",
            "subscription_id",
        ),
    ),
    (
        "billingperiodresourceusage",
        (
            "id",
            "created",
            "modified",
            "meta",
            "resource_key",
            "kind",
            "total",
            "limit_value",
            "overage_unit_price",
            "by_organization",
            "summary_id",
        ),
    ),
]

OLD_PREFIX = "payments_"
NEW_PREFIX = "vinta_billing_"

GROUPS_HOLDING_MANAGE_BILLING = ("organization_admin", "organization_billing_owner")
MANAGE_BILLING_CODENAME = "manage_billing"
MANAGE_BILLING_NAME = "Can manage the organization's billing"


def _assert_columns_match(cursor, table: str, columns: tuple[str, ...]) -> None:
    """Refuse to copy a table whose real columns are not the ones declared here.

    A column present in both tables but missing from ``TABLES`` would be dropped
    silently -- the ``INSERT`` would succeed and the values would simply not
    arrive. That is the one failure mode an explicit column list does not catch
    on its own, so it is caught here instead.
    """
    cursor.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = %s",
        [table],
    )
    actual = {row[0] for row in cursor.fetchall()}
    if actual != set(columns):
        raise RuntimeError(
            f"{table} does not have the columns this migration was written against. "
            f"Missing from the table: {sorted(set(columns) - actual)}. "
            f"Present but not copied: {sorted(actual - set(columns))}."
        )


def _copy(cursor, source: str, destination: str, columns: tuple[str, ...]) -> None:
    _assert_columns_match(cursor, source, columns)
    _assert_columns_match(cursor, destination, columns)
    column_list = ", ".join(f'"{column}"' for column in columns)
    cursor.execute(
        f'INSERT INTO "{destination}" ({column_list}) SELECT {column_list} FROM "{source}"'  # noqa: S608
    )


def _advance_sequence(cursor, table: str, columns: tuple[str, ...]) -> None:
    """Point ``table``'s identity sequence past the highest primary key copied in.

    ``is_called=False`` with ``max(id) + 1`` rather than ``is_called=True`` with
    ``max(id)`` so an empty table lands on 1 -- ``setval`` rejects 0, which is
    below the sequence's minimum.
    """
    if "id" not in columns:
        # ``billingprofile``: its primary key is ``organization_id``, supplied by
        # the caller, so there is no sequence to advance.
        return
    cursor.execute(
        f'SELECT setval(pg_get_serial_sequence(%s, \'id\'), '  # noqa: S608
        f'COALESCE((SELECT MAX("id") FROM "{table}"), 0) + 1, false)',
        [table],
    )


def copy_rows_into_vinta_billing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for table, columns in TABLES:
            _copy(cursor, f"{OLD_PREFIX}{table}", f"{NEW_PREFIX}{table}", columns)
            _advance_sequence(cursor, f"{NEW_PREFIX}{table}", columns)


def copy_rows_back_into_payments(apps, schema_editor):
    """Put the rows back where ``0022`` left them, and leave ``vinta_billing_*``
    as ``vinta_billing.0002`` left it: created and empty.

    Emptying the destination is what makes this a true inverse rather than a
    one-way copy: without it, re-applying this migration would collide on every
    primary key it had already moved once.
    """
    with schema_editor.connection.cursor() as cursor:
        for table, columns in TABLES:
            _copy(cursor, f"{NEW_PREFIX}{table}", f"{OLD_PREFIX}{table}", columns)
            _advance_sequence(cursor, f"{OLD_PREFIX}{table}", columns)
        # Children before parents, so no foreign key is ever left dangling.
        for table, columns in reversed(TABLES):
            cursor.execute(f'DELETE FROM "{NEW_PREFIX}{table}"')  # noqa: S608
            _advance_sequence(cursor, f"{NEW_PREFIX}{table}", columns)


def _content_type_and_permission(apps, db_alias, app_label: str):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label=app_label, model="subscription"
    )
    permission, _ = Permission.objects.using(db_alias).get_or_create(
        content_type=content_type,
        codename=MANAGE_BILLING_CODENAME,
        defaults={"name": MANAGE_BILLING_NAME},
    )
    return content_type, permission


def _move_manage_billing(apps, schema_editor, *, to_app_label: str, from_app_label: str):
    """Re-grant ``manage_billing`` on ``to_app_label``'s subscription content type,
    then revoke and delete the one on ``from_app_label``'s.

    The permission row is created here rather than left to ``post_migrate``:
    ``create_permissions`` runs at the *end* of the ``migrate`` command, long
    after this, so on a fresh database ``vinta_billing.manage_billing`` does not
    exist yet at this point. ``get_or_create`` covers the already-migrated case.

    Deleting the ``Permission`` row is what revokes it -- the ``Group`` /
    ``Permission`` many-to-many rows go with it -- so the grant cannot survive
    on a content type that no longer describes anything.
    """
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias

    _, permission = _content_type_and_permission(apps, db_alias, to_app_label)
    for group_name in GROUPS_HOLDING_MANAGE_BILLING:
        group = Group.objects.using(db_alias).filter(name=group_name).first()
        if group is not None:
            # ``add``, not ``set``: additive and idempotent, and it leaves any
            # grant an operator made deliberately alone. Same convention as
            # ``organizations.0028``, which is where these groups come from.
            group.permissions.add(permission)

    stale = (
        ContentType.objects.using(db_alias)
        .filter(app_label=from_app_label, model="subscription")
        .first()
    )
    if stale is not None:
        Permission.objects.using(db_alias).filter(content_type=stale).delete()
        stale.delete()


def grant_on_vinta_billing(apps, schema_editor):
    _move_manage_billing(
        apps, schema_editor, to_app_label="vinta_billing", from_app_label="payments"
    )


def grant_on_payments(apps, schema_editor):
    _move_manage_billing(
        apps, schema_editor, to_app_label="payments", from_app_label="vinta_billing"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0023_free_colliding_constraint_names"),
        # The destination tables, and the ``Meta.permissions`` declaration
        # ``manage_billing`` moves onto.
        ("vinta_billing", "0002_manage_billing_permission"),
        # The three groups and the ``payments.manage_billing`` row this migration
        # re-points. ``0028`` itself is frozen and keeps naming ``payments``: it
        # describes the world as it was, and this migration depends on it.
        ("organizations", "0028_seed_permission_groups"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(copy_rows_into_vinta_billing, copy_rows_back_into_payments),
        migrations.RunPython(grant_on_vinta_billing, grant_on_payments),
        # Everything below is ``makemigrations``'s own output, unedited: the
        # foreign keys have to come off before the tables they point at can go,
        # which is why the ``RemoveField``s precede the ``DeleteModel``s. Both
        # halves reverse into DDL Django derives from the migration state, which
        # is what makes the rollback path above real rather than nominal.
        migrations.RemoveField(
            model_name="billingprofile",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="billingperiodresourceusage",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="billingperiodsummary",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="billingperiodsummary",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="billingperiodsummary",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="planentitlement",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="pending_plan",
        ),
        migrations.RemoveField(
            model_name="planlimit",
            name="plan",
        ),
        # ``makemigrations`` also emitted a `RemoveField(billingprofile,
        # organization)` here. It is deliberately gone: ``BillingProfile``'s
        # primary key *is* that column, and splitting it out breaks in both
        # directions. Forward, dropping it before
        # ``payments_payment.billing_profile_id`` stops referencing it fails
        # ("cannot drop column organization_id ... other objects depend on it").
        # Backward, ``DeleteModel``'s reverse would rebuild the table from a
        # state that no longer has the field, so Django would give it a synthetic
        # ``id`` primary key and re-adding ``organization`` would fail with
        # "multiple primary keys for table are not allowed". Letting
        # ``DeleteModel(BillingProfile)`` carry the field does both correctly:
        # forward it is a ``DROP TABLE``, backward a ``CREATE TABLE`` with the
        # right primary key. The end state is identical either way, so
        # ``makemigrations --check`` stays clean; the ordering below (the
        # referencing FK first) is what the autodetector's split was for.
        migrations.RemoveField(
            model_name="payment",
            name="billing_profile",
        ),
        migrations.RemoveField(
            model_name="limitwarningnotification",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="meteredoccurrence",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="meteredoccurrence",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentstatusupdate",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="subscriptionaddon",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="organization",
        ),
        migrations.DeleteModel(
            name="ProviderWebhookEvent",
        ),
        migrations.RemoveField(
            model_name="refundstatusupdate",
            name="refund",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="subscriptionplanlimit",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionstatusupdate",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionentitlement",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionaddon",
            name="subscription",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
        migrations.DeleteModel(
            name="BillingPeriodResourceUsage",
        ),
        migrations.DeleteModel(
            name="BillingPeriodSummary",
        ),
        migrations.DeleteModel(
            name="PlanEntitlement",
        ),
        migrations.DeleteModel(
            name="BillingPlan",
        ),
        migrations.DeleteModel(
            name="PlanLimit",
        ),
        migrations.DeleteModel(
            name="BillingProfile",
        ),
        migrations.DeleteModel(
            name="LimitWarningNotification",
        ),
        migrations.DeleteModel(
            name="MeteredOccurrence",
        ),
        migrations.DeleteModel(
            name="PaymentStatusUpdate",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="Refund",
        ),
        migrations.DeleteModel(
            name="RefundStatusUpdate",
        ),
        migrations.DeleteModel(
            name="SubscriptionPlanLimit",
        ),
        migrations.DeleteModel(
            name="SubscriptionStatusUpdate",
        ),
        migrations.DeleteModel(
            name="SubscriptionEntitlement",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionAddOn",
        ),
    ]
