# Generated by Django 6.0.5 on 2026-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pending_organization_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Intended organization name captured at email/password signup. Consumed and cleared when the org is created on email confirmation. Blank for invited signups (they auto-join, no org name needed).",
                max_length=255,
            ),
        ),
    ]
