# Generated by Django 5.2.2 on 2025-07-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_date',
        ),
    ]
