# Generated by Django 5.2.2 on 2025-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_verified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
