# Generated by Django 5.2.2 on 2025-09-01 16:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('event_type', models.CharField(choices=[('calendar_event_created', 'Calendar Event Created'), ('calendar_event_updated', 'Calendar Event Updated'), ('calendar_event_deleted', 'Calendar Event Deleted'), ('calendar_event_attendee_added', 'Calendar Event Attendee Added'), ('calendar_event_attendee_removed', 'Calendar Event Attendee Removed'), ('calendar_event_attendee_updated', 'Calendar Event Attendee Updated')], default='calendar_event_created', max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('headers', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('event_type', models.CharField(choices=[('calendar_event_created', 'Calendar Event Created'), ('calendar_event_updated', 'Calendar Event Updated'), ('calendar_event_deleted', 'Calendar Event Deleted'), ('calendar_event_attendee_added', 'Calendar Event Attendee Added'), ('calendar_event_attendee_removed', 'Calendar Event Attendee Removed'), ('calendar_event_attendee_updated', 'Calendar Event Attendee Updated')], max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField()),
                ('response_status', models.PositiveBigIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('retry_number', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignObject(editable=False, from_fields=['configuration_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='configuration_set', to='webhooks.webhookconfiguration', to_fields=['id', 'organization_id'])),
                ('configuration_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_fk_rel', to='webhooks.webhookconfiguration')),
                ('main_event', models.ForeignObject(editable=False, from_fields=['main_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_event_set', to='webhooks.webhookevent', to_fields=['id', 'organization_id'])),
                ('main_event_fk', models.ForeignKey(blank=True, help_text='Reference to the main event in case of retries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_event_fk_rel', to='webhooks.webhookevent')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
