# Generated by Django 6.0.5 on 2026-06-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='event_type',
            field=models.CharField(choices=[('calendar_event_created', 'Calendar Event Created'), ('calendar_event_updated', 'Calendar Event Updated'), ('calendar_event_deleted', 'Calendar Event Deleted'), ('calendar_event_attendee_added', 'Calendar Event Attendee Added'), ('calendar_event_attendee_removed', 'Calendar Event Attendee Removed'), ('calendar_event_attendee_updated', 'Calendar Event Attendee Updated'), ('organization_member_created', 'Organization member created')], default='calendar_event_created', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(choices=[('calendar_event_created', 'Calendar Event Created'), ('calendar_event_updated', 'Calendar Event Updated'), ('calendar_event_deleted', 'Calendar Event Deleted'), ('calendar_event_attendee_added', 'Calendar Event Attendee Added'), ('calendar_event_attendee_removed', 'Calendar Event Attendee Removed'), ('calendar_event_attendee_updated', 'Calendar Event Attendee Updated'), ('organization_member_created', 'Organization member created')], max_length=255),
        ),
    ]
