"""Move ``webhooks`` onto vinta-django-orgs' scoped mixin and safe relations.

Generated by ``makemigrations`` and then read operation by operation against
``sqlmigrate``. Same shape as ``audit/migrations/0002`` -- see that module's
docstring for the full rationale; what differs here:

* ``AlterModelOptions`` on both models, which declare no ``Meta`` of their own
  and so now inherit ``SingleOrganizationModelMixin.Meta``'s
  ``default_manager_name`` / ``base_manager_name``. State only.
* ``AlterField`` on ``webhookevent.configuration`` and ``webhookevent.main_event``
  -- the two organization-safe relations. Column layout unchanged;
  ``sqlmigrate`` reports ``(no-op)`` for both.

**No constraint is at risk.** Neither model declares any ``Meta.constraints`` or
``Meta.indexes`` at all, so the only indexes over ``organization_id`` alone are
the foreign keys' own, and ``sqlmigrate`` shows each dropped with a matching
``(organization, id)`` ``CREATE INDEX``.

**Lock audit**: as in ``audit/migrations/0002``.
"""

# ``to_fields=(None, 'organization')`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not. Same suppression, same
# reason, as ``calendar_integration/migrations/0045``.
# mypy: disable-error-code="arg-type"

# Generated by Django 6.0.5 on 2026-08-12 23:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhookconfiguration_event_type_and_more'),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookconfiguration',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='webhookconfiguration',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webhookevent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='configuration',
            field=models.ForeignObject(editable=False, from_fields=('configuration_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='configuration_set', to='webhooks.webhookconfiguration', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='main_event',
            field=models.ForeignObject(editable=False, from_fields=('main_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_event_set', to='webhooks.webhookevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddIndex(
            model_name='webhookconfiguration',
            index=models.Index(fields=['organization', 'id'], name='webhooks_we_organiz_08d0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['organization', 'id'], name='webhooks_we_organiz_659153_idx'),
        ),
    ]
