# Generated by Django 5.2.2 on 2025-09-04 04:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('integration_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('long_lived_token_hash', models.CharField(db_index=True, help_text="Hash of the the system user's access token.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the user is active.')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('resource_name', models.CharField(choices=[('calendar_event', 'Calendar Event'), ('calendar', 'Calendar'), ('recurrence_rule', 'Recurrence Rule'), ('external_attendee', 'External Attendee'), ('external_attendance', 'External Attendance'), ('attendance', 'Attendance'), ('user', 'User'), ('resource_allocation', 'Resource Allocation'), ('event_recurring_exception', 'Event Recurring Exception'), ('blocked_time', 'Blocked Time'), ('blocked_time_recurring_exception', 'Blocked Time Recurring Exception'), ('available_time', 'Available Time'), ('available_time_recurring_exception', 'Available Time Recurring Exception'), ('availability_windows', 'Availability Windows'), ('unavailable_windows', 'Unavailable Windows'), ('organization', 'Organization')], db_index=True, max_length=150)),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_resources', to='public_api.systemuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
