# Generated by Django 6.0.5 on 2026-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0002_alter_resourceaccess_resource_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resourceaccess",
            constraint=models.UniqueConstraint(
                fields=("system_user", "resource_name"),
                name="uniq_resourceaccess_systemuser_resource",
            ),
        ),
    ]
