# Generated by Django 6.0.5 on 2026-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0003_resourceaccess_uniq_resourceaccess_systemuser_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
