# Generated by Django 6.0.5 on 2026-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0004_add_systemuser_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource_name',
            field=models.CharField(choices=[('calendar_event', 'Calendar Event'), ('calendar', 'Calendar'), ('recurrence_rule', 'Recurrence Rule'), ('external_attendee', 'External Attendee'), ('external_attendance', 'External Attendance'), ('attendance', 'Attendance'), ('user', 'User'), ('resource_allocation', 'Resource Allocation'), ('event_recurring_exception', 'Event Recurring Exception'), ('blocked_time', 'Blocked Time'), ('blocked_time_recurring_exception', 'Blocked Time Recurring Exception'), ('available_time', 'Available Time'), ('available_time_recurring_exception', 'Available Time Recurring Exception'), ('availability_windows', 'Availability Windows'), ('unavailable_windows', 'Unavailable Windows'), ('organization', 'Organization'), ('calendar_group', 'Calendar Group'), ('system_user', 'System User')], db_index=True, max_length=150),
        ),
    ]
