# Generated by Django 6.0.5 on 2026-06-17 02:55

from django.db import migrations, models
from public_api.constants import PublicAPIResources

class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0005_alter_resourceaccess_resource_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceaccess",
            name="resource_name",
            field=models.CharField(
                choices=PublicAPIResources.choices,
                db_index=True,
                max_length=150,
            ),
        ),
    ]
