# Generated by Django 6.0.5 on 2026-06-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organizationbranding'),
        ('public_api', '0006_alter_resourceaccess_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='scoped_to_membership',
            field=models.ForeignObject(editable=False, from_fields=['scoped_to_membership_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_system_users', to='organizations.organizationmembership', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='scoped_to_membership_fk',
            field=models.ForeignKey(blank=True, help_text="When set, this token may only read/write data belonging to calendars owned by this organization membership's user. NULL = organization-wide token (legacy default).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_system_users_fk_rel', to='organizations.organizationmembership'),
        ),
    ]
