# Generated by Django 6.0.5 on 2026-06-18 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_api", "0006_alter_resourceaccess_resource_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="scoped_to_user",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="When set, this token may only read/write data belonging to calendars owned by this user. NULL = organization-wide token (legacy default).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoped_system_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
