"""Move ``public_api.SystemUser`` onto vinta-django-orgs' scoped mixin.

Generated by ``makemigrations`` and then read against ``sqlmigrate``. Same shape
as ``audit/migrations/0002`` -- see that module's docstring -- with one thing
worth stating outright:

``SystemUser.organization`` stays **nullable**. It is the one scoped model in
this project where ``organization=None`` is a value rather than a missing
argument (the org-less, admin-minted credential with access to every
organization). The field is redeclared on the model rather than inherited, so
this ``AlterField`` only turns ``db_index`` off to match
``SingleOrganizationModelMixin.organization``; ``null=True`` / ``blank=True`` /
``related_name='system_users'`` are unchanged, and no column is rewritten.
``SystemUser.save()`` carries the matching behavioural exception.

**No constraint is at risk**: the model declares no ``Meta``, so the only index
over ``organization_id`` alone is the foreign key's own, dropped in favour of the
``(organization, id)`` composite. ``sqlmigrate`` shows one ``DROP INDEX`` and one
``CREATE INDEX``.

**Lock audit**: as in ``audit/migrations/0002``.
"""

# Generated by Django 6.0.5 on 2026-08-12 23:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0008_remove_systemuser_scoped_to_membership_fk_and_more'),
        migrations.swappable_dependency(settings.ORGANIZATION_MEMBERSHIP_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='systemuser',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='organization',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemuser',
            index=models.Index(fields=['organization', 'id'], name='public_api__organiz_1a1075_idx'),
        ),
    ]
