# Generated by Django 6.0.5 on 2026-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0009_alter_resourceaccess_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource_name',
            field=models.CharField(choices=[('calendar_event', 'Calendar Event'), ('calendar', 'Calendar'), ('recurrence_rule', 'Recurrence Rule'), ('external_attendee', 'External Attendee'), ('external_attendance', 'External Attendance'), ('attendance', 'Attendance'), ('user', 'User'), ('resource_allocation', 'Resource Allocation'), ('event_recurring_exception', 'Event Recurring Exception'), ('blocked_time', 'Blocked Time'), ('blocked_time_recurring_exception', 'Blocked Time Recurring Exception'), ('available_time', 'Available Time'), ('available_time_recurring_exception', 'Available Time Recurring Exception'), ('availability_windows', 'Availability Windows'), ('unavailable_windows', 'Unavailable Windows'), ('organization', 'Organization'), ('calendar_group', 'Calendar Group'), ('system_user', 'System User'), ('membership', 'Membership'), ('invitation', 'Invitation'), ('branding', 'Branding'), ('child_org_analytics', 'Child Organization Analytics'), ('create_resource_calendar', 'Create Resource Calendar'), ('disable_resource_calendar', 'Disable Resource Calendar'), ('import_resource_calendars', 'Import Resource Calendars'), ('create_availability_window', 'Create Availability Window')], db_index=True, max_length=150),
        ),
    ]
