#!/usr/bin/env python
"""Spike: what the Google and Microsoft room directories do when we write to them.

Answers spec open questions 1, 2 and 8 of
`ai-plans/2026-10-04-RESOURCE_CALENDAR_PROVIDER_SYNC_SPEC.md` against **sandbox**
tenants. How to run it, and the table to record the answers in, are in
`docs/integrations/resource-directory-spike.md`.

Subcommands:

* `google-create-delete` -- Google Admin SDK Directory: insert a room with a
  client-chosen `resourceId`, replay the insert, read it back, patch capacity, delete
  it. Also checks whether `buildingId` is required for `CONFERENCE_ROOM` and whether a
  duplicate name is rejected.
* `ms-create-delete` -- Microsoft Graph Places: create a room under a floor, time the
  mailbox provisioning, check that a tag round-trips and can be searched, PATCH,
  DELETE, then check whether the room mailbox is still there.
* `ms-description` -- Microsoft Graph Places: list the room's property names and
  check which candidate property keeps a free-text value.

Safety contract:

* **Dry-run by default.** Without `--execute` the script makes no network call at
  all: tokens are fake and every request is logged and answered by a canned response.
* Credentials come only from environment variables (see `--help` of each subcommand).
* Logs and the final JSON summary hold only opaque ids, HTTP status codes, provider
  error codes, timings and property *names*. Room emails are hashed. Room names and
  descriptions are generated by the script and are never logged.
* Every room the script creates is deleted in a `finally` block, even when a step
  fails.

Standalone on purpose: no Django import, so it runs with `uv run python` and no `.env`.
"""

from __future__ import annotations

import argparse
import base64
import dataclasses
import hashlib
import json
import logging
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from collections.abc import Callable, Iterator, Sequence
from contextlib import contextmanager
from typing import Any, Protocol


logger = logging.getLogger("resource_directory_spike")

GOOGLE_DIRECTORY_BASE = "https://admin.googleapis.com/admin/directory/v1"
GOOGLE_WRITE_SCOPE = "https://www.googleapis.com/auth/admin.directory.resource.calendar"

GRAPH_V1_BASE = "https://graph.microsoft.com/v1.0"
# Creating and deleting places is only documented on the beta endpoint.
GRAPH_PLACES_DEFAULT_BASE = "https://graph.microsoft.com/beta"
MS_LOGIN_BASE = "https://login.microsoftonline.com"
MS_GRAPH_DEFAULT_SCOPE = "https://graph.microsoft.com/.default"

# Room properties that might hold a free-text description on Microsoft. `description`
# is not a documented room property; probing it records how Graph rejects one.
MS_DESCRIPTION_CANDIDATES = ("label", "nickname", "description")

ENV_GOOGLE_SA_JSON = "SPIKE_GOOGLE_SERVICE_ACCOUNT_JSON"
ENV_GOOGLE_ADMIN_EMAIL = "SPIKE_GOOGLE_ADMIN_EMAIL"
ENV_GOOGLE_CUSTOMER = "SPIKE_GOOGLE_CUSTOMER"
ENV_MS_TENANT_ID = "SPIKE_MS_TENANT_ID"
ENV_MS_CLIENT_ID = "SPIKE_MS_CLIENT_ID"
ENV_MS_CLIENT_SECRET = "SPIKE_MS_CLIENT_SECRET"  # noqa: S105 - an env var name
ENV_MS_FLOOR_ID = "SPIKE_MS_FLOOR_ID"

DRY_RUN_TOKEN = "dry-run-token"  # noqa: S105 - a placeholder, never sent anywhere

Findings = dict[str, Any]
# Label -> call that deletes what the label names. Insertion-ordered; run newest first.
Cleanups = dict[str, Callable[[], "HttpResponse"]]


class SpikeError(Exception):
    """The spike could not run (bad configuration or a failed prerequisite step)."""


@dataclasses.dataclass(frozen=True)
class HttpResponse:
    """The parts of a provider response the spike looks at."""

    status: int
    body: dict[str, Any]

    @property
    def ok(self) -> bool:
        """Whether the status is 2xx."""
        return 200 <= self.status < 300


class Transport(Protocol):
    """Sends one HTTP request. `operation` is a log label, never the URL."""

    def send(
        self,
        operation: str,
        method: str,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        json_body: dict[str, Any] | None = None,
        form_body: dict[str, str] | None = None,
    ) -> HttpResponse:
        """Send the request and return the response, including 4xx/5xx ones."""
        ...


class UrllibTransport:
    """Real HTTP, through the standard library so the spike adds no dependency."""

    def __init__(self, timeout_seconds: float = 30.0) -> None:
        self.timeout_seconds = timeout_seconds

    def send(
        self,
        operation: str,
        method: str,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        json_body: dict[str, Any] | None = None,
        form_body: dict[str, str] | None = None,
    ) -> HttpResponse:
        """Send the request. HTTP errors come back as a response, not an exception."""
        if not url.startswith("https://"):
            raise SpikeError(f"refusing non-HTTPS request for {operation}")
        request_headers = {"Accept": "application/json", **(headers or {})}
        data: bytes | None = None
        if json_body is not None:
            data = json.dumps(json_body).encode()
            request_headers["Content-Type"] = "application/json"
        elif form_body is not None:
            data = urllib.parse.urlencode(form_body).encode()
            request_headers["Content-Type"] = "application/x-www-form-urlencoded"
        request = urllib.request.Request(  # noqa: S310 - scheme checked above
            url, data=data, method=method, headers=request_headers
        )
        try:
            with urllib.request.urlopen(  # noqa: S310 - scheme checked above
                request, timeout=self.timeout_seconds
            ) as raw_response:
                status = raw_response.status
                raw = raw_response.read()
        except urllib.error.HTTPError as exc:
            status = exc.code
            raw = exc.read()
        response = HttpResponse(status=status, body=_parse_json_object(raw))
        logger.info("%s %s -> HTTP %s", method, operation, status)
        return response


class DryRunTransport:
    """Logs each request it would send and answers with a canned success.

    The canned body carries every key the scenarios read, so a dry run walks the whole
    scenario and shows every call it would make, in order.
    """

    CANNED_BODY: dict[str, Any] = {  # noqa: RUF012 - copied before being returned
        "id": "dry-run-place-id",
        "resourceId": "dry-run-resource-id",
        "resourceEmail": "dry-run-room@example.invalid",
        "emailAddress": "dry-run-room@example.invalid",
        "capacity": 8,
        "tags": [],
        "buildings": [{"buildingId": "dry-run-building-id"}],
        "value": [],
    }

    def __init__(self) -> None:
        self.calls: list[tuple[str, str]] = []

    def send(
        self,
        operation: str,
        method: str,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        json_body: dict[str, Any] | None = None,
        form_body: dict[str, str] | None = None,
    ) -> HttpResponse:
        """Record the call and return a canned 2xx response."""
        self.calls.append((method, operation))
        logger.info("[dry-run] would send %s %s", method, operation)
        status = 204 if method == "DELETE" else 200
        return HttpResponse(status=status, body=json.loads(json.dumps(self.CANNED_BODY)))


@dataclasses.dataclass
class SpikeContext:
    """What every scenario needs: how to send, how to wait, where to write findings."""

    transport: Transport
    token: str
    dry_run: bool
    sleep: Callable[[float], None] = time.sleep
    monotonic: Callable[[], float] = time.monotonic
    findings: Findings = dataclasses.field(default_factory=dict)

    def auth_headers(self) -> dict[str, str]:
        """Bearer header for the provider API."""
        return {"Authorization": f"Bearer {self.token}"}

    def send(
        self, operation: str, method: str, url: str, json_body: dict[str, Any] | None = None
    ) -> HttpResponse:
        """Send an authenticated JSON request."""
        return self.transport.send(
            operation, method, url, headers=self.auth_headers(), json_body=json_body
        )

    def wait(self, seconds: float) -> None:
        """Sleep, except in a dry run, where there is nothing to wait for."""
        if self.dry_run:
            logger.info("[dry-run] would wait %ss", seconds)
            return
        self.sleep(seconds)

    def record(self, key: str, value: Any) -> None:
        """Store one finding and log it. Callers pass only safe values."""
        self.findings[key] = value
        logger.info("finding %s = %s", key, value)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_json_object(raw: bytes) -> dict[str, Any]:
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except ValueError:
        return {}
    return parsed if isinstance(parsed, dict) else {"value": parsed}


def opaque(value: str) -> str:
    """A short stable hash, so a value can be compared across runs without being shown."""
    return hashlib.sha256(value.encode()).hexdigest()[:12]


def provider_error_code(response: HttpResponse) -> str | None:
    """The provider's machine-readable error code, never its human message.

    Error messages can echo request values back, so they stay out of logs and findings.
    """
    error = response.body.get("error")
    if not isinstance(error, dict):
        return None
    # Google: {"error": {"code": 409, "errors": [{"reason": "duplicate"}], "status": ...}}
    errors = error.get("errors")
    if isinstance(errors, list) and errors and isinstance(errors[0], dict):
        reason = errors[0].get("reason")
        if isinstance(reason, str):
            return reason
    # Google `status` or Microsoft `code`.
    for key in ("status", "code"):
        code = error.get(key)
        if isinstance(code, str):
            return code
    return None


def jwt_roles(token: str) -> list[str]:
    """The `roles` claim of an app-only access token (the granted application permissions).

    The signature is not checked: the token came straight from the token endpoint and
    only its claims are reported.
    """
    parts = token.split(".")
    if len(parts) < 2:
        return []
    payload = parts[1] + "=" * (-len(parts[1]) % 4)
    try:
        claims = json.loads(base64.urlsafe_b64decode(payload))
    except ValueError:
        return []
    roles = claims.get("roles", []) if isinstance(claims, dict) else []
    return sorted(role for role in roles if isinstance(role, str))


def _require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SpikeError(f"environment variable {name} is required with --execute")
    return value


def _spike_label() -> str:
    return uuid.uuid4().hex[:12]


def _delete_now(cleanups: Cleanups, label: str) -> HttpResponse:
    """Run one registered cleanup as a scenario step.

    It stays registered unless it worked, so a delete that fails or raises is tried
    again on the way out, and logged there if it fails again.
    """
    response = cleanups[label]()
    if response.ok or response.status == 404:
        del cleanups[label]
    return response


@contextmanager
def _cleanup_on_exit(cleanups: Cleanups) -> Iterator[None]:
    """Run every pending cleanup, newest first, whatever happened in the block."""
    try:
        yield
    finally:
        while cleanups:
            label, cleanup = cleanups.popitem()
            try:
                response = cleanup()
            except Exception:
                logger.exception("cleanup %s raised; delete it by hand", label)
                continue
            if not response.ok and response.status != 404:
                logger.error(
                    "cleanup %s returned HTTP %s; delete it by hand", label, response.status
                )


# ---------------------------------------------------------------------------
# Google
# ---------------------------------------------------------------------------


def google_access_token(*, dry_run: bool) -> str:
    """Mint a domain-wide-delegation token with the directory **write** scope."""
    if dry_run:
        logger.info("[dry-run] would mint a Google service-account token (write scope)")
        return DRY_RUN_TOKEN
    # Imported lazily: a dry run must not even load the HTTP transport.
    from google.auth.transport.requests import Request
    from google.oauth2 import service_account

    key_path = _require_env(ENV_GOOGLE_SA_JSON)
    admin_email = _require_env(ENV_GOOGLE_ADMIN_EMAIL)
    credentials = service_account.Credentials.from_service_account_file(
        key_path, scopes=[GOOGLE_WRITE_SCOPE]
    ).with_subject(admin_email)
    credentials.refresh(Request())
    token = credentials.token
    if not token:
        raise SpikeError("Google returned no access token")
    return str(token)


def _google_calendars_url(customer: str, resource_id: str | None = None) -> str:
    base = f"{GOOGLE_DIRECTORY_BASE}/customer/{urllib.parse.quote(customer)}/resources/calendars"
    if resource_id is None:
        return base
    return f"{base}/{urllib.parse.quote(resource_id)}"


def _google_room_body(
    resource_id: str, name: str, building_id: str | None, capacity: int
) -> dict[str, Any]:
    body: dict[str, Any] = {
        "resourceId": resource_id,
        "resourceName": name,
        "resourceCategory": "CONFERENCE_ROOM",
        "capacity": capacity,
        "resourceDescription": f"Vinta spike room {resource_id}",
    }
    if building_id is not None:
        body["buildingId"] = building_id
        body["floorName"] = "1"
    return body


def run_google_create_delete(ctx: SpikeContext, *, customer: str, building_id: str | None) -> None:
    """Spec open question 8, plus the idempotent-insert assumption of Phase 4."""
    label = _spike_label()
    cleanups: Cleanups = {}

    def schedule_delete(resource_id: str) -> None:
        cleanups[resource_id] = lambda: ctx.send(
            f"google.delete({resource_id})", "DELETE", _google_calendars_url(customer, resource_id)
        )

    with _cleanup_on_exit(cleanups):
        if building_id is None:
            buildings = ctx.send(
                "google.buildings.list",
                "GET",
                f"{GOOGLE_DIRECTORY_BASE}/customer/{urllib.parse.quote(customer)}"
                "/resources/buildings?maxResults=1",
            )
            listed = buildings.body.get("buildings") or []
            if not buildings.ok or not listed:
                raise SpikeError(
                    f"could not find a building (HTTP {buildings.status}); pass --building-id"
                )
            building_id = str(listed[0]["buildingId"])
        ctx.record("building_id", building_id)

        # Q8a: is buildingId required for CONFERENCE_ROOM?
        no_building_id = f"vinta-spike-{label}-nobuilding"
        no_building = ctx.send(
            f"google.insert({no_building_id}, no building)",
            "POST",
            _google_calendars_url(customer),
            _google_room_body(no_building_id, f"Vinta spike {label} nb", None, 4),
        )
        if no_building.ok:
            schedule_delete(no_building_id)
        ctx.record("insert_without_building_status", no_building.status)
        ctx.record("insert_without_building_error", provider_error_code(no_building))

        # The resourceId Phase 4 sets deterministically to `vinta-<link uuid>`.
        resource_id = f"vinta-spike-{label}"
        room_name = f"Vinta spike {label}"
        body = _google_room_body(resource_id, room_name, building_id, 4)
        inserted = ctx.send(
            f"google.insert({resource_id})", "POST", _google_calendars_url(customer), body
        )
        ctx.record("insert_status", inserted.status)
        if not inserted.ok:
            ctx.record("insert_error", provider_error_code(inserted))
            raise SpikeError(f"insert failed with HTTP {inserted.status}; nothing else to test")
        schedule_delete(resource_id)
        ctx.record("insert_kept_client_resource_id", inserted.body.get("resourceId") == resource_id)

        # Replaying the same insert: Phase 4 treats a 409 as "already created".
        replay = ctx.send(
            f"google.insert({resource_id}, replay)", "POST", _google_calendars_url(customer), body
        )
        ctx.record("replay_insert_status", replay.status)
        ctx.record("replay_insert_error", provider_error_code(replay))

        readback = ctx.send(
            f"google.get({resource_id})", "GET", _google_calendars_url(customer, resource_id)
        )
        ctx.record("readback_status", readback.status)
        email = readback.body.get("resourceEmail")
        ctx.record("readback_resource_email_hash", opaque(email) if email else None)
        ctx.record(
            "readback_description_round_trip",
            readback.body.get("resourceDescription") == body["resourceDescription"],
        )

        patched = ctx.send(
            f"google.patch({resource_id}, capacity)",
            "PATCH",
            _google_calendars_url(customer, resource_id),
            {"capacity": 8},
        )
        ctx.record("patch_capacity_status", patched.status)
        after_patch = ctx.send(
            f"google.get({resource_id}, after patch)",
            "GET",
            _google_calendars_url(customer, resource_id),
        )
        ctx.record("patch_capacity_round_trip", after_patch.body.get("capacity") == 8)

        # Q8b: does the directory reject a second room with the same name?
        duplicate_id = f"vinta-spike-{label}-dup"
        duplicate = ctx.send(
            f"google.insert({duplicate_id}, duplicate name)",
            "POST",
            _google_calendars_url(customer),
            _google_room_body(duplicate_id, room_name, building_id, 4),
        )
        if duplicate.ok:
            schedule_delete(duplicate_id)
        ctx.record("duplicate_name_insert_status", duplicate.status)
        ctx.record("duplicate_name_insert_error", provider_error_code(duplicate))

        deleted = _delete_now(cleanups, resource_id)
        ctx.record("delete_status", deleted.status)
        after_delete = ctx.send(
            f"google.get({resource_id}, after delete)",
            "GET",
            _google_calendars_url(customer, resource_id),
        )
        ctx.record("get_after_delete_status", after_delete.status)


# ---------------------------------------------------------------------------
# Microsoft
# ---------------------------------------------------------------------------


def microsoft_access_token(transport: Transport, *, dry_run: bool) -> str:
    """App-only token through the client-credentials flow, the way Phase 5 will get it."""
    if dry_run:
        logger.info("[dry-run] would request a Microsoft app-only token")
        return DRY_RUN_TOKEN
    tenant_id = _require_env(ENV_MS_TENANT_ID)
    response = transport.send(
        "microsoft.token",
        "POST",
        f"{MS_LOGIN_BASE}/{urllib.parse.quote(tenant_id)}/oauth2/v2.0/token",
        form_body={
            "grant_type": "client_credentials",
            "client_id": _require_env(ENV_MS_CLIENT_ID),
            "client_secret": _require_env(ENV_MS_CLIENT_SECRET),
            "scope": MS_GRAPH_DEFAULT_SCOPE,
        },
    )
    token = response.body.get("access_token")
    if not response.ok or not isinstance(token, str):
        raise SpikeError(
            f"token request failed with HTTP {response.status} ({provider_error_code(response)})"
        )
    return token


@dataclasses.dataclass(frozen=True)
class MicrosoftOptions:
    """Where and how patiently to run the Microsoft scenarios."""

    floor_id: str
    places_base: str
    poll_interval: float
    provision_timeout: float
    post_delete_wait: float


def _place_url(options: MicrosoftOptions, place_id: str | None = None) -> str:
    base = f"{options.places_base}/places"
    return base if place_id is None else f"{base}/{urllib.parse.quote(place_id)}"


def _create_ms_room(
    ctx: SpikeContext,
    options: MicrosoftOptions,
    label: str,
    tag: str,
    cleanups: Cleanups,
) -> tuple[str, float]:
    """POST a room under the floor. Returns its place id and the monotonic create time."""
    started = ctx.monotonic()
    created = ctx.send(
        f"microsoft.places.create({label})",
        "POST",
        _place_url(options),
        {
            "@odata.type": "microsoft.graph.room",
            "displayName": f"Vinta spike {label}",
            "parentId": options.floor_id,
            "capacity": 4,
            "tags": [tag],
        },
    )
    ctx.record("create_status", created.status)
    if not created.ok:
        ctx.record("create_error", provider_error_code(created))
        raise SpikeError(f"create failed with HTTP {created.status}; nothing else to test")
    place_id = created.body.get("id")
    if not isinstance(place_id, str):
        raise SpikeError("create returned no place id")
    ctx.record("place_id", place_id)
    created_email = created.body.get("emailAddress")
    ctx.record("create_response_has_email", bool(created_email))
    cleanups[place_id] = lambda: ctx.send(
        f"microsoft.places.delete({place_id})", "DELETE", _place_url(options, place_id)
    )
    return place_id, started


def _poll(
    ctx: SpikeContext,
    options: MicrosoftOptions,
    check: Callable[[], HttpResponse],
    done: Callable[[HttpResponse], bool],
) -> HttpResponse:
    """Call `check` until `done` says so or the provisioning timeout runs out."""
    deadline = ctx.monotonic() + options.provision_timeout
    while True:
        response = check()
        if done(response) or ctx.monotonic() >= deadline:
            return response
        ctx.wait(options.poll_interval)


def run_ms_create_delete(ctx: SpikeContext, options: MicrosoftOptions) -> None:
    """Spec open question 1, plus the tag-lookup idempotency assumption of Phase 6."""
    label = _spike_label()
    tag = f"vinta-link-{uuid.uuid4()}"
    ctx.record("token_roles", jwt_roles(ctx.token))
    cleanups: Cleanups = {}

    with _cleanup_on_exit(cleanups):
        place_id, created_at = _create_ms_room(ctx, options, label, tag, cleanups)

        # Provisioning: when does the place report a mailbox address?
        place = _poll(
            ctx,
            options,
            lambda: ctx.send(
                f"microsoft.places.get({place_id})", "GET", _place_url(options, place_id)
            ),
            lambda r: r.ok and bool(r.body.get("emailAddress")),
        )
        email = place.body.get("emailAddress")
        ctx.record(
            "email_address_seconds", round(ctx.monotonic() - created_at, 1) if email else None
        )
        ctx.record("email_address_hash", opaque(email) if email else None)
        tags = place.body.get("tags")
        ctx.record("tag_round_trip", isinstance(tags, list) and tag in tags)

        # Phase 6 looks up the tag before any POST, so the lookup itself must work.
        tag_filter = urllib.parse.quote(f"tags/any(t:t eq '{tag}')")
        lookup = ctx.send(
            "microsoft.places.list(rooms, filter by tag)",
            "GET",
            f"{options.places_base}/places/microsoft.graph.room?$filter={tag_filter}",
        )
        matches = lookup.body.get("value")
        ctx.record("tag_filter_status", lookup.status)
        ctx.record("tag_filter_error", provider_error_code(lookup))
        ctx.record(
            "tag_filter_found_room",
            isinstance(matches, list)
            and any(isinstance(m, dict) and m.get("id") == place_id for m in matches),
        )

        if email:
            mailbox_url = f"{GRAPH_V1_BASE}/users/{urllib.parse.quote(email)}"
            calendar = _poll(
                ctx,
                options,
                lambda: ctx.send(
                    "microsoft.mailbox.calendar(room)", "GET", f"{mailbox_url}/calendar"
                ),
                lambda r: r.ok,
            )
            ctx.record("mailbox_calendar_status", calendar.status)
            ctx.record(
                "mailbox_calendar_seconds",
                round(ctx.monotonic() - created_at, 1) if calendar.ok else None,
            )
            # Plan open question 4: is Calendars.Read enough for app-only getSchedule?
            schedule = ctx.send(
                "microsoft.getSchedule(room)",
                "POST",
                f"{mailbox_url}/calendar/getSchedule",
                {
                    "schedules": [email],
                    "startTime": {"dateTime": "2030-01-01T09:00:00", "timeZone": "UTC"},
                    "endTime": {"dateTime": "2030-01-01T10:00:00", "timeZone": "UTC"},
                },
            )
            ctx.record("get_schedule_status", schedule.status)
            ctx.record("get_schedule_error", provider_error_code(schedule))

        patched = ctx.send(
            f"microsoft.places.patch({place_id}, capacity)",
            "PATCH",
            _place_url(options, place_id),
            {"@odata.type": "microsoft.graph.room", "capacity": 8},
        )
        ctx.record("patch_capacity_status", patched.status)
        ctx.record("patch_capacity_error", provider_error_code(patched))
        after_patch = ctx.send(
            f"microsoft.places.get({place_id}, after patch)", "GET", _place_url(options, place_id)
        )
        ctx.record("patch_capacity_round_trip", after_patch.body.get("capacity") == 8)
        after_tags = after_patch.body.get("tags")
        ctx.record("tag_survives_patch", isinstance(after_tags, list) and tag in after_tags)

        deleted = _delete_now(cleanups, place_id)
        ctx.record("delete_status", deleted.status)
        ctx.record("delete_error", provider_error_code(deleted))
        after_delete = ctx.send(
            f"microsoft.places.get({place_id}, after delete)", "GET", _place_url(options, place_id)
        )
        ctx.record("get_place_after_delete_status", after_delete.status)

        # Q1: does the room mailbox outlive the place?
        if email:
            ctx.wait(options.post_delete_wait)
            mailbox_url = f"{GRAPH_V1_BASE}/users/{urllib.parse.quote(email)}"
            user = ctx.send(
                "microsoft.users.get(room, after delete)", "GET", f"{mailbox_url}?$select=id"
            )
            ctx.record("mailbox_user_status_after_delete", user.status)
            ctx.record("mailbox_user_error_after_delete", provider_error_code(user))
            calendar_after = ctx.send(
                "microsoft.mailbox.calendar(room, after delete)", "GET", f"{mailbox_url}/calendar"
            )
            ctx.record("mailbox_calendar_status_after_delete", calendar_after.status)


def run_ms_description(ctx: SpikeContext, options: MicrosoftOptions) -> None:
    """Spec open question 2: which room property, if any, keeps free text."""
    label = _spike_label()
    tag = f"vinta-link-{uuid.uuid4()}"
    cleanups: Cleanups = {}
    # Free text as a partner would send it: long, punctuated, multi-line.
    marker = f"Vinta spike {label}. Second line, with punctuation: ok?\n" + "x" * 240

    with _cleanup_on_exit(cleanups):
        place_id, _ = _create_ms_room(ctx, options, label, tag, cleanups)
        place = _poll(
            ctx,
            options,
            lambda: ctx.send(
                f"microsoft.places.get({place_id})", "GET", _place_url(options, place_id)
            ),
            lambda r: r.ok,
        )
        ctx.record(
            "room_property_names",
            sorted(key for key in place.body if not key.startswith("@odata")),
        )

        for field in MS_DESCRIPTION_CANDIDATES:
            patched = ctx.send(
                f"microsoft.places.patch({place_id}, {field})",
                "PATCH",
                _place_url(options, place_id),
                {"@odata.type": "microsoft.graph.room", field: marker},
            )
            readback = ctx.send(
                f"microsoft.places.get({place_id}, after {field})",
                "GET",
                _place_url(options, place_id),
            )
            stored = readback.body.get(field)
            ctx.record(
                f"candidate_{field}",
                {
                    "patch_status": patched.status,
                    "patch_error": provider_error_code(patched),
                    "round_trip_exact": stored == marker,
                    "stored_length": len(stored) if isinstance(stored, str) else None,
                    "sent_length": len(marker),
                },
            )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    """The CLI. Every subcommand is dry-run unless `--execute` is passed."""
    parser = argparse.ArgumentParser(
        prog="resource_directory_spike",
        description=(
            "Probe Google and Microsoft room-directory writes against SANDBOX tenants. "
            "Dry-run by default: nothing is sent without --execute."
        ),
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="debug logging")
    subparsers = parser.add_subparsers(dest="command", required=True, metavar="SUBCOMMAND")

    def add_execute(sub: argparse.ArgumentParser) -> None:
        sub.add_argument(
            "--execute",
            action="store_true",
            help="really call the provider (creates and deletes rooms in the sandbox tenant)",
        )

    google = subparsers.add_parser(
        "google-create-delete",
        help="insert, replay, read, patch and delete a Google room; duplicate-name check",
        description=(
            f"Needs {ENV_GOOGLE_SA_JSON} (path to the service-account key file) and "
            f"{ENV_GOOGLE_ADMIN_EMAIL} (the admin the service account impersonates). "
            f"{ENV_GOOGLE_CUSTOMER} defaults to my_customer."
        ),
    )
    google.add_argument(
        "--building-id", help="building to put the room in (default: the first one listed)"
    )
    add_execute(google)

    for name, help_text in (
        ("ms-create-delete", "create, patch and delete a Microsoft room; mailbox check"),
        ("ms-description", "which Microsoft room property keeps free text"),
    ):
        sub = subparsers.add_parser(
            name,
            help=help_text,
            description=(
                f"Needs {ENV_MS_TENANT_ID}, {ENV_MS_CLIENT_ID} and {ENV_MS_CLIENT_SECRET} "
                "for an Entra app with Place.ReadWrite.All and Calendars.Read "
                "(application permissions, admin-consented)."
            ),
        )
        sub.add_argument("--floor-id", help=f"parent floor place id (or {ENV_MS_FLOOR_ID})")
        sub.add_argument(
            "--places-base",
            default=GRAPH_PLACES_DEFAULT_BASE,
            help="Graph base URL for /places calls (default: %(default)s)",
        )
        sub.add_argument("--poll-interval", type=float, default=10.0, help="seconds")
        sub.add_argument(
            "--provision-timeout",
            type=float,
            default=600.0,
            help="seconds to wait for the room email and mailbox",
        )
        sub.add_argument(
            "--post-delete-wait",
            type=float,
            default=60.0,
            help="seconds to wait after DELETE before checking the mailbox",
        )
        add_execute(sub)

    return parser


def _microsoft_options(args: argparse.Namespace, *, dry_run: bool) -> MicrosoftOptions:
    floor_id = args.floor_id or os.environ.get(ENV_MS_FLOOR_ID, "").strip()
    if not floor_id:
        if not dry_run:
            raise SpikeError(f"--floor-id (or {ENV_MS_FLOOR_ID}) is required with --execute")
        floor_id = "dry-run-floor-id"
    return MicrosoftOptions(
        floor_id=floor_id,
        places_base=args.places_base.rstrip("/"),
        poll_interval=args.poll_interval,
        provision_timeout=args.provision_timeout,
        post_delete_wait=args.post_delete_wait,
    )


def run(args: argparse.Namespace, transport: Transport | None = None) -> Findings:
    """Run the chosen subcommand and return its findings."""
    dry_run = not args.execute
    if transport is None:
        transport = DryRunTransport() if dry_run else UrllibTransport()

    if args.command == "google-create-delete":
        ctx = SpikeContext(
            transport=transport, token=google_access_token(dry_run=dry_run), dry_run=dry_run
        )
        customer = os.environ.get(ENV_GOOGLE_CUSTOMER, "").strip() or "my_customer"
        run_google_create_delete(ctx, customer=customer, building_id=args.building_id)
    else:
        options = _microsoft_options(args, dry_run=dry_run)
        ctx = SpikeContext(
            transport=transport,
            token=microsoft_access_token(transport, dry_run=dry_run),
            dry_run=dry_run,
        )
        if args.command == "ms-create-delete":
            run_ms_create_delete(ctx, options)
        else:
            run_ms_description(ctx, options)
    return {"command": args.command, "dry_run": dry_run, "findings": ctx.findings}


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point. Prints the findings as JSON on stdout; logs go to stderr."""
    args = build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        stream=sys.stderr,
    )
    if not args.execute:
        logger.info("DRY RUN: no request leaves this machine. Pass --execute to call the provider.")
    try:
        summary = run(args)
    except SpikeError as exc:
        logger.error("spike stopped: %s", exc)
        return 1
    sys.stdout.write(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
