# Generated by Django 6.0.5 on 2026-07-04 03:05

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_use", "Terms of Use"),
                            ("sms_consent", "SMS Messaging Consent"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Monotonically increasing per document_type."
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "body_markdown",
                    models.TextField(help_text="Raw markdown body, rendered client-side."),
                ),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["document_type", "-version"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "-version"], name="legal_polic_documen_e33adc_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "version"), name="uq_policydocument_type_version"
                    )
                ],
            },
        ),
    ]
