# Generated by Django 6.0.5 on 2026-07-04 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_userconsent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsent",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(fields=["phone_number"], name="legal_userconsent_phone_idx"),
        ),
    ]
