# Generated by Django 6.0.5 on 2026-08-26 03:41

import django.db.models.deletion
import typing
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAuditIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("identity_type", models.CharField(default="user", max_length=32)),
                ("identity_key", models.CharField(blank=True, max_length=255)),
                ("identity_label", models.CharField(blank=True, max_length=255)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("group_names", models.JSONField(blank=True, default=list)),
                ("permission_keys", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("system_user_scopes", models.JSONField(blank=True, default=list)),
                (
                    "system_user_scoped_to_membership",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "membership_groups",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.group"
                    ),
                ),
                (
                    "membership_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.permission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "AUDIT_IDENTITY_MODEL",
                "indexes": [
                    models.Index(
                        fields=["identity_type", "identity_key"],
                        name="audit_integ_identit_9b330e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAuditScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_scopes",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("organization__isnull", True), ("scope_type", "global")
                            ),
                            models.Q(
                                models.Q(("scope_type", "global"), _negated=True),
                                ("organization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="audit_org_scope_type_and_org_agree",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="audit_org_scope_unique_key_per_type",
                    ),
                ],
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
