# Generated by Django 6.0.5 on 2026-06-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organizationmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="is_active",
            field=models.BooleanField(
                db_default=True,
                db_index=True,
                default=True,
                help_text="Whether this membership is active. Inactive memberships are treated as gated: the user still has a row but loses all tenant-scoped access until reactivated. Use this to disable a user without deleting their membership record (which would lose role/history). Default True keeps every existing read unchanged.",
            ),
        ),
    ]
