# Generated by Django 6.0.5 on 2026-06-13 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Phase 1 — Membership FK migration.

    Converts OrganizationMembership.user from OneToOneField to ForeignKey so a
    user can hold memberships in multiple organizations. Drops the implicit
    UNIQUE(user_id) index that the OneToOne carried and replaces it with the
    composite UNIQUE(user_id, organization_id) constraint
    ``uniq_membership_user_organization``.

    Lock posture: the table is small / empty in this environment. Both
    AlterField (brief ACCESS EXCLUSIVE on metadata) and AddConstraint
    (builds a unique index; ACCESS EXCLUSIVE for the duration) are safe to
    run inline. No data migration required — existing rows are 1:1 under the
    new FK.

    Reverse path: AlterField restores the OneToOneField (re-adds the implicit
    UNIQUE on user_id); RemoveConstraint drops the composite unique. Both are
    handled by Django's framework without manual SQL.
    """

    dependencies = [
        ("organizations", "0005_organizationmembership_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"),
                name="uniq_membership_user_organization",
            ),
        ),
    ]
