# Generated by Django 6.0.5 on 2026-06-13 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Phase 4 — Relax OrganizationInvitation.email uniqueness from global to per-org.

    Previously ``email`` carried a field-level ``unique=True`` which prevented the
    same email address from having concurrent pending invitations across different
    organizations.  Phase 4 enables multi-org invite accept (Use-case 6): a user
    already in org A can receive and accept an invitation from org B.  The global
    unique blocks that flow, so we relax it to a composite
    ``unique(email, organization)`` — the same email can now appear once per org,
    but a duplicate invite within the same org is still rejected.

    Operations (in order):
    1. ``AlterField`` — drops the implicit ``UNIQUE(email)`` index that Django
       generated from ``EmailField(unique=True)`` (a metadata/index drop, not a
       table rewrite); on the small/empty OrganizationInvitation table this is
       safe to run inline.
    2. ``AddConstraint`` — creates the composite ``UNIQUE(email, organization_id)``
       index.  Takes ``ACCESS EXCLUSIVE`` for the duration of the index build.
       On the small/empty table this is safe inline (no CONCURRENTLY needed).

    Reverse path:
    - ``RemoveConstraint`` drops the composite unique index.
    - ``AlterField`` restores ``EmailField(unique=True)``, re-adding the global
      ``UNIQUE(email)`` index.  Both are handled by Django's framework without
      manual SQL.

    Note: ``invite_user_to_organization`` already filters by both ``email`` and
    ``organization`` in its ``get_or_create`` call, so it works correctly under
    the new constraint — a second org inviting the same email now succeeds.
    """

    dependencies = [
        ("organizations", "0006_alter_organizationmembership_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinvitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="organizationinvitation",
            constraint=models.UniqueConstraint(
                fields=("email", "organization"),
                name="uniq_invitation_email_organization",
            ),
        ),
    ]
