# Generated by Django 6.0.5 on 2026-06-17 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_invitation_email_org_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="can_invite_organizations",
            field=models.BooleanField(
                default=False,
                help_text="Whether this organization can invite/create other organizations. DB/Django-admin only — never exposed via any API. Enables the whole reseller capability bundle.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent organization if this is a child org. A reseller with live children cannot be deleted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_organizations",
                to="organizations.organization",
            ),
        ),
    ]
