# Generated by Django 6.0.5 on 2026-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organization_can_invite_organizations_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="uniq_org_name_per_parent"
            ),
        ),
    ]
