# Generated by Django 6.0.5 on 2026-06-17 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_uniq_org_name_per_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin")],
                default="member",
                help_text="Role the invited user should receive on accepting the invitation. Defaults to MEMBER. Admin invitations must be explicit.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_organization_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
