# Generated by Django 6.0.5 on 2026-06-17 13:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_organizationinvitation_invited_by_nullable_and_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        help_text="The display name of the white-labeled app (e.g., 'MyScheduler').",
                        max_length=120,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to the reseller's logo image.",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary color as hex code: #RRGGBB or #RRGGBBAA.",
                        max_length=9,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Secondary color as hex code: #RRGGBB or #RRGGBBAA.",
                        max_length=9,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email address for the From/reply-to on branded transactional emails.",
                        max_length=254,
                    ),
                ),
                (
                    "return_url_allowlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="List of URLs that are allowed as return addresses after OAuth flows.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="The reseller organization this branding customizes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Branding",
                "verbose_name_plural": "Organization Brandings",
            },
        ),
    ]
