# Generated by Django 6.0.5 on 2026-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organizationmembership_composite_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_event_update_policy',
            field=models.CharField(choices=[('allow', 'Allow direct updates'), ('change_request', 'Updates create change requests'), ('forbidden', 'Updates are forbidden')], db_default='change_request', default='change_request', help_text='Policy for handling inbound external provider edits and deletions to synced events. ALLOW: apply directly. CHANGE_REQUEST: route to approval. FORBIDDEN: auto-undo.', max_length=20),
        ),
    ]
