# Generated by Django 6.0.5 on 2026-07-19 18:33
#
# Phase 3 of billing plans and limits: `organizations.OrganizationTier` and
# `organizations.SubscriptionPlan` are superseded by `payments.BillingPlan` (+
# `PlanLimit` / `PlanEntitlement`). Both tables are empty in every environment
# (`organizations_organizationtier` and `organizations_subscriptionplan` are never
# written to; `Organization.tier` is null on every row and nothing assigns it), so
# this destructive delete carries no data risk. The reverse path recreates the prior
# schema.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_organization_external_event_update_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='organization',
        ),
        migrations.DeleteModel(
            name='OrganizationTier',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
