# Generated by Django 6.0.5 on 2026-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_subscriptionplan_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='is_billing_owner',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text="Whether this membership may manage the organization's billing (change plan, purchase add-ons, manage payment method) in addition to admins. The permission that reads this flag (IsBillingOwnerOrAdmin) lands in a later phase; this field only marks the membership."),
        ),
    ]
