# Generated by Django 6.0.5 on 2026-07-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationmembership_is_billing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_billing_owner',
            field=models.BooleanField(db_default=False, default=False, help_text="Whether this membership may manage the organization's billing (change plan, purchase add-ons, manage payment method) in addition to admins. This flag only marks the membership; the permission check that reads it is IsBillingOwnerOrAdmin."),
        ),
    ]
