# Generated by Django 6.0.5 on 2026-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_organization_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationbranding",
            name="return_url_allowlist",
        ),
        migrations.AddField(
            model_name="organizationbranding",
            name="redirect_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Single post-authentication redirect destination for this organization. Replaces the old return_url_allowlist: no caller-supplied redirect target is ever honored, so there is nothing to validate at request time and no open-redirect surface. Must be HTTPS with no wildcard character and no path-prefix pattern (organizations.redirect_url_validation).",
            ),
        ),
    ]
