# Generated by Django 6.0.5 on 2026-08-07 21:46

import s3direct_overrides.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_remove_organizationbranding_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationbranding",
            name="logo",
            field=s3direct_overrides.model_fields.S3DirectImageField(
                blank=True,
                dest="branding_logos",
                help_text="S3 key of the organization's uploaded logo image (PNG/JPEG/WebP; SVG rejected -- see vinta_schedule_api.settings.base.S3DIRECT_DESTINATIONS['branding_logos']). Replaces the old logo_url: the upload goes straight from the browser to our storage and only the key is stored. API reads sign the key on the way out (organizations.branding_logo.signed_logo_url); the invitation email, whose URLs must outlive a signature, reads through the delivery route instead (organizations.branding_logo.build_logo_delivery_url).",
                max_length=255,
                null=True,
                upload_to="uploads/branding_logos",
            ),
        ),
    ]
