"""Give ``OrganizationMembership`` a surrogate ``id`` primary key again.

Why
---
``AbstractOrganizationMembership`` (vinta-django-orgs) declares ``groups`` and
``permissions`` as ``ManyToManyField``s, and Django cannot hang a many-to-many
relation off a model with a composite primary key -- the through table has
nowhere to put a two-column reference. Reverting the composite PK added in
``0013_organizationmembership_composite_pk`` is therefore a precondition for
adopting the abstract base at all, not a preference.

What is deliberately *not* touched
----------------------------------
``uniq_membership_user_organization``. Five raw-SQL composite foreign keys
declare::

    FOREIGN KEY (<name>_user_id, organization_id)
    REFERENCES organizations_organizationmembership (user_id, organization_id)

-- ``calendar_integration``'s ``0026`` (CalendarOwnership), ``0032``
(EventAttendance), ``0036`` (CalendarManagementToken), ``0038``
(ExternalEventChangeRequest.resolved_by) and ``0040`` (BookingPolicy). PostgreSQL
binds each of those to one specific unique index. The unique *constraint* has
existed since well before the composite PK did and is the lower-OID index of the
two, so it is the one they are bound to; dropping the composite primary key
below leaves them intact and needs no rebind, no data migration, and no DDL on
five tenant tables. This migration depends on ``calendar_integration.0040`` so
that all five constraints exist before the swap runs -- if any of them were in
fact bound to the primary-key index, the ``DROP CONSTRAINT`` below would fail
loudly here rather than silently on the one database where the ordering differed.

Why raw SQL rather than the autodetector's operations
-----------------------------------------------------
Exactly the mirror image of ``0013``. Django's autodetector emits
``RemoveField('pk')`` (a state-only no-op, since ``CompositePrimaryKey`` is a
virtual field) plus ``AddField('id')`` -- and ``AddField`` of a column that is
already declared ``primary_key=True`` cannot be applied to a table that still
has a primary key. ``SeparateDatabaseAndState`` keeps the state half exactly what
``makemigrations`` expects (so ``makemigrations --check`` stays clean) and hands
the database half the three statements that actually perform the swap.

Lock / downtime audit
---------------------
Every statement takes ``ACCESS EXCLUSIVE`` on
``organizations_organizationmembership``:

1. ``DROP CONSTRAINT ..._pkey`` -- instant; drops the composite PK index.
2. ``ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY`` -- rewrites the
   table, because the column is NOT NULL with a generated value per row.
3. ``ADD CONSTRAINT ..._pkey PRIMARY KEY (id)`` -- builds a fresh unique index
   under the same lock (PostgreSQL has no ``ADD PRIMARY KEY ... CONCURRENTLY``).

Memberships are one row per user per organization, so the rewrite is fast, but
the table gates every tenant-scoped request: schedule in a low-traffic window.
Kept atomic (the default) so the table is never visible to another transaction
without a primary key.

Reverse
-------
Restores the composite primary key exactly as ``0013`` left it.
"""

from django.db import migrations, models


DROP_COMPOSITE_PK_AND_RESTORE_ID = """
ALTER TABLE organizations_organizationmembership
  DROP CONSTRAINT organizations_organizationmembership_pkey;
ALTER TABLE organizations_organizationmembership
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE organizations_organizationmembership
  ADD CONSTRAINT organizations_organizationmembership_pkey PRIMARY KEY (id);
"""

REVERSE_RESTORE_COMPOSITE_PK = """
ALTER TABLE organizations_organizationmembership
  DROP CONSTRAINT organizations_organizationmembership_pkey;
ALTER TABLE organizations_organizationmembership
  DROP COLUMN id;
ALTER TABLE organizations_organizationmembership
  ADD CONSTRAINT organizations_organizationmembership_pkey
  PRIMARY KEY (user_id, organization_id);
"""


class Migration(migrations.Migration):
    """Surrogate ``id`` primary key on OrganizationMembership."""

    dependencies = [
        ("organizations", "0022_organization_week_start"),
        # All five raw-SQL composite PROTECT FKs must exist before the primary
        # key is swapped -- see the module docstring.
        ("calendar_integration", "0040_bookingpolicy_membership_protect_fk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="organizationmembership",
                    name="pk",
                ),
                migrations.AddField(
                    model_name="organizationmembership",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_COMPOSITE_PK_AND_RESTORE_ID,
                    reverse_sql=REVERSE_RESTORE_COMPOSITE_PK,
                ),
            ],
        ),
    ]
