# Generated by Django 6.0.5 on 2026-08-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_organization_slug_not_null_and_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('manage_organization', "Can manage the organization's settings"), ('manage_branding', "Can manage the organization's branding")]},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'default_manager_name': 'objects', 'permissions': [('manage_members', "Can manage the organization's members")]},
        ),
    ]
