# Generated by Django 6.0.5 on 2026-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0017_alter_organizationmembership_is_billing_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=None,
                help_text="Public, URL-safe identifier used by the organization's branded login page and by brandingForTenant. Optional until the organization sets one self-serve; stored as NULL (never empty string) when unset — default=None keeps a field left blank in a form/serializer NULL rather than '', which is what lets the unique index admit any number of organizations with no slug. Mutable after set: changing it orphans previously-issued branded login URLs, which then fall back to the default identity rather than erroring. Format, reserved-word, and confusable-character rules live in tenancy.slug_validation and are enforced by each write surface (REST serializer, admin form, GraphQL input), not here.",
                max_length=63,
                null=True,
                unique=True,
            ),
        ),
    ]
