# Generated by Django 6.0.5 on 2026-08-04 17:39

import s3direct_overrides.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenancy",
            "0019_remove_organizationbranding_return_url_allowlist_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationbranding",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="organizationbranding",
            name="logo",
            field=s3direct_overrides.model_fields.S3DirectImageField(
                blank=True,
                dest="branding_logos",
                help_text="S3 key of the reseller's uploaded logo image (PNG/JPEG/WebP; SVG rejected -- see vinta_schedule_api.settings.base.S3DIRECT_DESTINATIONS['branding_logos']). Replaces the old logo_url: the upload goes straight from the browser to our storage, and nothing renders it as a raw or signed URL -- every read goes through tenancy.branding_logo.build_logo_delivery_url instead.",
                max_length=255,
                null=True,
                upload_to="uploads/branding_logos",
            ),
        ),
    ]
