# Generated by Django 6.0.5 on 2026-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0021_alter_organizationbranding_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='week_start',
            field=models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], db_default='monday', default='monday', help_text='Day of the week that starts the week for quota period boundaries. Used for calculating quota periods in group-scoped availability rules.', max_length=20),
        ),
    ]
