"""Phase 1c: unwind ``OrganizationMembership``'s composite primary key.

The exact inverse of ``0013_organizationmembership_composite_pk``, and written the
same way (``SeparateDatabaseAndState``) for the same reason: ``CompositePrimaryKey``
is a *virtual* ORM-level field, so Django's autodetector treats ``RemoveField(pk)``
as a database no-op and would leave the table with its composite ``PRIMARY KEY``
still in place under a state that says the primary key is ``id``.

Why unwind it
-------------
Django cannot hang a ``ManyToManyField`` off a composite-primary-key model, and
``AbstractOrganizationMembership`` (vinta-django-orgs) declares two --
``groups`` and ``permissions``. They are the whole point of the migration this
phase belongs to, so the composite key goes.

Why the five raw-SQL PROTECT FKs need no rebind
-----------------------------------------------
Five composite foreign keys reference
``organizations_organizationmembership (user_id, organization_id)``:

  * ``calownership_membership_protect_fk``    (calendar_integration_calendarownership)
  * ``evattendance_membership_protect_fk``    (calendar_integration_eventattendance)
  * ``calmgmttoken_membership_protect_fk``    (calendar_integration_calendarmanagementtoken)
  * ``externaleventcr_resolved_by_protect_fk``(calendar_integration_externaleventchangerequest)
  * ``bookingpolicy_membership_protect_fk``   (calendar_integration_bookingpolicy)

PostgreSQL binds a foreign key to one *specific* unique index, recorded in
``pg_constraint.conindid``. Verified against a real database rather than assumed:
all five report ``conindid`` = ``uniq_membership_user_organization``, **not**
``organizations_organizationmembership_pkey`` -- including the two
(``externaleventcr_resolved_by_protect_fk``, ``bookingpolicy_membership_protect_fk``)
that were created *after* 0013, i.e. at a moment when the composite PK index and
the unique constraint both existed and either would have been a legal target.

``0013`` kept ``uniq_membership_user_organization`` deliberately (its "Option A"),
and this migration keeps it too. Dropping the composite ``PRIMARY KEY`` therefore
drops an index nothing depends on, and the five FKs stay valid across both
directions of this migration with no drop/re-add and no data migration.
``calendar_integration/tests/test_membership_protect_fk.py`` proves the guarantee
holds after the swap by actually tripping the constraint.

Forward DB SQL
--------------
Byte-for-byte ``0013``'s ``REVERSE_RESTORE_ID_PK``::

    ALTER TABLE organizations_organizationmembership
      DROP CONSTRAINT organizations_organizationmembership_pkey;   -- composite PK
    ALTER TABLE organizations_organizationmembership
      ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;       -- BigAutoField shape
    ALTER TABLE organizations_organizationmembership
      ADD CONSTRAINT organizations_organizationmembership_pkey PRIMARY KEY (id);

``ADD COLUMN ... GENERATED BY DEFAULT AS IDENTITY`` fills every existing row from
the fresh sequence as it rewrites the table, so the ``PRIMARY KEY (id)`` that
follows always has distinct, non-null values to build on.

Lock / downtime audit
---------------------
Every statement takes ``ACCESS EXCLUSIVE`` on
``organizations_organizationmembership``, and the ``ADD COLUMN`` with an identity
default rewrites the table. That table is one row per user-per-organization, so
the rewrite is short -- but it does gate every tenant-scoped request, so schedule
it in a low-traffic window. Kept ``atomic = True`` (the default) so the table is
never visible to another transaction without a primary key.

Reverse
-------
Restores ``0013``'s end state exactly: drop the ``id`` PK, drop the column (and
its identity sequence), re-add ``PRIMARY KEY (user_id, organization_id)``. The
surrogate ids are discarded, which is why the plan's Rollback note calls this
phase the first non-cleanly-revertible one -- nothing *references* those ids, so
the schema round-trips, but the values do not come back.
"""

from django.db import migrations, models


DROP_COMPOSITE_PK_AND_RESTORE_ID_PK = """
ALTER TABLE organizations_organizationmembership
  DROP CONSTRAINT organizations_organizationmembership_pkey;
ALTER TABLE organizations_organizationmembership
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE organizations_organizationmembership
  ADD CONSTRAINT organizations_organizationmembership_pkey PRIMARY KEY (id);
"""

REVERSE_RESTORE_COMPOSITE_PK = """
ALTER TABLE organizations_organizationmembership
  DROP CONSTRAINT organizations_organizationmembership_pkey;
ALTER TABLE organizations_organizationmembership
  DROP COLUMN id;
ALTER TABLE organizations_organizationmembership
  ADD CONSTRAINT organizations_organizationmembership_pkey
  PRIMARY KEY (user_id, organization_id);
"""


class Migration(migrations.Migration):
    """Surrogate ``id`` primary key back on OrganizationMembership."""

    dependencies = [
        ("tenancy", "0023_move_content_types_to_tenancy"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="organizationmembership",
                    name="pk",
                ),
                migrations.AddField(
                    model_name="organizationmembership",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_COMPOSITE_PK_AND_RESTORE_ID_PK,
                    reverse_sql=REVERSE_RESTORE_COMPOSITE_PK,
                ),
            ],
        ),
    ]
