# Generated by Django 6.0.5 on 2026-06-20 20:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0013_organizationmembership_composite_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=100)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('membership', 'Membership'), ('system_user', 'System user'), ('single_use_code', 'Single-use code')], db_index=True, max_length=20)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, choices=[('member', 'Member'), ('admin', 'Admin')], max_length=20, null=True)),
                ('system_user_scopes', models.JSONField(blank=True, null=True)),
                ('system_user_scoped_to_membership', models.BigIntegerField(blank=True, null=True)),
                ('subject_type', models.CharField(db_index=True, max_length=255)),
                ('subject_id', models.CharField(db_index=True, max_length=255)),
                ('subject_label', models.CharField(blank=True, max_length=255, null=True)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditAffectedMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('membership_user_id', models.BigIntegerField()),
                ('audit', models.ForeignObject(editable=False, from_fields=['audit_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='affected_membership_links', to='audit.audit', to_fields=['id', 'organization_id'])),
                ('audit_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_membership_links_fk_rel', to='audit.audit')),
                ('membership', models.ForeignObject(editable=False, from_fields=['membership_user_id', 'organization_id'], on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_affected_links', to='organizations.organizationmembership', to_fields=['user_id', 'organization_id'])),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='affected_memberships',
            field=models.ManyToManyField(blank=True, related_name='+', through='audit.AuditAffectedMembership', through_fields=('audit_fk', 'membership'), to='organizations.organizationmembership'),
        ),
        migrations.AddIndex(
            model_name='auditaffectedmembership',
            index=models.Index(fields=['organization', 'membership_user_id'], name='auditaffected_org_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditaffectedmembership',
            constraint=models.UniqueConstraint(fields=('audit_fk', 'membership_user_id'), name='uniq_audit_membership'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_f68cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'action', 'created_at'], name='audit_audit_organiz_c39eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'actor_type', 'actor_id'], name='audit_audit_organiz_ef21bd_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'subject_type', 'subject_id'], name='audit_audit_organiz_de064e_idx'),
        ),
    ]
