"""Move ``audit`` onto vinta-django-orgs' scoped mixin and safe relations.

Generated by ``makemigrations`` and then read operation by operation against
``sqlmigrate``, because the autodetector will not tell you when an
``AlterField`` drops a constraint it never re-creates.

* ``AlterModelManagers`` on both models. State only.
* ``AlterField`` on ``auditaffectedmembership.audit``: the concrete ``audit_fk``
  column and the ``audit`` ``ForeignObject`` beside it are byte-identical between
  the retired ``organizations.OrganizationForeignKey`` and
  ``vinta_orgs.fields.OrganizationSafeForeignKey``; only the *spelling* of the
  join changes. ``sqlmigrate`` reports ``(no-op)``.
* ``AlterField`` on ``audit.affected_memberships``: ``through_fields`` moves from
  ``('audit_fk', 'membership')`` to ``('audit', 'membership')`` so the first hop
  of the many-to-many joins on ``(audit_fk, organization)`` rather than on the
  key alone -- the related manager a many-to-many builds is *not*
  organization-scoped, so nothing else would put the organization back into the
  ``ON`` clause. Same two columns, so ``sqlmigrate`` reports ``(no-op)``.
* ``AlterField`` on each ``organization`` foreign key: ``db_index=False`` plus
  the loss of ``related_name='+'`` and the help text. ``sqlmigrate`` confirms the
  only index dropped is the foreign key's own single-column one, which is a
  prefix of the ``(organization, id)`` index added below.
* ``AddIndex`` of ``(organization, id)`` on both models, contributed by the
  package's ``class_prepared`` receiver.

**No constraint is at risk here.** Django's ``_alter_field`` drops every
non-``Meta.indexes`` index whose columns are exactly ``[organization_id]`` and
excludes ``Meta.indexes`` names but *not* ``Meta.constraints`` names -- the
same gap that once silently dropped ``bookingpolicy_uniq_org_default`` on
another model. Neither model here
declares a single-column constraint or index over ``organization``:
``AuditAffectedMembership``'s ``uniq_audit_membership`` is over
``(audit_fk, membership_user_id)`` and ``auditaffected_org_member_idx`` is over
``(organization, membership_user_id)``. ``sqlmigrate`` emits exactly two
``DROP INDEX`` statements, both the foreign keys' own, and two matching
``CREATE INDEX``.

**Lock audit.** Every ``AlterField`` on a foreign key drops and re-adds the
column's ``FOREIGN KEY`` constraint with an identical definition, taking
``ACCESS EXCLUSIVE`` on the table for the length of the transaction, and the
index drop/create pairs are not ``CONCURRENTLY``. Deliberate and consistent with
``calendar_integration/migrations/0045``'s precedent: the operations are already
transactional and interdependent, and this project is pre-launch with no
production data.
"""

# ``to_fields=(None, 'organization')`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not. Same suppression, same
# reason, as ``calendar_integration/migrations/0045``.
# mypy: disable-error-code="arg-type"

# Generated by Django 6.0.5 on 2026-08-12 23:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.ORGANIZATION_MEMBERSHIP_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='audit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='auditaffectedmembership',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='audit',
            name='affected_memberships',
            field=models.ManyToManyField(blank=True, related_name='+', through='audit.AuditAffectedMembership', through_fields=('audit', 'membership'), to=settings.ORGANIZATION_MEMBERSHIP_MODEL),
        ),
        migrations.AlterField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='auditaffectedmembership',
            name='audit',
            field=models.ForeignObject(editable=False, from_fields=('audit_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='affected_membership_links', to='audit.audit', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='auditaffectedmembership',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'id'], name='audit_audit_organiz_3a4105_idx'),
        ),
        migrations.AddIndex(
            model_name='auditaffectedmembership',
            index=models.Index(fields=['organization', 'id'], name='audit_audit_organiz_31ae98_idx'),
        ),
    ]
