# Generated by Django 5.2.2 on 2025-09-04 04:30

import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import model_utils.fields
import calendar_integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeBulkModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('modification_start_date', models.DateTimeField(help_text='The date from which the modification applies')),
                ('is_bulk_cancelled', models.BooleanField(default=False, help_text='True if all occurrences from this date are cancelled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableTimeRecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('exception_date', models.DateTimeField(help_text='The original start time of the occurrence being excepted')),
                ('is_cancelled', models.BooleanField(default=False, help_text="True if this occurrence is cancelled, False if it's modified")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('start_time_tz_unaware', models.DateTimeField()),
                ('end_time_tz_unaware', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50, validators=[calendar_integration.models.validate_not_empty])),
                ('recurrence_id', models.DateTimeField(blank=True, help_text='For recurring instances, this identifies which occurrence this is', null=True)),
                ('is_recurring_exception', models.BooleanField(default=False, help_text='True if this object is an exception to the recurrence rule (modified occurrence)')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedTimeBulkModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('modification_start_date', models.DateTimeField(help_text='The date from which the modification applies')),
                ('is_bulk_cancelled', models.BooleanField(default=False, help_text='True if all occurrences from this date are cancelled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedTimeRecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('exception_date', models.DateTimeField(help_text='The original start time of the occurrence being excepted')),
                ('is_cancelled', models.BooleanField(default=False, help_text="True if this occurrence is cancelled, False if it's modified")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[('internal', 'Internal Calendar'), ('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook Calendar'), ('apple', 'Apple Calendar'), ('ics', 'ICS')], default='internal', max_length=255)),
                ('calendar_type', models.CharField(choices=[('personal', 'Personal Calendar'), ('resource', 'Resource Calendar'), ('virtual', 'Virtual Calendar'), ('bundle', 'Bundle Calendar')], default='personal', help_text='The type of calendar. Personal calendars are for individual use, resource calendars are for shared resources, and virtual calendars are for online meetings or events.', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text="The maximum number of attendees that can be accommodated in this calendar's events. This is only applicable for resource calendars.", null=True)),
                ('manage_available_windows', models.BooleanField(default=False, help_text="If true, this calendar can manage its own available time windows. If not, it will use the available time windows of the external calendar it's attached to.")),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('start_time_tz_unaware', models.DateTimeField()),
                ('end_time_tz_unaware', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50, validators=[calendar_integration.models.validate_not_empty])),
                ('recurrence_id', models.DateTimeField(blank=True, help_text='For recurring instances, this identifies which occurrence this is', null=True)),
                ('is_recurring_exception', models.BooleanField(default=False, help_text='True if this object is an exception to the recurrence rule (modified occurrence)')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_bundle_primary', models.BooleanField(default=False, help_text='True if this is the primary event in a bundle (hosts the actual event in external providers)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarOrganizationResourcesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='not_started', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this calendar is the default calendar for the user in this organization. This means that events created by the user will be added to this calendar by default.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('next_sync_token', models.CharField(blank=True, max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('should_update_events', models.BooleanField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='not_started', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildrenCalendarRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('is_primary', models.BooleanField(default=False, help_text='True if this child calendar is the primary calendar for the bundle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventBulkModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('modification_start_date', models.DateTimeField(help_text='The date from which the modification applies')),
                ('is_bulk_cancelled', models.BooleanField(default=False, help_text='True if all occurrences from this date are cancelled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventExternalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('exception_date', models.DateTimeField(help_text='The original start time of the occurrence being excepted')),
                ('is_cancelled', models.BooleanField(default=False, help_text="True if this occurrence is cancelled, False if it's modified")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('email', models.EmailField(max_length=254)),
                ('audience', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('private_key_id', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('private_key', encrypted_fields.fields.EncryptedCharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], help_text='How often the event repeats (DAILY, WEEKLY, MONTHLY, YEARLY)', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='The interval between each frequency iteration (e.g., every 2 weeks)')),
                ('count', models.PositiveIntegerField(blank=True, help_text='Number of occurrences after which the recurrence ends', null=True)),
                ('until', models.DateTimeField(blank=True, help_text='The date and time until which the recurrence is valid', null=True)),
                ('by_weekday', models.CharField(blank=True, help_text="Comma-separated list of weekdays (e.g., 'MO,WE,FR')", max_length=100)),
                ('by_month_day', models.CharField(blank=True, help_text="Comma-separated list of month days (e.g., '1,15,-1' for 1st, 15th, last day)", max_length=100)),
                ('by_month', models.CharField(blank=True, help_text='Comma-separated list of months (1-12)', max_length=50)),
                ('by_year_day', models.CharField(blank=True, help_text='Comma-separated list of year days (1-366 or -366 to -1)', max_length=100)),
                ('by_week_number', models.CharField(blank=True, help_text='Comma-separated list of week numbers (1-53 or -53 to -1)', max_length=100)),
                ('by_hour', models.CharField(blank=True, help_text='Comma-separated list of hours (0-23)', max_length=100)),
                ('by_minute', models.CharField(blank=True, help_text='Comma-separated list of minutes (0-59)', max_length=200)),
                ('by_second', models.CharField(blank=True, help_text='Comma-separated list of seconds (0-59)', max_length=200)),
                ('week_start', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', help_text='First day of the week', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('start_time_tz_unaware', models.DateTimeField()),
                ('end_time_tz_unaware', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50, validators=[calendar_integration.models.validate_not_empty])),
                ('recurrence_id', models.DateTimeField(blank=True, help_text='For recurring instances, this identifies which occurrence this is', null=True)),
                ('is_recurring_exception', models.BooleanField(default=False, help_text='True if this object is an exception to the recurrence rule (modified occurrence)')),
                ('bulk_modification_parent', models.ForeignObject(editable=False, from_fields=['bulk_modification_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.availabletime', to_fields=['id', 'organization_id'])),
                ('bulk_modification_parent_fk', models.ForeignKey(blank=True, help_text='If this is a continuation of a split series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications_fk_rel', to='calendar_integration.availabletime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
