# Generated by Django 5.2.2 on 2025-09-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_integration', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=['parent_recurring_object_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.availabletime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='parent_recurring_object_fk',
            field=models.ForeignKey(blank=True, help_text='If this is an instance of a recurring object, points to the parent object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances_fk_rel', to='calendar_integration.availabletime'),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=['modified_continuation_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.availabletimebulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='modified_continuation_fk',
            field=models.ForeignKey(blank=True, help_text='New recurring object for modified series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_fk_rel', to='calendar_integration.availabletimebulkmodification'),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=['original_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.availabletimebulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='original_parent_fk',
            field=models.ForeignKey(blank=True, help_text='Original recurring object before split', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_fk_rel', to='calendar_integration.availabletimebulkmodification'),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='parent_available_time',
            field=models.ForeignObject(editable=False, from_fields=['parent_available_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.availabletime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletimebulkmodification',
            name='parent_available_time_fk',
            field=models.ForeignKey(help_text='The recurring available time this bulk modification applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records_fk_rel', to='calendar_integration.availabletime'),
        ),
        migrations.AddField(
            model_name='availabletimerecurrenceexception',
            name='modified_available_time',
            field=models.ForeignObject(editable=False, from_fields=['modified_available_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.availabletime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletimerecurrenceexception',
            name='modified_available_time_fk',
            field=models.ForeignKey(blank=True, help_text='If the occurrence is modified (not cancelled), points to the modified event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for_fk_rel', to='calendar_integration.availabletime'),
        ),
        migrations.AddField(
            model_name='availabletimerecurrenceexception',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='availabletimerecurrenceexception',
            name='parent_available_time',
            field=models.ForeignObject(editable=False, from_fields=['parent_available_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.availabletime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletimerecurrenceexception',
            name='parent_available_time_fk',
            field=models.ForeignKey(help_text='The recurring event this exception applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions_fk_rel', to='calendar_integration.availabletime'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bulk_modification_parent',
            field=models.ForeignObject(editable=False, from_fields=['bulk_modification_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.blockedtime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bulk_modification_parent_fk',
            field=models.ForeignKey(blank=True, help_text='If this is a continuation of a split series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications_fk_rel', to='calendar_integration.blockedtime'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=['parent_recurring_object_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.blockedtime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='parent_recurring_object_fk',
            field=models.ForeignKey(blank=True, help_text='If this is an instance of a recurring object, points to the parent object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances_fk_rel', to='calendar_integration.blockedtime'),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=['modified_continuation_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.blockedtimebulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='modified_continuation_fk',
            field=models.ForeignKey(blank=True, help_text='New recurring object for modified series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_fk_rel', to='calendar_integration.blockedtimebulkmodification'),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=['original_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.blockedtimebulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='original_parent_fk',
            field=models.ForeignKey(blank=True, help_text='Original recurring object before split', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_fk_rel', to='calendar_integration.blockedtimebulkmodification'),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='parent_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=['parent_blocked_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.blockedtime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtimebulkmodification',
            name='parent_blocked_time_fk',
            field=models.ForeignKey(help_text='The recurring blocked time this bulk modification applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records_fk_rel', to='calendar_integration.blockedtime'),
        ),
        migrations.AddField(
            model_name='blockedtimerecurrenceexception',
            name='modified_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=['modified_blocked_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.blockedtime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtimerecurrenceexception',
            name='modified_blocked_time_fk',
            field=models.ForeignKey(blank=True, help_text='If the occurrence is modified (not cancelled), points to the modified event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for_fk_rel', to='calendar_integration.blockedtime'),
        ),
        migrations.AddField(
            model_name='blockedtimerecurrenceexception',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='blockedtimerecurrenceexception',
            name='parent_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=['parent_blocked_time_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.blockedtime', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtimerecurrenceexception',
            name='parent_blocked_time_fk',
            field=models.ForeignKey(help_text='The recurring event this exception applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions_fk_rel', to='calendar_integration.blockedtime'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_times', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_calendar_fk',
            field=models.ForeignKey(blank=True, help_text='If this blocked time was created through a bundle calendar, references the bundle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_times_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_times_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bulk_modification_parent',
            field=models.ForeignObject(editable=False, from_fields=['bulk_modification_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bulk_modification_parent_fk',
            field=models.ForeignKey(blank=True, help_text='If this is a continuation of a split series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_calendar_fk',
            field=models.ForeignKey(blank=True, help_text='If this event was created through a bundle calendar, references the bundle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=['bundle_primary_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_representations', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_primary_event_fk',
            field=models.ForeignKey(blank=True, help_text='For bundle representations, points to the primary event that hosts the actual external event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_representations_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=['parent_recurring_object_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parent_recurring_object_fk',
            field=models.ForeignKey(blank=True, help_text='If this is an instance of a recurring object, points to the parent object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=['bundle_primary_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_time_representations', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_primary_event_fk',
            field=models.ForeignKey(blank=True, help_text='For bundle representations, points to the primary event that this blocked time represents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_time_representations_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarorganizationresourcesimport',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calendarownership',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarownership',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarownership',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
    ]
