# Generated by Django 5.2.2 on 2025-08-24 23:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0002_add_recurring_events_functions'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calendar_type',
            field=models.CharField(choices=[('personal', 'Personal Calendar'), ('resource', 'Resource Calendar'), ('virtual', 'Virtual Calendar'), ('bundle', 'Bundle Calendar')], default='personal', help_text='The type of calendar. Personal calendars are for individual use, resource calendars are for shared resources, and virtual calendars are for online meetings or events.', max_length=50),
        ),
        migrations.CreateModel(
            name='ChildrenCalendarRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('bundle_calendar', models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='bundle_relationships', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('bundle_calendar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_relationships_fk_rel', to='calendar_integration.calendar')),
                ('child_calendar', models.ForeignObject(editable=False, from_fields=['child_calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='bundle_children_relatioships', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('child_calendar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_children_relatioships_fk_rel', to='calendar_integration.calendar')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='bundles', through='calendar_integration.ChildrenCalendarRelationship', through_fields=('bundle_calendar', 'child_calendar'), to='calendar_integration.calendar'),
        ),
    ]
