# Generated by Django 5.2.2 on 2025-09-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_integration', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_ownerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='calendars', through='calendar_integration.CalendarOwnership', through_fields=('calendar_fk', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarsync',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarsync',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncs_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarsync',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='bundle_relationships', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='bundle_calendar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_relationships_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='child_calendar',
            field=models.ForeignObject(editable=False, from_fields=['child_calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='bundle_children_relationships', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='child_calendar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_children_relationships_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='bundle_children',
            field=models.ManyToManyField(blank=True, through='calendar_integration.ChildrenCalendarRelationship', through_fields=('bundle_calendar', 'child_calendar'), to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', through='calendar_integration.EventAttendance', through_fields=('event', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=['modified_continuation_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.eventbulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='modified_continuation_fk',
            field=models.ForeignKey(blank=True, help_text='New recurring object for modified series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_fk_rel', to='calendar_integration.eventbulkmodification'),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=['original_parent_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.eventbulkmodification', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='original_parent_fk',
            field=models.ForeignKey(blank=True, help_text='Original recurring object before split', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_fk_rel', to='calendar_integration.eventbulkmodification'),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='parent_event',
            field=models.ForeignObject(editable=False, from_fields=['parent_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventbulkmodification',
            name='parent_event_fk',
            field=models.ForeignKey(help_text='The recurring event this bulk modification applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventexternalattendance',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventexternalattendance',
            name='event_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventexternalattendance',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='eventrecurrenceexception',
            name='modified_event',
            field=models.ForeignObject(editable=False, from_fields=['modified_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventrecurrenceexception',
            name='modified_event_fk',
            field=models.ForeignKey(blank=True, help_text='If the occurrence is modified (not cancelled), points to the modified event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventrecurrenceexception',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='eventrecurrenceexception',
            name='parent_event',
            field=models.ForeignObject(editable=False, from_fields=['parent_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventrecurrenceexception',
            name='parent_event_fk',
            field=models.ForeignKey(help_text='The recurring event this exception applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='externalattendee',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='eventexternalattendance',
            name='external_attendee',
            field=models.ForeignObject(editable=False, from_fields=['external_attendee_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances', to='calendar_integration.externalattendee', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='eventexternalattendance',
            name='external_attendee_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances_fk_rel', to='calendar_integration.externalattendee'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_attendees',
            field=models.ManyToManyField(related_name='calendar_events', to='calendar_integration.externalattendee'),
        ),
        migrations.AddField(
            model_name='googlecalendarserviceaccount',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_service_accounts', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='googlecalendarserviceaccount',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_service_accounts_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='googlecalendarserviceaccount',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.ForeignObject(editable=False, from_fields=['recurrence_rule_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=['id', 'organization_id'], unique=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_rule_fk',
            field=models.OneToOneField(blank=True, help_text='The recurrence rule for this object. If set, this object is recurring.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance_fk_rel', to='calendar_integration.recurrencerule'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='recurrence_rule',
            field=models.ForeignObject(editable=False, from_fields=['recurrence_rule_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=['id', 'organization_id'], unique=True),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='recurrence_rule_fk',
            field=models.OneToOneField(blank=True, help_text='The recurrence rule for this object. If set, this object is recurring.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance_fk_rel', to='calendar_integration.recurrencerule'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='recurrence_rule',
            field=models.ForeignObject(editable=False, from_fields=['recurrence_rule_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=['id', 'organization_id'], unique=True),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='recurrence_rule_fk',
            field=models.OneToOneField(blank=True, help_text='The recurrence rule for this object. If set, this object is recurring.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance_fk_rel', to='calendar_integration.recurrencerule'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='calendar_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='event_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='organization',
            field=models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='allocated_events', through='calendar_integration.ResourceAllocation', through_fields=('event', 'calendar'), to='calendar_integration.calendar'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('external_id', 'provider', 'organization_id')},
        ),
        migrations.AlterUniqueTogether(
            name='blockedtime',
            unique_together={('calendar_fk_id', 'external_id')},
        ),
    ]
