# Generated by Django 5.2.2 on 2025-08-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0003_alter_calendar_calendar_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='children',
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_times', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_calendar_fk',
            field=models.ForeignKey(blank=True, help_text='If this blocked time was created through a bundle calendar, references the bundle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_times_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=['bundle_primary_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_time_representations', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='bundle_primary_event_fk',
            field=models.ForeignKey(blank=True, help_text='For bundle representations, points to the primary event that this blocked time represents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_time_representations_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='bundle_children',
            field=models.ManyToManyField(blank=True, through='calendar_integration.ChildrenCalendarRelationship', through_fields=('bundle_calendar', 'child_calendar'), to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=['bundle_calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events', to='calendar_integration.calendar', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_calendar_fk',
            field=models.ForeignKey(blank=True, help_text='If this event was created through a bundle calendar, references the bundle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events_fk_rel', to='calendar_integration.calendar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=['bundle_primary_event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_representations', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bundle_primary_event_fk',
            field=models.ForeignKey(blank=True, help_text='For bundle representations, points to the primary event that hosts the actual external event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_representations_fk_rel', to='calendar_integration.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_bundle_primary',
            field=models.BooleanField(default=False, help_text='True if this is the primary event in a bundle (hosts the actual event in external providers)'),
        ),
        migrations.AddField(
            model_name='childrencalendarrelationship',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='True if this child calendar is the primary calendar for the bundle'),
        ),
    ]
