# Generated by Django 5.2.2 on 2025-08-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0004_remove_calendar_children_blockedtime_bundle_calendar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='parent_event',
            new_name='parent_recurring_object',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='parent_event_fk',
            new_name='parent_recurring_object_fk',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='is_recurring_exception',
            field=models.BooleanField(default=False, help_text='True if this object is an exception to the recurrence rule (modified occurrence)'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_id',
            field=models.DateTimeField(blank=True, help_text='For recurring instances, this identifies which occurrence this is', null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.ForeignObject(editable=False, from_fields=('recurrence_rule_fk', 'organization_id'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule_instance', to='calendar_integration.recurrencerule', to_fields=('id', 'organization_id'), unique=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule_fk',
            field=models.OneToOneField(blank=True, help_text='The recurrence rule for this object. If set, this object is recurring.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule_fk_rel', to='calendar_integration.recurrencerule'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='parent_recurring_object_fk',
            field=models.ForeignKey(blank=True, help_text='If this is an instance of a recurring object, points to the parent object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances_fk_rel', to='calendar_integration.calendarevent'),
        ),
    ]
