# Generated by Django 5.2.2 on 2025-09-08 18:17

import calendar_integration.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0005_add_timezone_aware_fields'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventUpdateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('token', models.CharField(db_index=True, default=calendar_integration.models.generate_unique_id, max_length=255, unique=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('event', models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_tokens', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id'])),
                ('event_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_tokens_fk_rel', to='calendar_integration.calendarevent')),
                ('external_attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_update_tokens', to='calendar_integration.externalattendee')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_update_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarEventUpdateTokenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('permission', models.CharField(choices=[('attendees', 'Update Attendees'), ('self_rsvp', 'Update Self RSVP'), ('details', 'Update Event Details'), ('cancel', 'Cancel Event'), ('reschedule', 'Reschedule Event')], max_length=100)),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('token', models.ForeignObject(editable=False, from_fields=['token_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='calendar_integration.calendareventupdatetoken', to_fields=['id', 'organization_id'])),
                ('token_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_fk_rel', to='calendar_integration.calendareventupdatetoken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
