# Generated by Django 5.2.2 on 2025-09-08 18:17

from calendar_integration.constants import EventManagementPermissions
import calendar_integration.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0005_add_timezone_aware_fields'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='accepts_public_scheduling',
            field=models.BooleanField(default=False, help_text='If true, this event can be scheduled by external users through public scheduling links.'),
        ),
        migrations.CreateModel(
            name='CalendarManagementToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('token_hash', models.TextField()),
                ('used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('event', models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id'])),
                ('event_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens_fk_rel', to='calendar_integration.calendarevent')),
                ('calendar', models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('calendar_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens_fk_rel', to='calendar_integration.calendar')),
                ('external_attendee', models.ForeignObject(editable=False, from_fields=('external_attendee_fk', 'organization_id'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_management_tokens', to='calendar_integration.externalattendee', to_fields=('id', 'organization_id'))),
                ('external_attendee_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_management_tokens_fk_rel', to='calendar_integration.externalattendee')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_management_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarManagementTokenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('permission', models.CharField(choices=EventManagementPermissions.choices, max_length=100)),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('token', models.ForeignObject(editable=False, from_fields=['token_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='calendar_integration.calendarmanagementtoken', to_fields=['id', 'organization_id'])),
                ('token_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_fk_rel', to='calendar_integration.calendarmanagementtoken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
