# Generated by Django 5.2.2 on 2025-10-11 12:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0006_calendareventupdatetoken_and_more'),
        ('organizations', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('provider', models.CharField(choices=[('internal', 'Internal Calendar'), ('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook Calendar'), ('apple', 'Apple Calendar'), ('ics', 'ICS')], max_length=50)),
                ('external_subscription_id', models.CharField(help_text="Provider's subscription ID", max_length=255)),
                ('external_resource_id', models.CharField(help_text="Provider's resource/calendar ID", max_length=255)),
                ('callback_url', models.URLField(max_length=500)),
                ('channel_id', models.CharField(blank=True, default='', help_text='Google Calendar channel ID', max_length=255)),
                ('resource_uri', models.CharField(blank=True, default='', help_text='Google Calendar resource URI', max_length=500)),
                ('verification_token', models.CharField(blank=True, default='', help_text='Webhook verification token', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When subscription expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('calendar', models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('calendar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions_fk_rel', to='calendar_integration.calendar')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('provider', models.CharField(choices=[('internal', 'Internal Calendar'), ('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook Calendar'), ('apple', 'Apple Calendar'), ('ics', 'ICS')], max_length=50)),
                ('event_type', models.CharField(help_text='Type of webhook event (created, updated, deleted)', max_length=100)),
                ('external_calendar_id', models.CharField(help_text='External calendar ID from webhook', max_length=255)),
                ('external_event_id', models.CharField(blank=True, default='', help_text='External event ID if available', max_length=255)),
                ('raw_payload', models.JSONField(help_text='Full webhook payload for debugging')),
                ('headers', models.JSONField(default=dict, help_text='Request headers')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=50)),
                ('calendar_sync', models.ForeignObject(editable=False, from_fields=['calendar_sync_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_sync_set', to='calendar_integration.calendarsync', to_fields=['id', 'organization_id'])),
                ('calendar_sync_fk', models.ForeignKey(blank=True, help_text='Associated calendar sync if triggered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_sync_fk_rel', to='calendar_integration.calendarsync')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('subscription', models.ForeignObject(editable=False, from_fields=['subscription_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='calendar_integration.calendarwebhooksubscription', to_fields=['id', 'organization_id'])),
                ('subscription_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events_fk_rel', to='calendar_integration.calendarwebhooksubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='calendarwebhooksubscription',
            index=models.Index(fields=['provider', 'external_subscription_id'], name='calendar_in_provide_88ad23_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhooksubscription',
            index=models.Index(fields=['expires_at'], name='calendar_in_expires_46769c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhooksubscription',
            index=models.Index(fields=['is_active', 'created'], name='calendar_in_is_acti_07fb98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarwebhooksubscription',
            unique_together={('organization', 'calendar', 'provider')},
        ),
        migrations.AddIndex(
            model_name='calendarwebhookevent',
            index=models.Index(fields=['provider', 'created'], name='calendar_in_provide_d5534e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhookevent',
            index=models.Index(fields=['processing_status', 'created'], name='calendar_in_process_b63385_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhookevent',
            index=models.Index(fields=['external_calendar_id', 'created'], name='calendar_in_externa_e7d2af_idx'),
        ),
    ]
