# Generated by Django 5.2.2 on 2025-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0007_add_webhook_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarwebhooksubscription',
            index=models.Index(
                fields=['organization', 'provider', 'external_subscription_id', 'is_active'],
                name='cal_webhook_sub_lookup_idx'
            ),
        ),
    ]
