# Generated by Django 5.2.2 on 2025-10-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0008_add_webhook_subscription_lookup_index'),
    ]

    operations = [
        # Remove the old unique constraint that uses ForeignObject field
        migrations.AlterUniqueTogether(
            name='calendarwebhooksubscription',
            unique_together=set(),
        ),
        # Add the new unique constraint that uses the concrete field
        migrations.AlterUniqueTogether(
            name='calendarwebhooksubscription',
            unique_together={('organization', 'calendar_fk', 'provider')},
        ),
    ]
