# Generated by Django 6.0.5 on 2026-06-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendar_integration",
            "0010_calendargroup_calendarevent_calendar_group_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="is_active",
            field=models.BooleanField(
                db_default=True,
                db_index=True,
                default=True,
                help_text="Whether this calendar is active. Inactive calendars are hidden from default list/detail queries. Use DELETE /calendar/{id}/ to soft-disable (sets this to False) instead of deleting the row. Opt-in to see disabled calendars via ?include_inactive=true. Default True keeps every existing read unchanged.",
            ),
        ),
    ]
