# Generated by Django 6.0.5 on 2026-06-06 13:29

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0011_calendar_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarserviceaccount',
            name='private_key',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
