# Generated by Django 6.0.5 on 2026-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0012_alter_googlecalendarserviceaccount_private_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlecalendarserviceaccount",
            name="audience",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
