# Generated by Django 6.0.5 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0013_alter_googlecalendarserviceaccount_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="sync_enabled",
            field=models.BooleanField(
                db_default=True,
                db_index=True,
                default=True,
                help_text="Whether this calendar's events are pulled from the external provider. Set to False to skip syncing calendars that aren't useful for scheduling — holidays, birthdays, organization-wide events, etc. When False, no new CalendarSync is requested for this calendar (including webhook- and import-triggered syncs); previously synced events are left untouched. Default True keeps existing calendars syncing as before.",
            ),
        ),
    ]
