# Generated by Django 6.0.5 on 2026-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0014_calendar_sync_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarsync",
            name="trigger_source",
            field=models.CharField(
                choices=[
                    ("import", "Import"),
                    ("manual", "Manual"),
                    ("webhook", "Webhook"),
                    ("admin", "Admin"),
                ],
                default="manual",
                help_text="What kicked off this sync: import, manual, webhook, or admin.",
                max_length=20,
            ),
        ),
    ]
