# Generated by Django 6.0.5 on 2026-06-09 12:30

from django.db import migrations, models


def backfill_visibility_from_is_active(apps, schema_editor):
    Calendar = apps.get_model("calendar_integration", "Calendar")
    Calendar.objects.filter(is_active=False).update(visibility="inactive")
    # Rows with is_active=True already have visibility="active" via db_default.


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0016_recurring_occurrences_overlap"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("unlisted", "Unlisted"),
                    ("inactive", "Inactive"),
                ],
                db_default="active",
                db_index=True,
                default="active",
                help_text=(
                    "Controls how this calendar appears in queries. "
                    "active: listed and available for booking (default). "
                    "unlisted: hidden from listing/booking queries but still synced for conflict detection; "
                    "survives re-import so user opt-out is preserved. "
                    "inactive: soft-deleted, hidden from all queries and not synced. "
                    "Use DELETE /calendars/{id}/ to transition to inactive instead of hard-deleting."
                ),
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_visibility_from_is_active,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="is_active",
        ),
    ]
