# Generated by Django 6.0.5 on 2026-06-13 17:19
# Phase 1: Rename audience → admin_email field on GoogleCalendarServiceAccount.
# This migration:
# 1. Renames the column (low-cost metadata-only operation in Postgres).
# 2. Alters the field to EmailField with max_length=255 (keeps existing column width
#    unchanged as varchar(255)), adds help_text documenting DWD use. This is a
#    catalog-only change (no row-scan required on Postgres).
# Both operations are safe on the low-traffic service-account table.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0017_calendar_visibility_replaces_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlecalendarserviceaccount",
            old_name="audience",
            new_name="admin_email",
        ),
        migrations.AlterField(
            model_name="googlecalendarserviceaccount",
            name="admin_email",
            field=models.EmailField(
                blank=True,
                help_text=(
                    "Google Workspace super-admin email used as the DWD impersonation subject. "
                    "The service account must have domain-wide delegation granted for the Admin SDK "
                    "and Calendar API scopes in the Google Admin Console."
                ),
                max_length=255,
            ),
        ),
    ]
