# Generated by Django 6.0.5 on 2026-06-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0018_rename_audience_admin_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlecalendarserviceaccount",
            name="public_key",
        ),
    ]
