# Generated by Django 6.0.5 on 2026-06-18 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0019_remove_googlecalendarserviceaccount_public_key"),
        ("public_api", "0006_alter_resourceaccess_resource_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarmanagementtoken",
            name="calendar_group",
            field=models.ForeignObject(
                editable=False,
                from_fields=["calendar_group_fk", "organization_id"],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="management_tokens",
                to="calendar_integration.calendargroup",
                to_fields=["id", "organization_id"],
            ),
        ),
        migrations.AddField(
            model_name="calendarmanagementtoken",
            name="calendar_group_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this token is scoped to a calendar group (for group booking codes). Mutually exclusive with the ``calendar`` scope for booking codes.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="management_tokens_fk_rel",
                to="calendar_integration.calendargroup",
            ),
        ),
        migrations.AddField(
            model_name="calendarmanagementtoken",
            name="consumed_source_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the client that consumed (used) this token.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarmanagementtoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, the token is invalid after this datetime (UTC).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarmanagementtoken",
            name="minted_by_system_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The SystemUser (org token) that minted this booking code, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minted_management_tokens",
                to="public_api.systemuser",
            ),
        ),
    ]
