# Generated by Django 6.0.5 on 2026-06-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0020_booking_code_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendargroup',
            name='accepts_public_scheduling',
            field=models.BooleanField(default=False, help_text='If true, this group can be booked by external users through public scheduling links without a scheduling code. If false (default), the group is restricted: booking requires a token or a single-use scheduling code.'),
        ),
    ]
