# Generated by Django 6.0.5 on 2026-06-20 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0021_calendargroup_accepts_public_scheduling'),
        ('organizations', '0011_organizationbranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarownership',
            name='membership',
            field=models.ForeignObject(editable=False, from_fields=['membership_user_id', 'organization_id'], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_ownerships', to='organizations.organizationmembership', to_fields=['user_id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarownership',
            name='membership_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='calendarownership',
            index=models.Index(fields=['organization', 'membership_user_id'], name='calownership_org_member_idx'),
        ),
    ]
