# Generated by Django 6.0.5 on 2026-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0023_backfill_calendarownership_membership_user_id'),
        ('organizations', '0011_organizationbranding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='users',
        ),
        migrations.AddField(
            model_name='calendar',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='calendars', through='calendar_integration.CalendarOwnership', through_fields=('calendar_fk', 'membership'), to='organizations.organizationmembership'),
        ),
    ]
