# Generated by Django 6.0.5 on 2026-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """Phase 2b cutover (schema half): drop CalendarOwnership.user, add partial unique.

    - ``RemoveField(user)`` drops the legacy ``user_id`` column and its DB FK
      constraint. CalendarOwnership is low-volume, so the brief ACCESS EXCLUSIVE
      metadata lock of a column drop is acceptable; the storage reclaim happens at
      the next VACUUM, not inline.
    - ``AddConstraint(calownership_uniq_cal_member)`` creates a *partial* unique
      index on ``(calendar_fk, membership_user_id) WHERE membership_user_id IS NOT
      NULL``, so a calendar cannot have two ownerships for the same member while
      multiple NULL (orphan) rows per calendar remain allowed.

    The raw-SQL composite PROTECT FK lives in the next migration (0026), which is
    ``atomic = False`` so its NOT VALID / VALIDATE steps don't share one
    long-locking transaction. Reverse drops the constraint then re-adds the
    column (Django default reverse).
    """

    dependencies = [
        ('calendar_integration', '0024_remove_calendar_users_calendar_memberships'),
        ('organizations', '0011_organizationbranding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarownership',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='calendarownership',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_user_id__isnull', False)), fields=('calendar_fk', 'membership_user_id'), name='calownership_uniq_cal_member'),
        ),
    ]
