# Generated by Django 6.0.5 on 2026-06-20 02:01

from django.db import migrations, models


# Forward: drop the legacy ``user_id`` column outright (the model no longer has
# the ``user`` field). Reverse: re-add ``user_id`` as a NULLABLE column and
# backfill it from ``membership_user_id`` so a roll-back on a populated table does
# not crash on a NOT NULL column with no default. We re-add the column nullable
# (not NOT NULL) because the original ``user`` FK was non-null and Django's
# auto-reverse of ``RemoveField`` would re-add a NOT NULL column with no default —
# which fails immediately on any existing row. Orphan rows (membership_user_id
# IS NULL) keep user_id = NULL on reverse, so the reverse is data-preserving for
# member-owned rows but cannot resurrect the original user_id of pre-existing
# orphans (their original value is gone after the forward drop).
DROP_USER_COLUMN = """
ALTER TABLE calendar_integration_calendarownership
  DROP COLUMN IF EXISTS user_id;
"""

READD_USER_COLUMN_NULLABLE_AND_BACKFILL = """
ALTER TABLE calendar_integration_calendarownership
  ADD COLUMN IF NOT EXISTS user_id integer NULL;
UPDATE calendar_integration_calendarownership
  SET user_id = membership_user_id
  WHERE membership_user_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    """Phase 2b cutover (schema half): drop CalendarOwnership.user, add partial unique.

    - The ``user`` field is removed from model state and the legacy ``user_id``
      column is dropped from the DB. CalendarOwnership is low-volume, so the brief
      ACCESS EXCLUSIVE metadata lock of a column drop is acceptable; the storage
      reclaim happens at the next VACUUM, not inline.
    - ``AddConstraint(calownership_uniq_cal_member)`` creates a *partial* unique
      index on ``(calendar_fk, membership_user_id) WHERE membership_user_id IS NOT
      NULL``, so a calendar cannot have two ownerships for the same member while
      multiple NULL (orphan) rows per calendar remain allowed.

    The raw-SQL composite PROTECT FK lives in the next migration (0026), which is
    ``atomic = False`` so its NOT VALID / VALIDATE steps don't share one
    long-locking transaction.

    Data-preserving reverse
    -----------------------
    The column drop is wrapped in ``SeparateDatabaseAndState`` so the model-state
    half is a plain ``RemoveField(user)`` (``makemigrations --check`` stays clean),
    while the database half is an explicit ``RunSQL`` whose reverse re-adds
    ``user_id`` as a **NULLABLE** column and backfills ``user_id =
    membership_user_id``. Django's auto-reverse of ``RemoveField`` would re-add a
    NOT NULL column with no default and crash on a populated table; the explicit
    nullable re-add + backfill avoids that. Member-owned rows recover their
    user_id on reverse; pre-existing orphan rows (membership_user_id IS NULL)
    cannot have their original user_id resurrected and stay NULL.
    """

    dependencies = [
        ('calendar_integration', '0024_remove_calendar_users_calendar_memberships'),
        ('organizations', '0011_organizationbranding'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='calendarownership',
                    name='user',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_USER_COLUMN,
                    reverse_sql=READD_USER_COLUMN_NULLABLE_AND_BACKFILL,
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendarownership',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_user_id__isnull', False)), fields=('calendar_fk', 'membership_user_id'), name='calownership_uniq_cal_member'),
        ),
    ]
