# Generated by Django 6.0.5 on 2026-06-20 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Phase 2b: switch the ``membership`` ForeignObject to ``on_delete=DO_NOTHING``.

    PROTECT delete semantics for ``CalendarOwnership.membership`` are enforced
    solely by the raw-SQL composite FK added in 0026 (``DEFERRABLE INITIALLY
    DEFERRED``). Carrying ``on_delete=PROTECT`` on the ForeignObject *as well* made
    Django's Python cascade collector raise ``ProtectedError`` eagerly — aborting
    even whole-object cascades (e.g. deleting an Organization, which CASCADEs to
    its memberships and ownerships in one transaction) where the DB-level deferred
    check would have allowed the commit. ``ForeignObject`` emits no DB constraint,
    so this ``AlterField`` only updates Django's model state / collector behaviour;
    it issues no DDL.
    """

    dependencies = [
        ('calendar_integration', '0026_calendarownership_membership_protect_fk'),
        ('organizations', '0011_organizationbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarownership',
            name='membership',
            field=models.ForeignObject(editable=False, from_fields=('membership_user_id', 'organization_id'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_ownerships', to='organizations.organizationmembership', to_fields=('user_id', 'organization_id')),
        ),
    ]
