# Generated by Django 6.0.5 on 2026-06-20 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_integration", "0027_alter_calendarownership_membership"),
        ("organizations", "0011_organizationbranding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendance",
            name="membership",
            field=models.ForeignObject(
                editable=False,
                from_fields=["membership_user_id", "organization_id"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_attendances",
                to="organizations.organizationmembership",
                to_fields=["user_id", "organization_id"],
            ),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="membership_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(
                fields=["organization", "membership_user_id"], name="evattend_org_member_idx"
            ),
        ),
    ]
