# Generated by Django 6.0.5 on 2026-06-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0029_backfill_eventattendance_membership_user_id'),
        ('organizations', '0011_organizationbranding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='attendees',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendee_memberships',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='calendar_integration.EventAttendance', through_fields=('event', 'membership'), to='organizations.organizationmembership'),
        ),
    ]
