# Generated by Django 6.0.5 on 2026-06-20 16:19

from django.db import migrations


# Forward: drop the legacy ``user_id`` column outright (the model no longer has the
# ``user`` field). Reverse: re-add ``user_id`` as a NULLABLE column and backfill it
# from ``membership_user_id`` so a roll-back on a populated table does not crash on a
# NOT NULL column with no default. We re-add the column nullable (not NOT NULL)
# because the original ``user`` FK was non-null and Django's auto-reverse of
# ``RemoveField`` would re-add a NOT NULL column with no default — which fails
# immediately on any existing row.
#
# LOSSY-FORWARD (accepted by the user):
# ``EventAttendance.user_id`` was NOT NULL today, but ``membership_user_id`` is NULL
# for *orphan* attendances (the attendee is not — or is no longer — a member of the
# event's organization). Dropping the ``user`` column PERMANENTLY discards the
# attendee identity of those orphan rows; their user_id cannot be resurrected on
# reverse (they keep user_id = NULL). Orphans were CSV-reported in the Phase 3
# backfill (migration 0029) before this drop. Member-owned rows recover their
# user_id on reverse via the ``membership_user_id`` backfill below.
DROP_USER_COLUMN = """
ALTER TABLE calendar_integration_eventattendance
  DROP COLUMN IF EXISTS user_id;
"""

READD_USER_COLUMN_NULLABLE_AND_BACKFILL = """
ALTER TABLE calendar_integration_eventattendance
  ADD COLUMN IF NOT EXISTS user_id integer NULL;
UPDATE calendar_integration_eventattendance
  SET user_id = membership_user_id
  WHERE membership_user_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    """Phase 4b cutover (schema half): drop EventAttendance.user.

    - The ``user`` field is removed from model state and the legacy ``user_id``
      column is dropped from the DB. EventAttendance is higher-volume than
      CalendarOwnership, but a column DROP is a brief metadata-only ACCESS
      EXCLUSIVE lock (no table rewrite, no per-row work); storage is reclaimed at
      the next VACUUM, not inline. The lock is acceptable.
    - **No unique constraint is added.** Unlike CalendarOwnership (Phase 2b),
      EventAttendance has no ``update_or_create`` keyed on ``(event, member)`` that
      needs one, and there is no pre-existing unique on ``(event, user)``. Adding a
      new partial unique on ``(event_fk, membership_user_id)`` could fail on
      pre-existing duplicate member attendances, so it is deliberately skipped.

    The raw-SQL composite PROTECT FK lives in the next migration (0032), which is
    ``atomic = False`` so its NOT VALID / VALIDATE steps don't share one
    long-locking transaction.

    Data-preserving (but orphan-lossy) reverse
    ------------------------------------------
    The column drop is wrapped in ``SeparateDatabaseAndState`` so the model-state
    half is a plain ``RemoveField(user)`` (``makemigrations --check`` stays clean),
    while the database half is an explicit ``RunSQL`` whose reverse re-adds
    ``user_id`` as a **NULLABLE** column and backfills ``user_id =
    membership_user_id``. Django's auto-reverse of ``RemoveField`` would re-add a
    NOT NULL column with no default and crash on a populated table; the explicit
    nullable re-add + backfill avoids that. Member-owned rows recover their user_id
    on reverse; orphan rows (membership_user_id IS NULL) cannot have their original
    user_id resurrected and stay NULL — the forward drop is lossy for orphans.
    """

    dependencies = [
        ('calendar_integration', '0030_remove_calendarevent_attendees_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='eventattendance',
                    name='user',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_USER_COLUMN,
                    reverse_sql=READD_USER_COLUMN_NULLABLE_AND_BACKFILL,
                ),
            ],
        ),
    ]
