# Generated by Django 6.0.5 on 2026-06-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0032_eventattendance_membership_protect_fk'),
        ('organizations', '0011_organizationbranding'),
        ('public_api', '0007_systemuser_scoped_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmanagementtoken',
            name='membership',
            field=models.ForeignObject(editable=False, from_fields=['membership_user_id', 'organization_id'], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_event_management_tokens', to='organizations.organizationmembership', to_fields=['user_id', 'organization_id']),
        ),
        migrations.AddField(
            model_name='calendarmanagementtoken',
            name='membership_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='calendarmanagementtoken',
            index=models.Index(fields=['organization', 'membership_user_id'], name='calmgmttoken_org_member_idx'),
        ),
    ]
