# Generated by Django 6.0.5 on 2026-06-20 17:06

from django.db import migrations


# Forward: drop the legacy ``user_id`` column outright (the model no longer has
# the ``user`` field). Reverse: re-add ``user_id`` as a NULLABLE column and
# backfill it from ``membership_user_id``.
#
# ``CalendarManagementToken.user`` was already NULLABLE (a token is for an internal
# ``user`` OR an ``external_attendee``), so re-adding the column nullable on reverse
# matches its original definition exactly. The reverse is data-preserving for
# member-backed tokens (``membership_user_id`` set → user_id recovered) and leaves
# null-membership tokens (external-attendee / orphan) with user_id = NULL — which is
# also their correct original value for external tokens. Pre-existing orphan tokens
# (a ``user`` that was set but is not a member of the org) cannot have their original
# user_id resurrected after the forward drop and stay NULL on reverse.
DROP_USER_COLUMN = """
ALTER TABLE calendar_integration_calendarmanagementtoken
  DROP COLUMN IF EXISTS user_id;
"""

READD_USER_COLUMN_NULLABLE_AND_BACKFILL = """
ALTER TABLE calendar_integration_calendarmanagementtoken
  ADD COLUMN IF NOT EXISTS user_id integer NULL;
UPDATE calendar_integration_calendarmanagementtoken
  SET user_id = membership_user_id
  WHERE membership_user_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    """Phase 6 cutover (schema half): drop CalendarManagementToken.user.

    - The ``user`` field is removed from model state and the legacy ``user_id``
      column is dropped from the DB. A column DROP is a brief metadata-only ACCESS
      EXCLUSIVE lock (no table rewrite, no per-row work); storage is reclaimed at
      the next VACUUM, not inline. The lock is acceptable.
    - **No unique constraint is added.** A member may legitimately hold multiple
      management tokens (calendar-level, event-level, distinct events), so there is
      no ``(scope, membership_user_id)`` upsert key that needs a partial unique, and
      adding one would reject valid duplicate member tokens.

    The raw-SQL composite PROTECT FK lives in the next migration (0036), which is
    ``atomic = False`` so its NOT VALID / VALIDATE steps don't share one
    long-locking transaction.

    Data-preserving reverse
    -----------------------
    The column drop is wrapped in ``SeparateDatabaseAndState`` so the model-state
    half is a plain ``RemoveField(user)`` (``makemigrations --check`` stays clean),
    while the database half is an explicit ``RunSQL`` whose reverse re-adds
    ``user_id`` as a **NULLABLE** column (matching its original nullable definition)
    and backfills ``user_id = membership_user_id``. Member-backed tokens recover
    their user_id on reverse; null-membership (external / orphan) tokens stay NULL.
    """

    dependencies = [
        ('calendar_integration', '0034_backfill_calendarmanagementtoken_membership_user_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='calendarmanagementtoken',
                    name='user',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=DROP_USER_COLUMN,
                    reverse_sql=READD_USER_COLUMN_NULLABLE_AND_BACKFILL,
                ),
            ],
        ),
    ]
