"""Phase 2 — Add ExternalEventChangeRequest model.

Class of operation: new table (CreateModel).

Lock / downtime audit
---------------------
``CreateModel`` takes an ``ACCESS EXCLUSIVE`` lock only on the new, empty table
itself. No existing tables are touched. Because the table does not exist yet,
the lock is instantaneous and carries zero downtime risk.

The partial unique index (``CREATE UNIQUE INDEX ... WHERE "status" = 'pending'``)
is built at table-creation time on an empty table — same lock, same rationale.

Reverse path
------------
``DeleteModel`` — drops the table and its indexes cleanly. The FK from
``ExternalEventChangeRequest.event_fk`` to ``CalendarEvent`` is removed as part
of the table drop; no orphaned objects are left behind.
"""

# Generated by Django 6.0.5 on 2026-06-21 12:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0036_calendarmanagementtoken_membership_protect_fk'),
        ('organizations', '0014_organization_external_event_update_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEventChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('kind', models.CharField(choices=[('update', 'Update'), ('delete', 'Delete')], max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('stale', 'Stale'), ('auto_undone', 'Auto-undone')], db_default='pending', default='pending', max_length=11)),
                ('provider', models.CharField(choices=[('internal', 'Internal Calendar'), ('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook Calendar'), ('apple', 'Apple Calendar'), ('ics', 'ICS')], max_length=50)),
                ('proposed_values', models.JSONField(default=dict, help_text='Proposed field values: title, description, start_time, end_time.')),
                ('proposed_payload', models.JSONField(default=dict, help_text='Raw provider payload that produced this request.')),
                ('retained_values', models.JSONField(default=dict, help_text='Snapshot of local field values before the change, used to undo on rejection.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('event', models.ForeignObject(editable=False, from_fields=['event_fk', 'organization_id'], on_delete=django.db.models.deletion.PROTECT, related_name='external_change_requests', to='calendar_integration.calendarevent', to_fields=['id', 'organization_id'])),
                ('event_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_change_requests_fk_rel', to='calendar_integration.calendarevent')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('resolved_by', models.ForeignObject(editable=False, from_fields=['resolved_by_user_id', 'organization_id'], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_external_change_requests', to='organizations.organizationmembership', to_fields=['user_id', 'organization_id'])),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('event_fk',), name='uniq_pending_change_request_per_event')],
            },
        ),
    ]
