# Generated by Django 6.0.5 on 2026-06-27 21:12

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0038_externaleventchangerequest_resolved_by_protect_fk'),
        ('organizations', '0014_organization_external_event_update_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('is_organization_default', models.BooleanField(default=False)),
                ('lead_time_seconds', models.PositiveIntegerField(default=0)),
                ('max_horizon_seconds', models.PositiveIntegerField(default=0)),
                ('buffer_before_seconds', models.PositiveIntegerField(default=0)),
                ('buffer_after_seconds', models.PositiveIntegerField(default=0)),
                ('membership_user_id', models.BigIntegerField(blank=True, null=True)),
                ('calendar', models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('calendar_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies_fk_rel', to='calendar_integration.calendar')),
                ('calendar_group', models.ForeignObject(editable=False, from_fields=['calendar_group_fk', 'organization_id'], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='calendar_integration.calendargroup', to_fields=['id', 'organization_id'])),
                ('calendar_group_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies_fk_rel', to='calendar_integration.calendargroup')),
                ('membership', models.ForeignObject(editable=False, from_fields=['membership_user_id', 'organization_id'], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking_policies', to='organizations.organizationmembership', to_fields=['user_id', 'organization_id'])),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'calendar_fk'], name='bookingpolicy_org_cal_idx'), models.Index(fields=['organization', 'membership_user_id'], name='bookingpolicy_org_member_idx'), models.Index(fields=['organization', 'calendar_group_fk'], name='bookingpolicy_org_group_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('calendar_fk__isnull', False), ('calendar_group_fk__isnull', True), ('is_organization_default', False), ('membership_user_id__isnull', True)), models.Q(('calendar_fk__isnull', True), ('calendar_group_fk__isnull', True), ('is_organization_default', False), ('membership_user_id__isnull', False)), models.Q(('calendar_fk__isnull', True), ('calendar_group_fk__isnull', False), ('is_organization_default', False), ('membership_user_id__isnull', True)), models.Q(('calendar_fk__isnull', True), ('calendar_group_fk__isnull', True), ('is_organization_default', True), ('membership_user_id__isnull', True)), _connector='OR'), name='bookingpolicy_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('calendar_fk__isnull', False)), fields=('organization', 'calendar_fk'), name='bookingpolicy_uniq_calendar'), models.UniqueConstraint(condition=models.Q(('membership_user_id__isnull', False)), fields=('organization', 'membership_user_id'), name='bookingpolicy_uniq_membership'), models.UniqueConstraint(condition=models.Q(('calendar_group_fk__isnull', False)), fields=('organization', 'calendar_group_fk'), name='bookingpolicy_uniq_group'), models.UniqueConstraint(condition=models.Q(('is_organization_default', True)), fields=('organization',), name='bookingpolicy_uniq_org_default')],
            },
        ),
    ]
