# Generated by Django 6.0.5 on 2026-07-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0040_bookingpolicy_membership_protect_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarorganizationresourcesimport',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='not_started', max_length=50),
        ),
    ]
