# Generated by Django 6.0.5 on 2026-08-05 15:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0042_availabletime_blockedtime_group_slot'),
        ('organizations', '0022_organization_week_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarGroupSlotQuotaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], help_text='Fixed calendar period the cap applies to (day, week, or month).', max_length=10)),
                ('cap', models.PositiveIntegerField(help_text='Maximum number of live bookings made through this group slot a calendar may hold within one period. Must be at least 1.')),
                ('calendar', models.ForeignObject(editable=False, from_fields=['calendar_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_quota_rules', to='calendar_integration.calendar', to_fields=['id', 'organization_id'])),
                ('calendar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_quota_rules_fk_rel', to='calendar_integration.calendar')),
                ('group_slot', models.ForeignObject(editable=False, from_fields=['group_slot_fk', 'organization_id'], on_delete=django.db.models.deletion.CASCADE, related_name='quota_rules', to='calendar_integration.calendargroupslot', to_fields=['id', 'organization_id'])),
                ('group_slot_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_rules_fk_rel', to='calendar_integration.calendargroupslot')),
                ('organization', models.ForeignKey(help_text='The organization this model is associated with. Queries should use the `organization` field.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'group_slot_fk'], name='cgsquotarule_org_slot_idx')],
                'constraints': [models.UniqueConstraint(fields=('group_slot_fk', 'calendar_fk', 'period'), name='calendargroupslotquotarule_unique_slot_calendar_period'), models.CheckConstraint(condition=models.Q(('cap__gt', 0)), name='calendargroupslotquotarule_cap_positive')],
            },
        ),
    ]
