# Generated by Django 6.0.5 on 2026-08-05 15:53

from django.db import migrations

from calendar_integration.migrations.sql.functions.calculate_calendar_group_quota_period_counts import (
    CalculateCalendarGroupQuotaPeriodCountsMigrationManager,
)
from calendar_integration.migrations.sql.functions.get_calendar_group_quota_period_counts_json import (
    GetCalendarGroupQuotaPeriodCountsJSONMigrationManager,
)


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0043_calendargroupslotquotarule'),
    ]

    operations = [
        CalculateCalendarGroupQuotaPeriodCountsMigrationManager(
            "calendar_integration", "0001"
        ).migration(),
        GetCalendarGroupQuotaPeriodCountsJSONMigrationManager(
            "calendar_integration", "0001"
        ).migration(),
    ]
