# Generated by Django 6.0.5 on 2026-08-05 15:53

from django.db import migrations

from calendar_integration.migrations.sql.functions.calculate_appointment_type_quota_period_counts import (
    CalculateAppointmentTypeQuotaPeriodCountsMigrationManager,
)
from calendar_integration.migrations.sql.functions.get_appointment_type_quota_period_counts_json import (
    GetAppointmentTypeQuotaPeriodCountsJSONMigrationManager,
)


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0043_appointmenttypeslotquotarule'),
    ]

    operations = [
        CalculateAppointmentTypeQuotaPeriodCountsMigrationManager(
            "calendar_integration", "0001"
        ).migration(),
        GetAppointmentTypeQuotaPeriodCountsJSONMigrationManager(
            "calendar_integration", "0001"
        ).migration(),
    ]
