"""Move ``calendar_integration`` onto vinta-django-orgs' scoped mixin and relations.

Generated by ``makemigrations`` and then reviewed operation by operation, checking
the index diff rather than accepting it blind. What is in here, and why:

* ``AlterModelOptions`` on the nine models that declare no ``Meta`` of their own.
  They now inherit ``SingleOrganizationModelMixin.Meta``'s ``default_manager_name``
  / ``base_manager_name``. State only; ``sqlmigrate`` reports ``(no-op)``.
* ``AlterModelManagers`` on every model. State only.
* ``AlterField`` on each organization-safe relation. The concrete ``<name>_fk``
  column and the ``<name>`` ``ForeignObject`` beside it are byte-identical between
  ``organizations.OrganizationForeignKey`` and
  ``vinta_orgs.fields.OrganizationSafeForeignKey``; only the *spelling* of the join
  changes (``from_fields=('x_fk', 'organization')`` where it read
  ``('x_fk', 'organization_id')``, ``to_fields=(None, 'organization')`` where it read
  ``('id', 'organization_id')``). ``Options.get_field`` resolves a field by attname
  as well as by name, so both spellings resolve to the same two fields. State only.
* ``AlterField`` on each ``organization`` foreign key: ``db_index=False``, plus the
  loss of ``related_name='+'`` and the help text. The index it drops is a prefix of
  the ``(organization, id)`` index added below and so can answer no query the
  composite cannot.
* ``AddIndex`` of ``(organization, id)`` on all 31 concrete models, contributed by
  the package's ``class_prepared`` receiver. Every hand-authored organization-leading
  index in this app pairs ``organization`` with a *different* second column
  (``membership_user_id``, ``group_slot_fk``, ``calendar_fk``, ``provider``,
  ``resolved_by_user_id``), so none of them is redundant with this one and none is
  dropped: a composite on ``(organization, id)`` cannot answer a lookup on
  ``(organization, membership_user_id)``, and none of them gives the
  organization-scoped, primary-key-ordered walk this one exists for.
* One hand-added ``RemoveConstraint`` / ``AddConstraint`` pair -- see the comment at
  the operation itself.

**Lock audit.** Every ``AlterField`` on a foreign key drops and re-adds the column's
``FOREIGN KEY`` constraint with an identical definition, which takes
``ACCESS EXCLUSIVE`` on the table (and ``SHARE ROW EXCLUSIVE`` on
``organizations_organization``) for the length of the transaction, and the index
drops/creates are not ``CONCURRENTLY``. Deliberate, and consistent with
``organizations/migrations/0025``'s precedent: the operations are already
transactional and interdependent, and this project is pre-launch with no production
tenants. A live deployment would want the index work split out and run
``CONCURRENTLY`` outside a transaction.
"""

# ``to_fields=(None, 'organization')`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not.
# mypy: disable-error-code="arg-type"

import django.db.models.deletion
import django.db.models.manager
import vinta_orgs.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0044_add_quota_period_counting_functions'),
        ('public_api', '0008_remove_systemuser_scoped_to_membership_fk_and_more'),
        migrations.swappable_dependency(settings.ORGANIZATION_MEMBERSHIP_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarmanagementtokenpermission',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='calendarorganizationresourcesimport',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='calendarsync',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='childrencalendarrelationship',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='eventexternalattendance',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='externalattendee',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='googlecalendarserviceaccount',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recurrencerule',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='resourceallocation',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='availabletime',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='availabletimebulkmodification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='availabletimerecurrenceexception',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blockedtime',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blockedtimebulkmodification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blockedtimerecurrenceexception',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bookingpolicy',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendar',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarevent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendareventgroupselection',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendargroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendargroupslot',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendargroupslotmembership',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendargroupslotquotarule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarmanagementtoken',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarmanagementtokenpermission',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarorganizationresourcesimport',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarownership',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarsync',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarwebhookevent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='calendarwebhooksubscription',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='childrencalendarrelationship',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventattendance',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventbulkmodification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventexternalattendance',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventrecurrenceexception',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externalattendee',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externaleventchangerequest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='googlecalendarserviceaccount',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recurrencerule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourceallocation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='bulk_modification_parent',
            field=models.ForeignObject(editable=False, from_fields=('bulk_modification_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.availabletime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='group_slot',
            field=models.ForeignObject(editable=False, from_fields=('group_slot_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_scoped_available_times', to='calendar_integration.calendargroupslot', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=('parent_recurring_object_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.availabletime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='recurrence_rule',
            field=vinta_orgs.fields.OrganizationSafeOneToOneObject(editable=False, from_fields=('recurrence_rule_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=(None, 'organization'), unique=True),
        ),
        migrations.AlterField(
            model_name='availabletimebulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=('modified_continuation_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.availabletimebulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletimebulkmodification',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='availabletimebulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=('original_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.availabletimebulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletimebulkmodification',
            name='parent_available_time',
            field=models.ForeignObject(editable=False, from_fields=('parent_available_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.availabletime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletimerecurrenceexception',
            name='modified_available_time',
            field=models.ForeignObject(editable=False, from_fields=('modified_available_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.availabletime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='availabletimerecurrenceexception',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='availabletimerecurrenceexception',
            name='parent_available_time',
            field=models.ForeignObject(editable=False, from_fields=('parent_available_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.availabletime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='bulk_modification_parent',
            field=models.ForeignObject(editable=False, from_fields=('bulk_modification_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.blockedtime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=('bundle_calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_times', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=('bundle_primary_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_blocked_time_representations', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='group_slot',
            field=models.ForeignObject(editable=False, from_fields=('group_slot_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_scoped_blocked_times', to='calendar_integration.calendargroupslot', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=('parent_recurring_object_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.blockedtime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='recurrence_rule',
            field=vinta_orgs.fields.OrganizationSafeOneToOneObject(editable=False, from_fields=('recurrence_rule_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=(None, 'organization'), unique=True),
        ),
        migrations.AlterField(
            model_name='blockedtimebulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=('modified_continuation_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.blockedtimebulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtimebulkmodification',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedtimebulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=('original_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.blockedtimebulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtimebulkmodification',
            name='parent_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=('parent_blocked_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.blockedtime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtimerecurrenceexception',
            name='modified_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=('modified_blocked_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.blockedtime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='blockedtimerecurrenceexception',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedtimerecurrenceexception',
            name='parent_blocked_time',
            field=models.ForeignObject(editable=False, from_fields=('parent_blocked_time_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.blockedtime', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='calendar_group',
            field=models.ForeignObject(editable=False, from_fields=('calendar_group_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='calendar_integration.calendargroup', to_fields=(None, 'organization')),
        ),
        # Hand-added pair around the ``AlterField`` below, which is otherwise a
        # silent data-integrity regression. ``bookingpolicy_uniq_org_default`` is a
        # partial ``UniqueConstraint`` over the single column ``organization``, so
        # it exists in PostgreSQL as a unique *index* on that column. Django's
        # ``_alter_field`` drops every non-``Meta.indexes`` index on a column whose
        # ``db_index`` goes ``True -> False`` (it excludes ``Meta.indexes`` names but
        # not ``Meta.constraints`` names), and never puts this one back -- verified
        # against ``sqlmigrate``, which emits
        # ``DROP INDEX IF EXISTS "bookingpolicy_uniq_org_default"`` and no matching
        # ``CREATE``. Losing it would let a second organization-default booking
        # policy exist per organization, making ``BookingPolicyManager.org_default``
        # non-deterministic. Removing and re-adding it explicitly keeps the model
        # state unchanged (net zero) while making the drop and the recreation both
        # real operations.
        migrations.RemoveConstraint(
            model_name='bookingpolicy',
            name='bookingpolicy_uniq_org_default',
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_organization_default', True)), fields=('organization',), name='bookingpolicy_uniq_org_default'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='bulk_modification_parent',
            field=models.ForeignObject(editable=False, from_fields=('bulk_modification_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modifications', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=('bundle_calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_events', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='bundle_primary_event',
            field=models.ForeignObject(editable=False, from_fields=('bundle_primary_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_representations', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='calendar_group',
            field=models.ForeignObject(editable=False, from_fields=('calendar_group_fk', 'organization'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='calendar_integration.calendargroup', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='parent_recurring_object',
            field=models.ForeignObject(editable=False, from_fields=('parent_recurring_object_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_recurring_instances', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=vinta_orgs.fields.OrganizationSafeOneToOneObject(editable=False, from_fields=('recurrence_rule_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instance', to='calendar_integration.recurrencerule', to_fields=(None, 'organization'), unique=True),
        ),
        migrations.AlterField(
            model_name='calendareventgroupselection',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), on_delete=django.db.models.deletion.PROTECT, related_name='group_selections', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendareventgroupselection',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=('event_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='group_selections', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendareventgroupselection',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendareventgroupselection',
            name='slot',
            field=models.ForeignObject(editable=False, from_fields=('slot_fk', 'organization'), on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='calendar_integration.calendargroupslot', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroup',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendargroupslot',
            name='group',
            field=models.ForeignObject(editable=False, from_fields=('group_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendar_integration.calendargroup', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroupslot',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendargroupslotmembership',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_memberships', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroupslotmembership',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendargroupslotmembership',
            name='slot',
            field=models.ForeignObject(editable=False, from_fields=('slot_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='calendar_integration.calendargroupslot', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroupslotquotarule',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_quota_rules', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroupslotquotarule',
            name='group_slot',
            field=models.ForeignObject(editable=False, from_fields=('group_slot_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='quota_rules', to='calendar_integration.calendargroupslot', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendargroupslotquotarule',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtoken',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtoken',
            name='calendar_group',
            field=models.ForeignObject(editable=False, from_fields=('calendar_group_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='calendar_integration.calendargroup', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtoken',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=('event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tokens', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtoken',
            name='external_attendee',
            field=models.ForeignObject(editable=False, from_fields=('external_attendee_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_management_tokens', to='calendar_integration.externalattendee', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtoken',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtokenpermission',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarmanagementtokenpermission',
            name='token',
            field=models.ForeignObject(editable=False, from_fields=('token_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='calendar_integration.calendarmanagementtoken', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarorganizationresourcesimport',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarownership',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarownership',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarsync',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarsync',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarwebhookevent',
            name='calendar_sync',
            field=models.ForeignObject(editable=False, from_fields=('calendar_sync_fk', 'organization'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_sync_set', to='calendar_integration.calendarsync', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarwebhookevent',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarwebhookevent',
            name='subscription',
            field=models.ForeignObject(editable=False, from_fields=('subscription_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='calendar_integration.calendarwebhooksubscription', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarwebhooksubscription',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='calendarwebhooksubscription',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='childrencalendarrelationship',
            name='bundle_calendar',
            field=models.ForeignObject(editable=False, from_fields=('bundle_calendar_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='bundle_relationships', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='childrencalendarrelationship',
            name='child_calendar',
            field=models.ForeignObject(editable=False, from_fields=('child_calendar_fk', 'organization'), on_delete=django.db.models.deletion.CASCADE, related_name='bundle_children_relationships', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='childrencalendarrelationship',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=('event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='eventbulkmodification',
            name='modified_continuation',
            field=models.ForeignObject(editable=False, from_fields=('modified_continuation_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_continuation_set', to='calendar_integration.eventbulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventbulkmodification',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='eventbulkmodification',
            name='original_parent',
            field=models.ForeignObject(editable=False, from_fields=('original_parent_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_parent_set', to='calendar_integration.eventbulkmodification', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventbulkmodification',
            name='parent_event',
            field=models.ForeignObject(editable=False, from_fields=('parent_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_modification_records', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventexternalattendance',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=('event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventexternalattendance',
            name='external_attendee',
            field=models.ForeignObject(editable=False, from_fields=('external_attendee_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_attendances', to='calendar_integration.externalattendee', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventexternalattendance',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrecurrenceexception',
            name='modified_event',
            field=models.ForeignObject(editable=False, from_fields=('modified_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_for', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='eventrecurrenceexception',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrecurrenceexception',
            name='parent_event',
            field=models.ForeignObject(editable=False, from_fields=('parent_event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='externalattendee',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='externaleventchangerequest',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='googlecalendarserviceaccount',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_service_accounts', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='googlecalendarserviceaccount',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='calendar',
            field=models.ForeignObject(editable=False, from_fields=('calendar_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='calendar_integration.calendar', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='event',
            field=models.ForeignObject(editable=False, from_fields=('event_fk', 'organization'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='calendar_integration.calendarevent', to_fields=(None, 'organization')),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='organization',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddIndex(
            model_name='availabletime',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_845ede_idx'),
        ),
        migrations.AddIndex(
            model_name='availabletimebulkmodification',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_78a08d_idx'),
        ),
        migrations.AddIndex(
            model_name='availabletimerecurrenceexception',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_c72eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedtime',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_5de6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedtimebulkmodification',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_b431a8_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedtimerecurrenceexception',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_401c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpolicy',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_a4ca13_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_6cd695_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_6c113f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventgroupselection',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_7750fa_idx'),
        ),
        migrations.AddIndex(
            model_name='calendargroup',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_6bc339_idx'),
        ),
        migrations.AddIndex(
            model_name='calendargroupslot',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_189571_idx'),
        ),
        migrations.AddIndex(
            model_name='calendargroupslotmembership',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_a2192d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendargroupslotquotarule',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_5b3dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarmanagementtoken',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_4a8ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarmanagementtokenpermission',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_115d45_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarorganizationresourcesimport',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_090a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarownership',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_e2378a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsync',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_38094e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhookevent',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_5de216_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarwebhooksubscription',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_adf06f_idx'),
        ),
        migrations.AddIndex(
            model_name='childrencalendarrelationship',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_f371f8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_2f141f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbulkmodification',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_c397c1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventexternalattendance',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_8c37b6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrecurrenceexception',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_94f725_idx'),
        ),
        migrations.AddIndex(
            model_name='externalattendee',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_a67a24_idx'),
        ),
        migrations.AddIndex(
            model_name='externaleventchangerequest',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_15d4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarserviceaccount',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_963355_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_1daa92_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceallocation',
            index=models.Index(fields=['organization', 'id'], name='calendar_in_organiz_404781_idx'),
        ),
    ]
