"""Join ``Calendar.memberships`` through the organization-safe relation.

``through_fields`` named ``calendar_fk`` -- the *concrete* half of
``CalendarOwnership.calendar`` -- so the Calendar -> CalendarOwnership hop of the
many-to-many joined on the key alone, with no ``organization`` in the ``ON``
clause. It now names ``calendar``, the ``ForeignObject`` that joins on
``(calendar_fk, organization)``. See the comment at the field declaration.

State only: an explicit ``through`` model means this field owns no table and no
column, and ``sqlmigrate`` reports ``(no-op)`` for the single operation. What
changes is the SQL the ORM generates for ``calendar.memberships`` /
``membership.calendars`` from here on.

Generated by ``makemigrations``; reviewed and left as generated.
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0045_alter_calendarmanagementtokenpermission_options_and_more'),
        migrations.swappable_dependency(settings.ORGANIZATION_MEMBERSHIP_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='memberships',
            field=models.ManyToManyField(blank=True, related_name='calendars', through='calendar_integration.CalendarOwnership', through_fields=('calendar', 'membership'), to=settings.ORGANIZATION_MEMBERSHIP_MODEL),
        ),
    ]
