# Generated by Django 6.0.5 on 2026-08-17 13:29

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_integration', '0047_calendarevent_external_attendees_scoped_through'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('identified_key', models.BigIntegerField()),
                ('system', models.URLField(max_length=500)),
                ('identifier', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'content_type', 'identified_key'], name='extclientid_org_ct_key_idx'), models.Index(fields=['organization', 'id'], name='calendar_in_organiz_02b985_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'content_type', 'identified_key', 'system'), name='extclientid_uniq_target_system'), models.UniqueConstraint(fields=('organization', 'content_type', 'system', 'identifier'), name='extclientid_uniq_system_ident')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
