# Generated by Django 6.0.5 on 2026-08-27 05:20
#
# State-only: `NaiveDateTimeField` is a `DateTimeField` subclass with the same
# `db_type`, so `sqlmigrate` reports every operation here as a no-op. Nothing
# rewrites the columns -- which matters, because `start_time` / `end_time` are
# `GENERATED ALWAYS` columns derived from these six, and Postgres refuses to alter
# a column a generated column depends on. The change is entirely in how Python
# prepares a naive value for the write; see `common.fields.NaiveDateTimeField`.

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0048_externalclientidentifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabletime",
            name="end_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="availabletime",
            name="start_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="blockedtime",
            name="end_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="blockedtime",
            name="start_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time_tz_unaware",
            field=common.fields.NaiveDateTimeField(),
        ),
    ]
