# Generated by Django 6.0.5 on 2026-09-01 19:37

# ``to_fields=(None, 'organization')`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not. Same suppression, same
# reason, as ``calendar_integration/migrations/0045``.
# mypy: disable-error-code="arg-type"

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0058_backfill_calendargroup_duration"),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CalendarPoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "calendar",
                    models.ForeignObject(
                        editable=False,
                        from_fields=("calendar_fk", "organization"),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships",
                        to="calendar_integration.calendar",
                        to_fields=(None, "organization"),
                    ),
                ),
                (
                    "calendar_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_memberships_fk_rel",
                        to="calendar_integration.calendar",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignObject(
                        editable=False,
                        from_fields=("pool_fk", "organization"),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="calendar_integration.calendarpool",
                        to_fields=(None, "organization"),
                    ),
                ),
                (
                    "pool_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships_fk_rel",
                        to="calendar_integration.calendarpool",
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="calendarpool",
            name="calendars",
            field=models.ManyToManyField(
                related_name="pools",
                through="calendar_integration.CalendarPoolMembership",
                through_fields=("pool", "calendar"),
                to="calendar_integration.calendar",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarpoolmembership",
            index=models.Index(
                fields=["organization", "id"], name="calendar_in_organiz_ae135c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarpoolmembership",
            constraint=models.UniqueConstraint(
                fields=("pool_fk", "calendar_fk"),
                name="calendarpoolmembership_unique_pool_calendar",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarpool",
            index=models.Index(
                fields=["organization", "id"], name="calendar_in_organiz_b84180_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarpool",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="calendarpool_unique_name_per_org"
            ),
        ),
    ]
