# Generated by Django 6.0.5 on 2026-09-02 00:08

# ``to_fields=[None, 'organization']`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not. Same suppression, same
# reason, as ``calendar_integration/migrations/0045`` and ``0050``; the error code
# differs only because this generator emitted lists where 0050 emitted tuples.
# mypy: disable-error-code="list-item"

"""Calendar Pools Phase 3: slot <-> pool attachments and the roster projection.

Three changes, one of them delicate:

1. ``CalendarGroupSlotPool`` -- the slot <-> pool through table. ``pool_fk`` is
   PROTECT, which is what refuses deleting a pool any slot still references.
2. ``CalendarGroupSlotMembership.source_pool`` -- nullable, NULL meaning the row
   is inline. Every existing row takes NULL and is valid under both the old and
   the new constraint, so no backfill is needed.
3. **The constraint swap.** ``calendargroupslotmembership_unique_slot_calendar``
   on ``(slot_fk, calendar_fk)`` has to go, because the projected union
   deliberately allows one calendar to reach a slot from several sources. Its
   replacement is *two partial unique indexes*, not one three-column
   constraint: Postgres treats NULLs as distinct, so a plain
   ``UNIQUE(slot_fk, calendar_fk, source_pool_fk)`` would accept two INLINE rows
   for the same pair and silently corrupt ``required_count`` satisfaction
   counting. ``NULLS NOT DISTINCT`` would express this directly but needs
   Postgres 15+, and local development here runs Postgres 14, so the partial
   pair -- portable to every Postgres in play -- is what ships.

   The two ``AddConstraint`` operations are hand-ordered BEFORE the
   ``RemoveConstraint`` (``makemigrations`` emits the removal first) so the
   table is never briefly unconstrained. Every pre-existing row satisfies the
   new inline index the moment ``source_pool_fk`` exists and is NULL, so adding
   first cannot fail on live data.

Reversible in full, but not for free. On its own, reversing this migration
would re-add the old two-column ``UNIQUE(slot_fk, calendar_fk)`` constraint
BEFORE dropping the partial pair -- and it would fail with a duplicate-key
error doing it, on any slot where a calendar is present both inline and
projected, or projected from two pools, which is the normal state this phase
creates the moment a pool is attached anywhere. The no-op ``RunSQL`` below
carries the fix as its ``reverse_sql``: it deletes every projected row
(``source_pool_fk IS NOT NULL``) immediately before that constraint would be
re-added. That is safe on its own terms -- those rows are wholly derived from
``CalendarPoolMembership`` via ``CalendarGroupSlotPool``, never a primary
record of anything -- and it changes nothing about what the rest of the
reverse already does: ``CalendarGroupSlotPool`` (the attachments those rows
were projected from) is dropped a few operations later in this same reverse,
so the attachments themselves do not survive downgrading past this migration
either way. A subsequent re-forward starts with no attachments, same as the
day this migration first ran.
"""

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_integration", "0059_calendarpool_calendarpoolmembership_and_more"),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarGroupSlotPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="calendargroupslotmembership",
            name="source_pool",
            field=models.ForeignObject(
                editable=False,
                from_fields=["source_pool_fk", "organization"],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projected_slot_memberships",
                to="calendar_integration.calendarpool",
                to_fields=[None, "organization"],
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotmembership",
            name="source_pool_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="The pool this roster row was projected from, or NULL when the calendar was added to the slot directly. Only CalendarGroupService._reconcile_slot_pools writes non-NULL rows, and only it deletes them; the inline path never reads or writes them. CASCADE is safe here because CalendarGroupSlotPool.pool PROTECTs the pool for as long as any slot references it, so a pool with projected rows cannot reach this cascade.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projected_slot_memberships_fk_rel",
                to="calendar_integration.calendarpool",
            ),
        ),
        migrations.AddIndex(
            model_name="calendargroupslotmembership",
            index=models.Index(
                fields=["organization", "source_pool_fk"],
                name="cgsmembership_org_srcpool_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendargroupslotmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_pool_fk__isnull", True)),
                fields=("slot_fk", "calendar_fk"),
                name="calendargroupslotmembership_uniq_inline",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendargroupslotmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_pool_fk__isnull", False)),
                fields=("slot_fk", "calendar_fk", "source_pool_fk"),
                name="calendargroupslotmembership_uniq_projected",
            ),
        ),
        # Dropped LAST, after both replacements are in place, so the table is
        # never briefly without a uniqueness guarantee on (slot, calendar).
        migrations.RemoveConstraint(
            model_name="calendargroupslotmembership",
            name="calendargroupslotmembership_unique_slot_calendar",
        ),
        # No-op forward. On REVERSE, this runs right before the old two-column
        # constraint gets re-added (see the module docstring's "Reversible in
        # full" note): it clears every projected row so that re-add cannot hit
        # a duplicate-key error on a calendar reachable from more than one
        # source.
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=(
                "DELETE FROM calendar_integration_calendargroupslotmembership "
                "WHERE source_pool_fk_id IS NOT NULL;"
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotpool",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotpool",
            name="pool",
            field=models.ForeignObject(
                editable=False,
                from_fields=["pool_fk", "organization"],
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slot_attachments",
                to="calendar_integration.calendarpool",
                to_fields=[None, "organization"],
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotpool",
            name="pool_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slot_attachments_fk_rel",
                to="calendar_integration.calendarpool",
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotpool",
            name="slot",
            field=models.ForeignObject(
                editable=False,
                from_fields=["slot_fk", "organization"],
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_attachments",
                to="calendar_integration.calendargroupslot",
                to_fields=[None, "organization"],
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslotpool",
            name="slot_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_attachments_fk_rel",
                to="calendar_integration.calendargroupslot",
            ),
        ),
        migrations.AddField(
            model_name="calendargroupslot",
            name="pools",
            field=models.ManyToManyField(
                related_name="group_slots",
                through="calendar_integration.CalendarGroupSlotPool",
                through_fields=("slot", "pool"),
                to="calendar_integration.calendarpool",
            ),
        ),
        migrations.AddIndex(
            model_name="calendargroupslotpool",
            index=models.Index(
                fields=["organization", "id"], name="calendar_in_organiz_338f57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendargroupslotpool",
            constraint=models.UniqueConstraint(
                fields=("slot_fk", "pool_fk"),
                name="calendargroupslotpool_unique_slot_pool",
            ),
        ),
    ]
