# Generated by Django 6.0.5 on 2026-10-05 03:37

# ``to_fields=[None, "organization"]`` is what ``ForeignObject.deconstruct()`` emits;
# ``None`` means "the target's primary key", which Django accepts and django-stubs'
# ``Sequence[str]`` annotation does not. Same suppression and reason as 0060.
# mypy: disable-error-code="list-item"

"""Record which account opened a calendar's push channel.

Renewing a Google channel and syncing on its notifications both need an account,
and a provider push carries none. Additive and nullable, so it is reversible and
takes no long lock; existing rows get an account the next time their channel is
renewed.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_integration", "0066_dst_aware_recurrence_functions"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarwebhooksubscription",
            name="google_service_account",
            field=models.ForeignObject(
                editable=False,
                from_fields=["google_service_account_fk", "organization"],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_subscriptions",
                to="calendar_integration.googlecalendarserviceaccount",
                to_fields=[None, "organization"],
            ),
        ),
        migrations.AddField(
            model_name="calendarwebhooksubscription",
            name="google_service_account_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that opened the channel, when it is a Google service account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_subscriptions_fk_rel",
                to="calendar_integration.googlecalendarserviceaccount",
            ),
        ),
        migrations.AddField(
            model_name="calendarwebhooksubscription",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that opened the channel, when it is a user's social account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="socialaccount.socialaccount",
            ),
        ),
        migrations.AlterField(
            model_name="calendarwebhooksubscription",
            name="verification_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hex digest of the secret token sent with the channel. Google echoes the token on every notification; only the digest is stored.",
                max_length=255,
            ),
        ),
    ]
