# Generated by Django 6.0.5 on 2026-10-05 03:59

# ``to_fields=[None, 'organization']`` is what ``ForeignObject.deconstruct()``
# emits, and ``None`` means "the target's primary key" -- which Django accepts and
# django-stubs' ``Sequence[str]`` annotation does not. Same suppression, same
# reason, as ``calendar_integration/migrations/0060``.
# mypy: disable-error-code="list-item"

"""Resource calendar provider sync: the schema every later phase builds on.

Additive only. Four new tables (``ResourceLocation``,
``ResourceCalendarProviderLink``, ``ResourceCalendarCreateRequest``,
``MicrosoftOrganizationConnection``) and two columns on
``GoogleCalendarServiceAccount``. ``write_enabled`` carries a database default, so
containers still running the previous release can keep inserting service accounts
during a rolling deploy. Reversing drops the tables and columns; nothing reads them
until later phases ship, and those are behind the
``resource_calendar_provider_sync`` flag.
"""

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import uuid
import vinta_orgs.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_integration", "0066_dst_aware_recurrence_functions"),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarserviceaccount",
            name="write_enabled",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="True once the service account was verified to hold the admin.directory.resource.calendar scope, so Vinta Schedule can create, edit and delete rooms in Google Workspace. Only the organization-level account (no calendar) is used for room writes.",
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarserviceaccount",
            name="write_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When write access was last verified successfully.", null=True
            ),
        ),
        migrations.CreateModel(
            name="ResourceLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Calendar"),
                            ("google", "Google Calendar"),
                            ("microsoft", "Microsoft Outlook Calendar"),
                            ("apple", "Apple Calendar"),
                            ("ics", "ICS"),
                        ],
                        max_length=50,
                    ),
                ),
                ("external_building_id", models.CharField(max_length=255)),
                ("building_name", models.CharField(max_length=255)),
                ("external_floor_id", models.CharField(blank=True, max_length=255)),
                ("floor_name", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False once a resync no longer sees this location on the provider. Rows still referenced by a room are kept, inactive, rather than deleted.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        help_text="When a resync last saw this location on the provider."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ResourceCalendarProviderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Calendar"),
                            ("google", "Google Calendar"),
                            ("microsoft", "Microsoft Outlook Calendar"),
                            ("apple", "Apple Calendar"),
                            ("ics", "ICS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending_creation", "Pending Creation"),
                            ("synced", "Synced"),
                            ("pending_update", "Pending Update"),
                            ("pending_deletion", "Pending Deletion"),
                            ("sync_failed", "Sync Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "failed_operation",
                    models.CharField(
                        blank=True,
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        help_text="The provider write that failed. Set only while sync_status is sync_failed.",
                        max_length=16,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="The last provider error, shown to admins. Never holds credentials.",
                    ),
                ),
                ("provider_snapshot", models.JSONField(blank=True, default=dict)),
                ("pending_fields", models.JSONField(blank=True, default=dict)),
                (
                    "provisional_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Stable id sent to the provider so a replayed create finds the room it already made: Google resourceId vinta-<key>, Microsoft tag vinta-link-<key>.",
                        unique=True,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "retry_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="After this moment a failing push stops retrying and the link goes to sync failed.",
                        null=True,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flagged_bookings_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the provider deleted the room while it still had future bookings, which an admin must resolve.",
                        null=True,
                    ),
                ),
                (
                    "calendar",
                    vinta_orgs.fields.OrganizationSafeOneToOneObject(
                        editable=False,
                        from_fields=["calendar_fk", "organization"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_link",
                        to="calendar_integration.calendar",
                        to_fields=[None, "organization"],
                        unique=True,
                    ),
                ),
                (
                    "calendar_fk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_link_fk_rel",
                        to="calendar_integration.calendar",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignObject(
                        editable=False,
                        from_fields=["location_fk", "organization"],
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_links",
                        to="calendar_integration.resourcelocation",
                        to_fields=[None, "organization"],
                    ),
                ),
                (
                    "location_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_links_fk_rel",
                        to="calendar_integration.resourcelocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MicrosoftOrganizationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                ("tenant_id", models.CharField(blank=True, max_length=64)),
                (
                    "consent_state",
                    models.CharField(
                        blank=True,
                        help_text="Single-use nonce for the admin-consent round trip. Cleared once used.",
                        max_length=128,
                    ),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "write_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="True once the app-only token was verified to carry Place.ReadWrite.All and Calendars.Read and a Places read succeeded.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_verification_error", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "id"], name="calendar_in_organiz_84e813_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization",), name="msorgconnection_uniq_organization"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ResourceCalendarCreateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="meta")),
                ("idempotency_key", models.CharField(max_length=255)),
                (
                    "request_fingerprint",
                    models.CharField(
                        help_text="sha256 hex digest of the normalized create payload.",
                        max_length=64,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "calendar",
                    models.ForeignObject(
                        editable=False,
                        from_fields=["calendar_fk", "organization"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_requests",
                        to="calendar_integration.calendar",
                        to_fields=[None, "organization"],
                    ),
                ),
                (
                    "calendar_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_requests_fk_rel",
                        to="calendar_integration.calendar",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "id"], name="calendar_in_organiz_7c0db6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "idempotency_key"),
                        name="resourcecalcreatereq_uniq_key",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="resourcelocation",
            index=models.Index(
                fields=["organization", "id"], name="calendar_in_organiz_b0e94b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcelocation",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider", "external_building_id", "external_floor_id"),
                name="resourcelocation_uniq_provider_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecalendarproviderlink",
            index=models.Index(
                fields=["organization", "id"], name="calendar_in_organiz_52b85b_idx"
            ),
        ),
    ]
